//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtectionSpace.h"

@interface GDURLProtectionSpace : NSURLProtectionSpace
{
    struct __SecTrust *m_serverTrust;
}

+ (id)protectionSpaceWithHost:(id)arg1 port:(int)arg2 protocol:(id)arg3 realm:(id)arg4 authenticationMethod:(id)arg5 serverTrust:(struct __SecTrust *)arg6;
- (struct __SecTrust *)serverTrust;
- (void)dealloc;
- (id)initWithHost:(id)arg1 port:(int)arg2 protocol:(id)arg3 realm:(id)arg4 authenticationMethod:(id)arg5 serverTrust:(struct __SecTrust *)arg6;

@end

