/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface _ABAddressBookAddRecord (Automation)
- (BOOL)isAutomationScreenActive;
- (void)deactivateAutomationScreen;
- (void)activateAutomationScreen;
- (id)getTopAutomationScreenName;
- (id)getDefaultAutomationScreenName;
- (void)forceAutomationScreen;
- (void)updateAutomationScreenNameAndUpdateState:(id)fp8;
- (void)setAutomationScreen:(id)fp8;
@end

