/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface _ABAddressBookAddRecord (SBHTTPCookieStorage)
- (void)sbDeleteCookie:(id)fp8;
- (id)sbCookiesForURL:(id)fp8;
- (void)updateNativeCookieStorageFromSBStorage;
- (void)queueURLForUpdateInSBCookieStorage:(id)fp8;
- (void)flushPendingSBCookieStorageUpdates;
- (void)updateSBCookieStorageFromNativeCookieStorageForURL:(id)fp8 delayed:(BOOL)fp12;
- (BOOL)doWeNeedToSyncCookies:(id)fp8 NativeCookies:(id)fp12;
- (void)deleteSBCookiesForURL:(id)fp8;
- (void)selectiveAppendCookiesFromArray:(id)fp8 intoArray:(id)fp12;
- (id)sbCookies;
- (void)sbSetCookies:(id)fp8 forURL:(id)fp12 mainDocumentURL:(id)fp16;
- (void)sbSetCookie:(id)fp8;
- (void)enableSystemCookies:(BOOL)fp8;
@end

