/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface _ABAddressBookAddRecord (CustomSizeModal)
- (void)presentModalViewController:(id)fp8 animated:(BOOL)fp12 ofSize:(struct CGSize)fp16;
@end

