/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface _ABAddressBookAddRecord (ForceSize)
- (void)refreshPopoverSizeAfterReloadForTableView:(id)fp8;
- (void)setPopoverSizeForTableView:(id)fp8;
- (void)forcePopoverSize;
- (void)setContentSizeForPopover:(struct CGSize)fp8;
- (struct CGSize)contentSize;
- (struct CGSize)contentSizeForPopover;
@end

