/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol AppStorePolicyManagerDelegate <NSObject>
- (void)appStorePolicyManager:(id)fp8 switchView:(BOOL)fp12;
- (void)appStorePolicyManager:(id)fp8 updateApplication:(id)fp12;
- (void)appStorePolicyManager:(id)fp8 removedApplication:(id)fp12;
- (void)appStorePolicyManager:(id)fp8 addApplication:(id)fp12;
- (void)appStorePolicyManager:(id)fp8 enabledAppStore:(BOOL)fp12;
@end

