/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class AppStorePolicy, UIButton, UIImageView, UILabel, UITextView;

@interface AppStoreDetailViewController : _ABAddressBookAddRecord
{
    AppStorePolicy *policy;
    BOOL visible;
    UIButton *installButton;
    UILabel *nameLabel;
    UILabel *companyLabel;
    UITextView *descriptionTextView;
    UIImageView *iconImageView;
    UILabel *versionLabel;
    UILabel *dateLabel;
    UILabel *sizeLabel;
}

+ (id)sizeWithFormat:(unsigned long)fp8;
- (void)setSizeLabel:(id)fp8;
- (id)sizeLabel;
- (void)setDateLabel:(id)fp8;
- (id)dateLabel;
- (void)setVersionLabel:(id)fp8;
- (id)versionLabel;
- (void)setIconImageView:(id)fp8;
- (id)iconImageView;
- (void)setDescriptionTextView:(id)fp8;
- (id)descriptionTextView;
- (void)setCompanyLabel:(id)fp8;
- (id)companyLabel;
- (void)setNameLabel:(id)fp8;
- (id)nameLabel;
- (void)setInstallButton:(id)fp8;
- (id)installButton;
- (BOOL)visible;
- (id)policy;
- (void)reloadViewData;
- (void)install;
- (void)setPolicy:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;

@end

