/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GUKeyboardSizeHandlerVC.h"

@class NSString;

@interface AutoResponse : GUKeyboardSizeHandlerVC
{
    NSString *_autoResponseText;
    id <AutoResponseDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)autoResponseText;
- (void)fontSizeChanged;
- (void)dealloc;
- (void)showCharacterLimitReachedAlert;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (id)createTextView;
- (void)viewDidUnload;
- (void)setAutoResponseText:(id)fp8;
- (void)viewDidLoad;

@end

