/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FilteredCache.h"

@interface CalendarListFilteredCache : FilteredCache
{
}

- (void)replaceIndexSet:(id)fp8 mainCache:(id)fp12;
- (void)insertIndexSet:(id)fp8 mainCache:(id)fp12;
- (void)partitionIndexSet:(id)fp8 mainCache:(id)fp12 withBlock:(id)fp(null);
- (void)addAllDayOccurrences:(id)fp8;
- (void)addSectionsForAllDayOccurrences:(id)fp8;
- (void)allDayReplaceIndexSet:(id)fp8 mainCache:(id)fp12;
- (void)allDayInsertIndexSet:(id)fp8 mainCache:(id)fp12;
- (id)initWithFilter:(id)fp8 dataSourceCache:(id)fp12 delegate:(id)fp16;

@end

