/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface CalendarDbWrapper : _ABAddressBookAddRecord
{
    struct UIAListener *listener;
    BOOL _isDomino;
    int _allDayEventStartHour;
    int _allDayEventEndHour;
}

+ (id)sharedCalendarDb;
- (BOOL)isDomino;
- (int)allDayEventEndHour;
- (int)allDayEventStartHour;
- (void)dealloc;
- (BOOL)serverSupportsCalendarAttachments;
- (int)debugDump;
- (int)debugDeleteAllContent;
- (int)debugGetRecordCount;
- (void)debugAddRandomEvents:(int)fp8;
- (void)debugAddRandomEvents:(int)fp8 withStartDate:(id)fp12 endDate:(id)fp16;
- (void)debugAddRecurringEvents:(int)fp8 withStartDate:(id)fp12 endDate:(id)fp16;
- (BOOL)isSelfRecurringConflictFor:(id)fp8 withOldDate:(id)fp12 andNewDate:(id)fp16;
- (BOOL)removeFromEmail:(id)fp8;
- (id)dominoFindMeetingRequestListFromEmail:(id)fp8;
- (id)getAppointmentFromGoodId:(unsigned long)fp8 andInstance:(long)fp12;
- (void)respondToMeetingRequestFromCalendar:(id)fp8 response:(int)fp12 notes:(id)fp16 sendEmail:(BOOL)fp20 forAllOccurrences:(BOOL)fp24;
- (void)processMeetingRequestFromEmail:(id)fp8 response:(int)fp12 notes:(id)fp16 sendEmail:(BOOL)fp20 processList:(BOOL)fp24 fromList:(id)fp28;
- (void)updateAppointment:(id)fp8;
- (BOOL)respondToMeetingRequestFromEmail:(id)fp8 response:(int)fp12 notes:(id)fp16 sendEmail:(BOOL)fp20;
- (BOOL)isSendEmailNeeded:(id)fp8 appointment:(id)fp12;
- (BOOL)isMeetingRequestOutOfDate:(id)fp8 appointment:(id)fp12;
- (BOOL)amITheOrganizer:(id)fp8;
- (void)createMeetingNoneFromEmail:(id)fp8 recNum:(int)fp12;
- (int)findConflicts:(id)fp8;
- (id)getAppointmentFromEmail:(id)fp8;
- (id)findAppointmentsForRecordId:(unsigned int)fp8 startDate:(id)fp12 numberOfDays:(int)fp16;
- (id)findAppointmentsForPeriod:(id)fp8 numberOfDays:(int)fp12 useCache:(BOOL)fp16;
- (id)findAppointmentsForPeriod:(id)fp8 numberOfDays:(int)fp12;
- (id)findAppointmentsForDay:(id)fp8;
- (void)deleteAppointment:(id)fp8 applyAll:(BOOL)fp12;
- (void)saveAppointment:(id)fp8 applyAll:(BOOL)fp12;
- (void)copyRecordTZInfoTo:(struct ACalendarRecord *)fp8 from:(const struct ACalendarRecord *)fp12;
- (void)updateRecordTZInfo:(struct ACalendarRecord *)fp8;
- (void)saveInviteesFrom:(id)fp8 to:(struct ACalendarRecord *)fp12;
- (BOOL)createExceptionForWrapper:(id)fp8 withRecord:(struct ACalendarRecord *)fp12 andTemplate:(struct ACalendarRecord *)fp16 applyingTo:(int)fp20 recordWasCopied:(char *)fp24;
- (void)setListener:(id)fp8 withSelector:(SEL)fp12;
- (id)startup;
- (struct ACalendar *)calendarDb;

@end

