/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class PriorityTableViewCell;

@interface ClearPriorityButton : _ABAddressBookAddRecord
{
    PriorityTableViewCell *_assignedPriorityCell;
}

- (void)setAssignedPriorityCell:(id)fp8;
- (id)assignedPriorityCell;
- (void)dealloc;

@end

