/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class GUTextView;

@interface ConfigVC : _ABAddressBookAddRecord
{
    GUTextView *confContent;
}

- (void)setConfContent:(id)fp8;
- (id)confContent;
- (void)cancel:(id)fp8;
- (void)saveConfigFile;
- (void)keyboardDidHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;

@end

