/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ContactBubbledTextInputMgr, NSMutableArray, UITableView, UIView;

@interface ContactTypeDownAddressingMatchesTableViewMgr : _ABAddressBookAddRecord <UITableViewDelegate, UITableViewDataSource>
{
    UIView *parentView;
    struct CGRect originalTableViewFrame;
    NSMutableArray *matches;
    BOOL isGALLookupInProgress;
    BOOL isLastPositionRequired;
    ContactBubbledTextInputMgr *theContactBubbledTextInputMgr;
    id <ContactTypeDownAddressingMatchesTableViewMgrDelegate> delegate;
    UITableView *_tableView;
}

- (void)setTheContactBubbledTextInputMgr:(id)fp8;
- (id)theContactBubbledTextInputMgr;
- (void)setOriginalTableViewFrame:(struct CGRect)fp8;
- (struct CGRect)originalTableViewFrame;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setMatches:(id)fp8;
- (id)matches;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)dealloc;
- (void)updateTableViewFrame:(struct CGRect)fp8;
- (void)showTableView:(BOOL)fp8;
- (void)resetIndicator;
- (void)setMoreGalIndicator;
- (void)setContactLookupIndicator:(id)fp8;
- (void)displayMatches:(id)fp8;
- (void)resetDataSource;
- (void)preferredContentSizeChanged;
- (void)ensureTableViewCreated;
- (id)initWithTableViewFrame:(struct CGRect)fp8 parentView:(id)fp24;

@end

