/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString;

@interface ContactPerson : _ABAddressBookAddRecord <NSCopying>
{
    BOOL isGAL;
    BOOL isNotCompleted;
    NSString *_firstName;
    NSString *_middleName;
    NSString *_lastName;
    NSString *_companyName;
    NSString *_displayName;
    NSMutableArray *_emailAddresses;
    NSString *_sectionTitle;
    int recordID;
    int index;
    BOOL isDistributionList;
    int goodContactId;
    int _folderId;
    BOOL _isContactRTL;
}

- (void)setFolderId:(int)fp8;
- (int)folderId;
- (void)setGoodContactId:(int)fp8;
- (int)goodContactId;
- (void)setIsDistributionList:(BOOL)fp8;
- (BOOL)isDistributionList;
- (void)setSectionTitle:(id)fp8;
- (id)sectionTitle;
- (void)setIndex:(int)fp8;
- (int)index;
- (void)setRecordID:(int)fp8;
- (int)recordID;
- (void)setEmailAddresses:(id)fp8;
- (id)emailAddresses;
- (void)setDisplayName:(id)fp8;
- (id)displayName;
- (void)setIsContactRTL:(BOOL)fp8;
- (void)setCompanyName:(id)fp8;
- (id)companyName;
- (void)setLastName:(id)fp8;
- (id)lastName;
- (void)setMiddleName:(id)fp8;
- (id)middleName;
- (void)setFirstName:(id)fp8;
- (id)firstName;
- (void)setIsNotCompleted:(BOOL)fp8;
- (BOOL)isNotCompleted;
- (void)setIsGAL:(BOOL)fp8;
- (BOOL)isGAL;
- (void)dump;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)ensureFieldsFilled;
- (BOOL)isContactRTL;
- (void)fillRecordFields;
- (id)initGalWithID:(int)fp8;
- (id)initWithID:(int)fp8;

@end

