/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface Convert : _ABAddressBookAddRecord
{
}

+ (BOOL)wchar_t:(int *)fp8 OfMax:(unsigned long)fp12 FromNSString:(id)fp16;
+ (int *)GCHARFromNSString:(id)fp8;
+ (id)NSStringFromGCHAR:(const int *)fp8;

@end

