/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "EmailListViewController.h"

#import "UINavigationControllerDelegate-Protocol.h"

@class ConversationListItem, NSString;

@interface ConversationListTVC : EmailListViewController <UINavigationControllerDelegate>
{
    BOOL isLoaded;
    ConversationListItem *conversation;
    int configuredFolder;
    EmailListViewController *emailListVC;
    NSString *_conversationSearchTerm;
    NSString *_conversationSearchScope;
}

- (void)setConversationSearchScope:(id)fp8;
- (id)conversationSearchScope;
- (void)setConversationSearchTerm:(id)fp8;
- (id)conversationSearchTerm;
- (void)setEmailListVC:(id)fp8;
- (id)emailListVC;
- (void)setConfiguredFolder:(int)fp8;
- (int)configuredFolder;
- (void)setIsLoaded:(BOOL)fp8;
- (BOOL)isLoaded;
- (void)setConversation:(id)fp8;
- (id)conversation;
- (void)setMultiSelectMode:(BOOL)fp8 animated:(BOOL)fp12;
- (id)createMainFilteredCache;
- (void)saveFilterSortPreset:(int)fp8 forFolder:(int)fp12;
- (void)updateSearchScopeButtonTitles;
- (int)loadFilterSortPresetForFolder:(int)fp8;
- (void)reallyUpdateListTitle;
- (void)updateListTitle;
- (void)updateSubscribeView;
- (void)handleConversationModeOff;
- (void)dealloc;
- (id)navigationItem;
- (void)changeFolder:(int)fp8;
- (void)setupDefaultFolder;
- (void)conversationDidFinishLoading;
- (void)selectAndDisplayFirstEmail;
- (void)toggleSortFilterView:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)back:(id)fp8;
- (id)initWithConversation:(id)fp8 folder:(int)fp12 delegate:(id)fp16;
- (id)getDefaultAutomationScreenName;

@end

