/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GUOverlayModalViewMgr.h"

@class KLCalendarModel, UIDatePicker;

@interface DayPickeriPad : GUOverlayModalViewMgr
{
    UIDatePicker *datePicker;
    id <DatePickerHandler> datePickerHandler;
    KLCalendarModel *model;
}

+ (float)getPickerHeight;
- (void)setDatePickerHandler:(id)fp8;
- (id)datePickerHandler;
- (void)setDatePicker:(id)fp8;
- (id)datePicker;
- (void)dealloc;
- (void)goCancel:(id)fp8;
- (void)goToday:(id)fp8;
- (void)goOk:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)show:(BOOL)fp8;

@end

