/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface DFID : _ABAddressBookAddRecord
{
}

+ (id)dfid;
+ (id)dfidRawString;
+ (id)buildRawString;
+ (id)bootTime;
+ (id)carrierInfo;
+ (id)languageList;
+ (id)hasCydia;
+ (id)canOpenApps;
+ (id)diskSpace;
+ (id)getSysInfoByName:(char *)fp8;

@end

