/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GUNavigationController.h"

#import "EmailErrorDelegate-Protocol.h"
#import "FolderListViewControllerDelegate-Protocol.h"
#import "RecipientCertDelegate-Protocol.h"
#import "RecipientMapDelegate-Protocol.h"
#import "SendEmailNotesIdPasswordVCDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class EmailData, EmailVC, FileAttachmentView, FileViewer, FolderTVC, FolderViewData, GUBarButtonItem, GUToolBar, NSMutableArray, NoRotateNC, RecipientMap, UIActionSheet, UIButton, UINavigationItem, UIPopoverController, UIToolbar, UIView, UIViewController;

@interface EmailRootNC : GUNavigationController <FolderListViewControllerDelegate, UIActionSheetDelegate, UIPopoverControllerDelegate, SendEmailNotesIdPasswordVCDelegate, RecipientCertDelegate, RecipientMapDelegate, EmailErrorDelegate>
{
    FolderTVC *_folderTVC;
    EmailVC *_emailVC;
    NSMutableArray *_markFlagOptions;
    EmailVC *_composeEmailVC;
    GUNavigationController *_composeEmailNC;
    FileAttachmentView *_fileAttachmentView;
    UIViewController *_iPadRootViewController;
    NoRotateNC *_folderNC;
    NoRotateNC *_rightNC;
    UINavigationItem *_contentNavigationItem;
    UIActionSheet *_displayedActionSheet;
    GUBarButtonItem *_rightBarButtonItem;
    GUBarButtonItem *_leftBarButtonItem;
    BOOL _fullScreen;
    UIPopoverController *_currentPopover;
    UIView *_blockingView;
    FileViewer *_fileViewer;
    UIToolbar *_moveToolbar;
    UIToolbar *_contentToolbar;
    GUToolBar *_contentToolbarPad;
    GUBarButtonItem *_moveTitleButton;
    GUBarButtonItem *deleteButton;
    UIView *_pagingButtonsPad;
    UIButton *_pagingButtonPadUp;
    UIButton *_pagingButtonPadDown;
    FolderViewData *_folderViewData;
    BOOL _canReplyAll;
    int _userEmailReplyForwardAction;
    RecipientMap *_recipientMap;
    BOOL canDisplayErrorInOutbox;
    GUBarButtonItem *_moveBarButton;
    GUBarButtonItem *_moveBarButtonIPhone;
    GUBarButtonItem *flagBarButton;
    GUBarButtonItem *flagBarButtonIPhone;
    EmailData *selectedDEMInOutbox;
    GUBarButtonItem *_iphonePageDown;
    GUBarButtonItem *_iphonePageUp;
}

+ (int)mapSendingEmailProblemFromOutboxStatus:(int)fp8;
+ (id)navigationControllerWithRootViewController:(id)fp8;
+ (id)navigationController;
- (void)setIphonePageUp:(id)fp8;
- (id)iphonePageUp;
- (void)setIphonePageDown:(id)fp8;
- (id)iphonePageDown;
- (void)setContentToolbar:(id)fp8;
- (id)contentToolbar;
- (void)setSelectedDEMInOutbox:(id)fp8;
- (id)selectedDEMInOutbox;
- (void)setFolderTVC:(id)fp8;
- (id)folderTVC;
- (void)setFolderViewData:(id)fp8;
- (id)folderViewData;
- (void)setFileAttachmentView:(id)fp8;
- (id)fileAttachmentView;
- (void)setComposeEmailNC:(id)fp8;
- (id)composeEmailNC;
- (void)setComposeEmailVC:(id)fp8;
- (id)composeEmailVC;
- (void)setFileViewer:(id)fp8;
- (id)fileViewer;
- (BOOL)isFullScreen;
- (void)setCanDisplayErrorInOutbox:(BOOL)fp8;
- (BOOL)canDisplayErrorInOutbox;
- (void)setDeleteButton:(id)fp8;
- (id)deleteButton;
- (void)setFlagBarButtonIPhone:(id)fp8;
- (id)flagBarButtonIPhone;
- (void)setFlagBarButton:(id)fp8;
- (id)flagBarButton;
- (void)setMoveBarButtonIPhone:(id)fp8;
- (id)moveBarButtonIPhone;
- (void)setMoveBarButton:(id)fp8;
- (id)moveBarButton;
- (void)presentComposeForAppointment:(id)fp8 andType:(int)fp12;
- (void)emailErrorViewMessage;
- (void)emailErrorDeleteMessage;
- (void)emailErrorSendAsNew;
- (void)emailErrorTryAgain;
- (void)emailErrorSendUnencrypted;
- (void)removeCurrentViewControllerAnimated:(BOOL)fp8;
- (void)recipientCertSendEncryptedWhenPossible;
- (void)recipientCertDoNotEncryptMessage;
- (void)recipientCertRemoveRecipients;
- (void)handleRecipientCertOption:(int)fp8;
- (void)handleNotSentEmail:(int)fp8;
- (int)anyProblemsWithSendingEmail:(id)fp8;
- (void)showEmailErrorScreenForEmail:(id)fp8 withError:(int)fp12;
- (void)showRecipientScreenForEmail:(id)fp8;
- (void)showPasswordScreen;
- (void)backToPasswordRecipient;
- (void)emailNotesIdPasswordVCCancel;
- (void)emailNotesIdPasswordVCSendMessage;
- (BOOL)isDEMInOutboxOnline:(id)fp8;
- (void)showDEMInOutbox;
- (id)viewMessageButton;
- (void)composeReplyOrForwardSmimeEmail:(int)fp8;
- (void)dismissGoodPopover:(id)fp8;
- (void)reprovisionStarted:(id)fp8;
- (void)securityLockWillDisplay:(id)fp8;
- (void)actionSheetCancel:(id)fp8;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)folderListViewComplete:(id)fp8;
- (void)anotherFolderSelected:(int)fp8 moveItems:(id)fp16;
- (void)displayDownloadRestOfMsgConfirmationActionSheet;
- (void)displayAttachmentConfirmationActionSheet:(int)fp8;
- (void)forwardEmail:(id)fp8 withAttachments:(BOOL)fp12;
- (void)replyToEmail:(id)fp8 all:(BOOL)fp12 moreThan32Recipients:(BOOL)fp16;
- (void)replyToEmail:(id)fp8 all:(BOOL)fp12;
- (void)updateComposeEmailPaperclip;
- (void)displayComposeEmailView;
- (void)toggleFullScreen:(id)fp8;
- (void)deleteMessages:(id)fp8;
- (void)setMoveToolbarVisible:(BOOL)fp8;
- (void)generateMarkFlagOptions;
- (void)toolbarReply:(id)fp8;
- (void)toolbarMark:(id)fp8;
- (void)moveCancel:(id)fp8;
- (void)toolbarMove:(id)fp8;
- (void)toolbarDelete:(id)fp8;
- (void)toolbarPageEmail:(id)fp8;
- (void)toolbarComposeEmail:(id)fp8;
- (void)updateEmailHeaderView;
- (void)reloadFolder;
- (void)configureRightBarButtonItems:(unsigned short)fp8;
- (void)openDraftEmail:(id)fp8;
- (void)composeEmail;
- (void)blockDetailedView:(BOOL)fp8 withTitle:(id)fp12;
- (void)closeAVPlayer;
- (id)popToViewController:(id)fp8 animated:(BOOL)fp12;
- (id)popToRootViewControllerAnimated:(BOOL)fp8;
- (id)popViewControllerAnimated:(BOOL)fp8;
- (id)currentPopover;
- (void)setCurrentPopover:(id)fp8;
- (void)setDisplayedActionSheet:(id)fp8;
- (id)displayedActionSheet;
- (void)presentEmail:(id)fp8;
- (void)refreshEmailView:(id)fp8;
- (void)moveEmails:(id)fp8 sender:(id)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)canBecomeFirstResponder;
- (void)motionEnded:(int)fp8 withEvent:(id)fp12;
- (void)dealloc;
- (void)resetToolbars;
- (id)setupRightButtonToolBar:(id)fp8;
- (void)willPresentDisclaimer:(id)fp8;
- (void)recipientMapUpdated;
- (BOOL)isEmailComposing;
- (void)performInitialSetup;
- (void)updatePosition;
- (id)init;

@end

