/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class GUBarButtonItem, UIButton, UILabel, UIScrollView, UIView;

@interface EmailErrorVC : _ABAddressBookAddRecord
{
    int _errorType;
    UIScrollView *scrollView;
    UIButton *viewMessageButton;
    UIView *buttonsView;
    UIButton *deleteMessageButton;
    UIButton *sendMessageButton;
    UILabel *errorLabel;
    UILabel *decisionLabel;
    GUBarButtonItem *cancelButton;
    id <EmailErrorDelegate> delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setCancelButton:(id)fp8;
- (id)cancelButton;
- (void)setDecisionLabel:(id)fp8;
- (id)decisionLabel;
- (void)setErrorLabel:(id)fp8;
- (id)errorLabel;
- (void)setSendMessageButton:(id)fp8;
- (id)sendMessageButton;
- (void)setDeleteMessageButton:(id)fp8;
- (id)deleteMessageButton;
- (void)setButtonsView:(id)fp8;
- (id)buttonsView;
- (void)setViewMessageButton:(id)fp8;
- (id)viewMessageButton;
- (void)setScrollView:(id)fp8;
- (id)scrollView;
- (void)viewDidUnload;
- (void)cancel;
- (void)deleteMessage:(id)fp8;
- (void)sendMessage:(id)fp8;
- (void)viewMessage:(id)fp8;
- (struct CGSize)getViewSize;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)setupLookForButton:(id)fp8;
- (void)viewDidLoad;
- (void)layoutViews;
- (void)setYOffset:(float *)fp8 forView:(id)fp12;
- (void)dealloc;
- (id)initWithErrorType:(int)fp8;

@end

