/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol FilteredCacheFilter <NSObject>
- (BOOL)insertionIndexPathOfObject:(id)fp8 indexPath:(id *)fp12 inCache:(id)fp16;
- (id)filterCache:(id)fp8;
@end

