/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSMutableArray;

@interface FirstDayOfTheWeekViewController : _ABAddressBookAddRecord
{
    unsigned int _selectedRow;
    NSMutableArray *_items;
}

- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)dealloc;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)init;
- (id)getDefaultAutomationScreenName;

@end

