/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "FolderListViewDataDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FolderListViewData, FolderViewData, NSMutableArray, UIPopoverController;

@interface FolderListViewController : _ABAddressBookAddRecord <UITableViewDelegate, UITableViewDataSource, FolderListViewDataDelegate>
{
    FolderViewData *_data;
    FolderListViewData *m_folderListViewData;
    int _viewType;
    BOOL _cancelButtonEnabled;
    NSMutableArray *_moveArray;
    id <FolderListViewControllerDelegate> _delegate;
    int _ignoreFolderType;
    UIPopoverController *_popover;
}

- (void)setPopover:(id)fp8;
- (id)popover;
- (void)setIgnoreFolderType:(int)fp8;
- (int)ignoreFolderType;
- (void)setFolderListViewData:(id)fp8;
- (id)folderListViewData;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setMoveArray:(id)fp8;
- (id)moveArray;
- (int)viewType;
- (void)setData:(id)fp8;
- (id)data;
- (oneway void)release;
- (id)retain;
- (id)getImageName:(unsigned int)fp8;
- (void)complete;
- (void)folderListViewData:(id)fp8 didUpdateManifest:(BOOL)fp12;
- (void)expandOrCollapseFolder:(id)fp8 event:(id)fp12;
- (void)tableView:(id)fp8 accessoryButtonTappedForRowWithIndexPath:(id)fp12;
- (int)tableView:(id)fp8 indentationLevelForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (BOOL)folderSyncIsToggleableForFolder:(int)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)setCancelButtonEnabled:(BOOL)fp8;
- (void)refreshPopoverSize;
- (void)setViewType:(int)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)setupBars;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (id)initWithArray:(id)fp8;
- (id)initWithStyle:(int)fp8;
- (id)getDefaultAutomationScreenName;

@end

