/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GCFHTTPTransactorThread : _ABAddressBookAddRecord
{
    struct GHTTPTransactor *m_httpTransactor;
    BOOL inited;
}

- (void)setInited:(BOOL)fp8;
- (BOOL)inited;
- (void)doResetAuthCache;
- (void)resetAuthCache;
- (void)doGracefulShutdown;
- (void)gracefulShutdown;
- (void)onAbortCurrentRequestBasedOnId:(id)fp8;
- (void)onAbortCurrentProcessingAndFlushPoolsWithParams:(id)fp8;
- (void)onSignal:(id)fp8;
- (void)signalEvent:(id)fp8 withParam:(id)fp12;
- (void)main;
- (void)mainLoop;
- (void)abortCurrentRequestBasedOnId:(unsigned long)fp8 callbackObject:(id)fp12;
- (void)abortCurrentProcessingAndFlushPoolsWithCallback:(id)fp8 disconnectConstantConnection:(BOOL)fp12 disconnectSBProxy:(BOOL)fp16 blocking:(BOOL)fp20;
- (void)abortCurrentProcessing:(id)fp8;
- (void)dealloc;
- (id)initWithHttpTransactor:(struct GHTTPTransactor *)fp8;

@end

