/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GeoCoderHelperDelegate <NSObject>
- (void)geoCoderHelper:(id)fp8 resolveAddressString:(id)fp12 didComplete:(BOOL)fp16;
@end

