/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString;

@interface GeoCoderHistory : _ABAddressBookAddRecord
{
    struct sqlite3 *db;
    NSString *address;
    NSString *coordinates;
    int deletionDate;
}

+ (id)instance;
- (void)setDeletionDate:(int)fp8;
- (int)deletionDate;
- (void)setCoordinates:(id)fp8;
- (id)coordinates;
- (void)setAddress:(id)fp8;
- (id)address;
- (void)setDb:(struct sqlite3 *)fp8;
- (struct sqlite3 *)db;
- (void)dealloc;
- (void)computeDeletionDate;
- (void)dumpGeoCoderHistory;
- (void)clearGeoCoderHistory;
- (BOOL)deleteGeoCoderHistory;
- (BOOL)updateGeoCoderHistory;
- (BOOL)addGeoCoderHistory;
- (BOOL)getGeoCoderHistory;
- (id)startup;
- (BOOL)createOrUpdateSchema;

@end

