/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GTSocketCommunicationDelegate-Protocol.h"

@class NSData;

@interface GFEAttachCrypto : _ABAddressBookAddRecord <GTSocketCommunicationDelegate>
{
    id <GTSocketCommunicationDelegate> _delegate;
    BOOL _isEncrypting;
    unsigned int _blockSize;
    NSData *_leftoverData;
    unsigned int _totalBytesCoded;
    unsigned int _totalReceived;
}

+ (id)attachDecrypterTo:(id)fp8;
+ (id)attachEncrypterTo:(id)fp8;
+ (void)encryptData:(id)fp8 delegate:(id)fp12;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)finalizeCoding;
- (void)handleDataCoding:(id)fp8;
- (id)initWithDecryptDelegate:(id)fp8;
- (id)initWithEncryptDelegate:(id)fp8;
- (void)dealloc;
- (void)streamDidReceiveData:(id)fp8;
- (void)streamEndedWithError:(id)fp8;

@end

