/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSOperationQueue, NSTimer;

@interface GmmBackgroundHandler : _ABAddressBookAddRecord <CLLocationManagerDelegate>
{
    struct UIAListener *emailDBListener;
    BOOL wasSignaledToCancelBT;
    BOOL hasProbablyEnteredInactiveBackgroundState;
    BOOL radioSocketSpindown;
    int backgroundModes;
    NSOperationQueue *backgroundedOperationQueue;
    unsigned int backgroundTaskIdentifier;
    unsigned int connectionsClosingIdentifier;
    NSTimer *betterBatteryTimer;
    CLLocationManager *locationManager;
    id completionHandler;
}

+ (void)didReceiveRemoteBackgroundNotification:(id)fp8 fetchCompletionHandler:(id)fp(null) context:(void)fp12;
+ (void)setBackgroundMode:(int)fp8 enabled:(BOOL)fp12;
+ (BOOL)isBackgroundModeEnabled:(int)fp8;
+ (unsigned int)backgroundTask;
+ (void)ensureBackgroundTaskIsEnded;
+ (void)applicationWillEnterForeground;
+ (void)applicationDidEnterBackground;
+ (void)setBackgroundModes:(int)fp8;
+ (int)backgroundModes;
+ (void)restartBackgroundSyncTimeout;
+ (BOOL)isRadioSocketBeingClosed;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)instance;
- (void)setCompletionHandler:(id)fp(null);
- (id)completionHandler;
- (void)setRadioSocketSpindown:(BOOL)fp8;
- (BOOL)radioSocketSpindown;
- (void)setLocationManager:(id)fp8;
- (id)locationManager;
- (void)setBetterBatteryTimer:(id)fp8;
- (id)betterBatteryTimer;
- (void)setConnectionsClosingIdentifier:(unsigned int)fp8;
- (unsigned int)connectionsClosingIdentifier;
- (void)setHasProbablyEnteredInactiveBackgroundState:(BOOL)fp8;
- (BOOL)hasProbablyEnteredInactiveBackgroundState;
- (void)setBackgroundTaskIdentifier:(unsigned int)fp8;
- (unsigned int)backgroundTaskIdentifier;
- (void)setBackgroundedOperationQueue:(id)fp8;
- (id)backgroundedOperationQueue;
- (void)setWasSignaledToCancelBT:(BOOL)fp8;
- (BOOL)wasSignaledToCancelBT;
- (void)setBackgroundModes:(int)fp8;
- (int)backgroundModes;
- (void)locationManager:(id)fp8 didFailWithError:(id)fp12;
- (void)locationManager:(id)fp8 didUpdateToLocation:(id)fp12 fromLocation:(id)fp16;
- (void)ListenForMessage:(id)fp8;
- (void)unregisterToDBNotifications;
- (void)toggleGPSModes:(BOOL)fp8;
- (void)registerToDBNotifications;
- (void)stopGPSNotification;
- (void)startGPSNotification;
- (void)stopVOIPKeepAliveNotification;
- (void)startVOIPKeepAliveNotification;
- (void)stopSignificantChangeNotification;
- (void)startSignificantChangeNotification;
- (void)startBackgroundSynchronization;
- (void)endConnectionClosedBackgroundTask;
- (void)beginConnectionClosingBackgroundTask;
- (void)callAndClearCompletionHandlerWithResult:(unsigned int)fp8;
- (void)suspendConnections;
- (void)clearGalDB;
- (void)resumeSession4;
- (void)suspendSession4;
- (void)betterBatteryTimer:(id)fp8;
- (void)startFiniteExecutionHandler:(double)fp8;
- (void)dealloc;
- (id)init;

@end

