/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSData, NSMutableDictionary, NSOperationQueue, NSString;

@interface GmmDefaults : _ABAddressBookAddRecord
{
    NSMutableDictionary *valueStore;
    BOOL pendingUpdates;
    BOOL deriveKeyFailure;
    BOOL _isSyncEngineInitialized;
    BOOL _obfuscated;
    id <WipeDeviceProtocol> _wipeDelegate;
    id <DbStorageProtocol> _dbDelegate;
    NSString *_secureDefaultsFileName;
    NSString *_obfuscatedDefaultsFileName;
    NSString *_secureDefaultsFileBackup;
    NSData *_lastWrittenData;
    NSOperationQueue *_syncQueue;
}

+ (id)obfuscatedUserDefaults;
+ (id)insecureUserDefaults;
+ (id)secureUserDefaults;
- (void)setDbDelegate:(id)fp8;
- (id)dbDelegate;
- (void)setWipeDelegate:(id)fp8;
- (id)wipeDelegate;
- (void)syncEngineInitialized:(id)fp8;
- (void)upgradeContainersFromVersion:(int)fp8;
- (void)copyFromNSDefaults;
- (void)resetSecureDefaults;
- (BOOL)synchronize;
- (BOOL)synchronizeAndWait;
- (BOOL)forceSynchronize;
- (id)key;
- (void)loadFromPath:(id)fp8;
- (void)removeObjectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (id)secureDefaultsFileBackup;
- (id)obfuscatedDefaultsFileName;
- (id)secureDefaultsFileName;
- (void)dealloc;
- (id)initObfuscatedUserDefaults;
- (id)initWithSyncEngineState:(BOOL)fp8;

@end

