/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GmmEmailDebugHelper : _ABAddressBookAddRecord
{
}

+ (void)removeRandomEmailsFromInbox:(int)fp8 withDelay:(double)fp12;
+ (void)removeRandomEmailsFromInbox:(int)fp8;
+ (void)generateRandomEmailInEmailFolder:(int)fp8 contactArray:(id)fp16;
+ (void)generateRandomEmailsInEmailFolder:(int)fp8 count:(int)fp16 contactArray:(id)fp20 withDelay:(double)fp24;
+ (id)randomContactStringsFromContactArray:(id)fp8 count:(int)fp12;
+ (id)randomContactStringFromContactArray:(id)fp8;
+ (id)randomContactFromContactArray:(id)fp8;
+ (int)randomIntegerLessThan:(int)fp8;
+ (struct AnEmail *)keyValueStringDataToAnEmail:(id)fp8;
+ (BOOL)yesNoFromString:(id)fp8;
+ (int)msgImportanceFromString:(id)fp8;
+ (void)fillEmailRecipient:(struct AnEmailRecipient *)fp8 fromRecipientWrapper:(id)fp12;
+ (id)recipientFromString:(id)fp8;
+ (void)addXmlEmailsToDbFromFile:(id)fp8 intoEmailFolder:(int)fp12;
- (void)invokeRemoveRandomEmailFromInbox:(id)fp8;
- (void)invokeGenerateRandomEmailInEmailFolder:(id)fp8;

@end

