/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GmmComplianceStatusObserverDelegate-Protocol.h"
#import "GmmEasyActivationFeatureDelegate-Protocol.h"
#import "GmmEasyActivationRequestExpirationDelegate-Protocol.h"
#import "GmmRestrictedAccessKeyRequesterDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class GmmComplianceStatusObserver, GmmEasyActivationFeatureObserver, GmmEasyActivationProgressVC, NSMutableArray, UIAlertView;

@interface GmmEasyActivationHandler : _ABAddressBookAddRecord <GmmEasyActivationFeatureDelegate, GmmRestrictedAccessKeyRequesterDelegate, GmmEasyActivationRequestExpirationDelegate, UIAlertViewDelegate, GmmComplianceStatusObserverDelegate>
{
    NSMutableArray *_activationRequests;
    GmmComplianceStatusObserver *_complianceStatusObserver;
    GmmEasyActivationFeatureObserver *_easyActivationFeatureObserver;
    struct GmmRestrictedAccessKeyRequester *_keyRequester;
    GmmEasyActivationProgressVC *_progressVC;
    UIAlertView *_errorView;
    BOOL _gfeComplianceCheckPassed;
}

- (BOOL)isGmmDefaultsfeComplianceCheckPassed;
- (void)complianceCheckFinishedWithResult:(BOOL)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)requestExpired:(id)fp8;
- (void)didFinishWithAccessKey:(id)fp8 requestId:(int)fp12 errorCode:(id)fp16;
- (void)easyActivationFeatureEnabled:(BOOL)fp8;
- (void)dismissErrorView;
- (void)displayErrorViewForRequest:(id)fp8 withStatus:(int)fp12;
- (void)dismissProgressView;
- (void)displayProgressViewForRequest:(id)fp8;
- (void)startSendingPendingRequests;
- (void)applicationDidEnterBackground;
- (void)startEasyActivationFeatureObserver;
- (void)startKeyRequester;
- (void)authenticatorPolicyChanged;
- (void)updateActivationDelegateStatus;
- (id)requestWithId:(int)fp8;
- (BOOL)internalSynchronizedCancelActivationRequest:(id)fp8 andErrorCode:(int)fp12;
- (BOOL)internalCancelActivationRequest:(id)fp8 andErrorCode:(int)fp12;
- (void)internalHandleResponseForRequest:(id)fp8 withStatus:(int)fp12 withProvisioningId:(id)fp16 withPin:(id)fp20;
- (BOOL)internalSendActivationResponseForRequest:(id)fp8 withStatus:(int)fp12 withProvisioningId:(id)fp16 withPin:(id)fp20;
- (void)setGfeComplianceCheckPassed:(BOOL)fp8;
- (id)currentEasyActivationRequest;
- (BOOL)isActivationInProgress;
- (BOOL)canSendActivationRequest;
- (void)startObservers;
- (BOOL)sendPendingActivationRequests;
- (id)enqueueActivationRequestWithApplication:(id)fp8 withAppId:(id)fp12 withAppName:(id)fp16 withAppVersion:(id)fp20 withNonce:(id)fp24;
- (void)cancelAllActivationRequests;
- (BOOL)cancelActivationRequest:(id)fp8;
- (BOOL)sendActivationRequest:(id)fp8;
- (id)sendActivationRequestFor:(id)fp8 withAppId:(id)fp12 withAppName:(id)fp16 withAppVersion:(id)fp20 withNonce:(id)fp24;
- (void)dealloc;
- (id)init;

@end

