/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GmmEasyActivationDelegateStatusHandler : _ABAddressBookAddRecord
{
}

+ (id)activationDelegateStatusString;
+ (BOOL)isActivationDelegateStatusSaved;
+ (BOOL)savedActivationDelegateStatus;
+ (BOOL)expectedActivationDelegateStatus;
+ (void)updateActivationDelegateStatus:(BOOL)fp8;
+ (BOOL)shouldUpdateActivationDelegateStatus;

@end

