/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "SendLogCommandDelegate-Protocol.h"

@class GUAlertView, SendLogCommand, UIProgressView;

@interface GmmLogSender : _ABAddressBookAddRecord <SendLogCommandDelegate>
{
    id receiver;
    SEL callBack;
    SendLogCommand *sender;
    GUAlertView *progressAlert;
    UIProgressView *progressView;
    BOOL _sendQuietly;
}

- (void)setReceiver:(id)fp8;
- (id)receiver;
- (id)getMarkFilePath;
- (void)dealloc;
- (void)handleSendLogCommandBackground;
- (void)handleSendLogCommandResume;
- (void)handleSendLogCommandOkCancel;
- (void)handleSendLogBackgroundComplete;
- (BOOL)checkIfNeedSendLonWhenStart;
- (BOOL)removeMarkFileWhenShutdown;
- (BOOL)addMarkFileWhenStartUp;
- (void)sendLogsQuietly;
- (void)sendLogs;
- (void)sendLogWithCallback:(SEL)fp8 target:(id)fp12;
- (id)init;

@end

