/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GmmService.h"

@interface GmmOpenHttpUrlService : GmmService
{
}

+ (id)instance;
+ (void)initialize;
- (void)openBrowserUsingApplication:(id)fp8;
- (void)openUrl:(id)fp8 usingApplication:(id)fp12;
- (void)openUrl:(id)fp8 usingApplicationWithName:(id)fp12;
- (id)init;

@end

