/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString;

@interface GmmSecureStringObjC : _ABAddressBookAddRecord
{
    NSString *_backingStore;
}

+ (id)stringWithString:(id)fp8;
+ (id)stringWithGmmSecureStringObjC:(id)fp8;
+ (id)stringWithUTF8String:(const char *)fp8;
- (void)setBackingStore:(id)fp8;
- (id)backingStore;
- (id)dataUsingEncoding:(unsigned int)fp8;
- (id)newSecuredNSString;
- (int)compare:(id)fp8;
- (unsigned int)lengthOfBytesUsingEncoding:(unsigned int)fp8;
- (unsigned int)length;
- (const char *)cStringUsingEncoding:(unsigned int)fp8;
- (const char *)UTF8String;
- (id)stringByReplacingCharactersInRange:(struct _NSRange)fp8 withString:(id)fp16;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithString:(id)fp8;
- (id)initWithGmmSecureStringObjC:(id)fp8;
- (id)initWithUTF8String:(const char *)fp8;
- (void)dealloc;

@end

