/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSMutableDictionary, NSString;

@interface GmmService : _ABAddressBookAddRecord
{
    NSString *_serviceName;
    NSString *_serviceMinimumVersion;
    NSMutableDictionary *_requestHandlers;
}

- (void)setRequestHandlers:(id)fp8;
- (id)requestHandlers;
- (void)registerResponseHandler:(id)fp(null) forRequestID:(void)fp8;
- (id)appIdForApplicationWithName:(id)fp8;
- (BOOL)isSupportedByApplicationWithName:(id)fp8;
- (id)availableApplications;
- (BOOL)isServiceAvailable;
- (void)dealloc;
- (id)init;

@end

