/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GMMTask : _ABAddressBookAddRecord
{
    unsigned short _recordNumber;
    struct ATaskRecord *_taskRecord;
    BOOL _isNewTask;
}

- (struct ATaskRecord *)taskRecord;
- (void)setRecordNumber:(unsigned short)fp8;
- (unsigned short)recordNumber;
- (void)setTaskNotes:(id)fp8;
- (id)taskNotes;
- (void)setTaskSubject:(id)fp8;
- (id)taskSubject;
- (void)setTaskComplete:(BOOL)fp8;
- (BOOL)taskComplete;
- (void)setTaskReminderSet:(BOOL)fp8;
- (BOOL)taskReminderSet;
- (void)setTaskPercent:(int)fp8;
- (int)taskPercent;
- (void)setTaskStatus:(int)fp8;
- (int)taskStatus;
- (void)setTaskPriority:(int)fp8;
- (int)taskPriority;
- (void)setTaskVersion:(int)fp8;
- (int)taskVersion;
- (void)setTaskHostId:(int)fp8;
- (int)taskHostId;
- (void)setReminderDate:(id)fp8;
- (id)reminderDate;
- (void)setCompletedDate:(id)fp8;
- (id)completedDate;
- (void)setStartDate:(id)fp8;
- (id)startDate;
- (void)setDueDate:(id)fp8;
- (id)dueDate;
- (BOOL)recordIsDirty;
- (void)updateRecordInDB;
- (void)refreshTaskRecord;
- (void)dealloc;
- (void)save;
- (void)update;
- (id)initWithRecordNumber:(unsigned short)fp8;
- (id)init;

@end

