/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GoodTrustServicesHandlerObserver-Protocol.h"

@class NSData, NSString;

@interface GoodTrustServicesHandlerObserverSyncImpl : _ABAddressBookAddRecord <GoodTrustServicesHandlerObserver>
{
    struct Mutex _mutex;
    struct Cond _waitCond;
    NSData *_response;
    NSString *_requestId;
    int _responseType;
    int _error;
    int _errType;
    int _state;
}

- (void)setResponseType:(int)fp8;
- (int)responseType;
- (void)setErrType:(int)fp8;
- (int)errType;
- (void)setState:(int)fp8;
- (int)state;
- (void)setError:(int)fp8;
- (int)error;
- (void)setRequestId:(id)fp8;
- (id)requestId;
- (void)setResponse:(id)fp8;
- (id)response;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onError:(int)fp8 type:(int)fp12;
- (void)onResponseReceived:(int)fp8 withData:(id)fp12;
- (void)onRequestSent:(id)fp8;
- (void)dealloc;
- (id)init;

@end

