/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GoodNotifWrapper : _ABAddressBookAddRecord
{
    int whatHappened;
    int whoDidThis;
    unsigned long context1;
    unsigned long context2;
    unsigned long changeNumber;
}

- (void)setChangeNumber:(unsigned long)fp8;
- (unsigned long)changeNumber;
- (void)setContext2:(unsigned long)fp8;
- (unsigned long)context2;
- (void)setContext1:(unsigned long)fp8;
- (unsigned long)context1;
- (void)setWhoDidThis:(int)fp8;
- (int)whoDidThis;
- (void)setWhatHappened:(int)fp8;
- (int)whatHappened;
- (id)description;

@end

