/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GoodTrustServicesHandler : _ABAddressBookAddRecord
{
}

+ (BOOL)isServiceRequestPending;
+ (BOOL)cancelServiceRequest:(id)fp8;
+ (BOOL)sendSerivceRequest:(id)fp8 withObserver:(id)fp12;
+ (void)handleResponseFromApplication:(id)fp8 withParams:(id)fp12 withAttachments:(id)fp16 correspondingToRequestID:(id)fp20;
+ (id)smimeServiceAppId;
+ (id)smimeServiceNameForAppId:(id)fp8;
+ (id)serviceMethodName:(int)fp8;
+ (BOOL)hasValidRequestContext;
+ (id)getContextWithId:(id)fp8;
+ (BOOL)removeContextWithId:(id)fp8;
+ (BOOL)addContext:(id)fp8 with:(id)fp12;

@end

