/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GoodBAIViewController : _ABAddressBookAddRecord
{
    BOOL performCACSetup;
}

- (void)setPerformCACSetup:(BOOL)fp8;
- (BOOL)performCACSetup;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)dismissModalView:(BOOL)fp8;

@end

