/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "FilteredCacheDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CalendarOccurrence, FilteredCache, GTEventBubble, GTRecycleItemsQueue, NSDate, NSMutableArray;

@interface GTAllDayView : _ABAddressBookAddRecord <FilteredCacheDelegate, UIGestureRecognizerDelegate>
{
    id <GTAllDayViewDelegate> _delegate;
    FilteredCache *_filteredCache;
    NSMutableArray *_bubbles;
    GTRecycleItemsQueue *_bubbleQueue;
    NSDate *_date;
    CalendarOccurrence *occurrenceToWatchAndNotifyWhenShown;
    GTEventBubble *_pressedBubble;
    struct CGPoint _locationOfInitialPress;
}

- (void)setPressedBubble:(id)fp8;
- (id)pressedBubble;
- (void)setLocationOfInitialPress:(struct CGPoint)fp8;
- (struct CGPoint)locationOfInitialPress;
- (void)setOccurrenceToWatchAndNotifyWhenShown:(id)fp8;
- (id)occurrenceToWatchAndNotifyWhenShown;
- (void)setDate:(id)fp8;
- (id)date;
- (void)setBubbleQueue:(id)fp8;
- (id)bubbleQueue;
- (void)setBubbles:(id)fp8;
- (id)bubbles;
- (id)filteredCache;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)recycleBubble:(id)fp8;
- (id)getNewBubble;
- (void)updateBubblesForOccurrences:(id)fp8;
- (void)filteredCache:(id)fp8 didUpdateRowsAtIndexPaths:(id)fp12;
- (void)filteredCache:(id)fp8 didRemoveRowsAtIndexPaths:(id)fp12;
- (void)deleteBubblesForOccurrences:(id)fp8;
- (void)filteredCache:(id)fp8 willRemoveRowsAtIndexPaths:(id)fp12;
- (void)adjustViewHeight;
- (void)updateShapeOfBubble:(id)fp8;
- (void)addBubblesForOccurrences:(id)fp8;
- (void)notifyBubbleShown:(id)fp8;
- (id)eventBubbleForOccurrence:(id)fp8;
- (void)filteredCache:(id)fp8 didAddRowsAtIndexPaths:(id)fp12;
- (void)filteredCache:(id)fp8 didRemoveSectionsAtIndexes:(id)fp12;
- (void)filteredCache:(id)fp8 didAddSectionsAtIndexes:(id)fp12;
- (void)didInitiallyLoadDataForFilteredCache:(id)fp8;
- (void)viewLongPresssed:(id)fp8;
- (void)eventBubbleDidShow:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)setFilteredCache:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

