/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTCalendarViewController.h"

@class GTCalendarDrawerVC;

@interface GTCalendarViewController_iPad : GTCalendarViewController
{
    GTCalendarDrawerVC *_calendarDrawerVC;
}

- (void)setCalendarDrawerVC:(id)fp8;
- (id)calendarDrawerVC;
- (void)updateCalendarAppearance;
- (void)didSelectModule:(id)fp8 atIndex:(int)fp12;
- (void)setCurrentViewController:(id)fp8;
- (void)setupBarButtonItems;
- (void)viewWillUnload;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (void)dealloc;

@end

