/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class UIActivityIndicatorView;

@interface GTCalendarLoadingView : _ABAddressBookAddRecord
{
    UIActivityIndicatorView *_activityIndicator;
}

- (void)setActivityIndicator:(id)fp8;
- (id)activityIndicator;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

