/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "UIAccessibilityIdentification-Protocol.h"

@class CalendarOccurrence, NSString, UIImageView, UILabel;

@interface GTCalendarEventTableCell : _ABAddressBookAddRecord <UIAccessibilityIdentification>
{
    float _rightSidePadding;
    BOOL _darkStyle;
    BOOL _highlightedCell;
    UILabel *_subjectLabel;
    UILabel *_locationLabel;
    UILabel *_timeStartLabel;
    UILabel *_timeEndLabel;
    UIImageView *_iconRightImageView;
    UIImageView *_iconLeftImageView;
    UIImageView *_statusView;
    CalendarOccurrence *_occurrence;
    NSString *_accessibilityIdentifier;
}

+ (float)estimatedHeight;
+ (void)initialize;
- (void)setAccessibilityIdentifier:(id)fp8;
- (id)accessibilityIdentifier;
- (void)setHighlightedCell:(BOOL)fp8;
- (BOOL)highlightedCell;
- (BOOL)darkStyle;
- (id)occurrence;
- (void)setStatusView:(id)fp8;
- (id)statusView;
- (void)setIconLeftImageView:(id)fp8;
- (id)iconLeftImageView;
- (void)setIconRightImageView:(id)fp8;
- (id)iconRightImageView;
- (void)setTimeEndLabel:(id)fp8;
- (id)timeEndLabel;
- (void)setTimeStartLabel:(id)fp8;
- (id)timeStartLabel;
- (void)setLocationLabel:(id)fp8;
- (id)locationLabel;
- (void)setSubjectLabel:(id)fp8;
- (id)subjectLabel;
- (void)setFonts;
- (void)setupCellFromOccurrence;
- (void)setupStatusBar;
- (void)setupIconsAndLocationSize;
- (void)setupDates;
- (void)setupSubjectAndLocation;
- (void)layoutSubviews;
- (void)setOccurrence:(id)fp8;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (void)setFrame:(struct CGRect)fp8;
- (void)prepareForReuse;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)awakeFromNib;
- (void)viewLongPresssed:(id)fp8;
- (void)highlightCell;
- (void)setDarkStyle:(BOOL)fp8;
- (void)dealloc;

@end

