/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GTConnectionMonitor : _ABAddressBookAddRecord
{
    struct __SCNetworkReachability *reachabilityRef;
}

+ (id)reachabilityForInternetConnection;
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)fp8;
- (int)currentReachabilityStatus:(_Bool)fp8;
- (int)currentReachabilityStatus;
- (int)networkStatusForFlags:(unsigned int)fp8 andPrintNetworkStatus:(_Bool)fp12;
- (void)dealloc;
- (void)stopNotifier;
- (BOOL)startNotifier;

@end

