/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSDate;

@interface GTDateRange : _ABAddressBookAddRecord
{
    NSDate *_startDate;
    NSDate *_endDate;
}

+ (id)rangeFromDate:(id)fp8 toDate:(id)fp12;
- (id)endDate;
- (id)startDate;
- (void)dealloc;
- (id)initWithIntervalFromDate:(id)fp8 interval:(double)fp12;
- (id)initFromDate:(id)fp8 toDate:(id)fp12;

@end

