/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString;

@interface GTInfiniteScrollCell : _ABAddressBookAddRecord
{
    int _index;
    NSString *_reuseIdentifer;
}

- (void)setReuseIdentifer:(id)fp8;
- (id)reuseIdentifer;
- (void)setIndex:(int)fp8;
- (int)index;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)fp8 reuseIdentifier:(id)fp24;
- (void)dealloc;

@end

