/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSMutableArray, UILabel;

@interface GTInfiniteScrollDatePickerMonthCellHeader : _ABAddressBookAddRecord
{
    NSMutableArray *_weekdayLabels;
    UILabel *_title;
}

+ (void)initialize;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setWeekdayLabels:(id)fp8;
- (id)weekdayLabels;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 date:(id)fp24;

@end

