/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GTInfiniteScrollViewDataSource <NSObject>
- (struct CGSize)infiniteScrollView:(id)fp8 sizeOfViewAtIndex:(int)fp12;
- (id)infiniteScrollView:(id)fp8 viewAtIndex:(int)fp12;
@end

