/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray;

@interface GTPagingSliderView : _ABAddressBookAddRecord <UIScrollViewDelegate>
{
    NSArray *_pageViews;
    struct CGRect _currentFrame;
    int _currentIndex;
    int _indexOnDelegate;
    BOOL shouldPreloadViews;
    id <GTPagingSliderDelegate> pagingDelegate;
    Class pageViewClass;
    int scrollDirection;
}

+ (id)sliderWithViewClass:(Class)fp8 frame:(struct CGRect)fp12 delegate:(id)fp28;
- (void)setIndexOnDelegate:(int)fp8;
- (void)setScrollDirection:(int)fp8;
- (int)scrollDirection;
- (void)setShouldPreloadViews:(BOOL)fp8;
- (BOOL)shouldPreloadViews;
- (Class)pageViewClass;
- (void)setPagingDelegate:(id)fp8;
- (id)pagingDelegate;
- (id).cxx_construct;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollWithDeltaIndex:(int)fp8;
- (void)reloadPages;
- (void)jumpToIndex:(int)fp8;
- (void)resetPagesPostion;
- (void)setPagesPosition;
- (id)nextView;
- (id)currentView;
- (id)previousView;
- (void)setFrame:(struct CGRect)fp8;
- (void)adjustViewSize;
- (void)setPageViewClass:(Class)fp8;
- (void)createPages;
- (void)setPageViews:(id)fp8;
- (int)indexOnDelegate;
- (void)setIndexOnDelegate:(int)fp8 byCallToJumpToIndex:(BOOL)fp12;
- (void)dealloc;
- (void)setupSelf;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;

@end

