/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class GTArrowView, NSString, UIActivityIndicatorView, UILabel, UITableView, UIView;

@interface GTPullToRefreshTVC : _ABAddressBookAddRecord
{
    BOOL _isMultiSelectMode;
    BOOL _isEnabled;
    UILabel *_actionLabel;
    UIView *_refreshHeaderView;
    float _refreshHeaderHeight;
    UILabel *_upperMidLabel;
    UILabel *_lowerMidLabel;
    UILabel *_upperLabel;
    UILabel *_midLabel;
    UILabel *_lowerLabel;
    UIActivityIndicatorView *_activityIndicator;
    GTArrowView *_gtArrowView;
    NSString *_textPull;
    NSString *_textRelease;
    NSString *_textLoading;
    float _refreshLabelWidth;
    UITableView *currentTableView;
}

- (void)setCurrentTableView:(id)fp8;
- (id)currentTableView;
- (void)setRefreshHeaderView:(id)fp8;
- (id)refreshHeaderView;
- (void)setIsEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (void)setIsMultiSelectMode:(BOOL)fp8;
- (BOOL)isMultiSelectMode;
- (void)setRefreshLabelWidth:(float)fp8;
- (float)refreshLabelWidth;
- (void)setTextLoading:(id)fp8;
- (id)textLoading;
- (void)setTextRelease:(id)fp8;
- (id)textRelease;
- (void)setTextPull:(id)fp8;
- (id)textPull;
- (void)setGtArrowView:(id)fp8;
- (id)gtArrowView;
- (void)setActivityIndicator:(id)fp8;
- (id)activityIndicator;
- (void)setLowerLabel:(id)fp8;
- (id)lowerLabel;
- (void)setMidLabel:(id)fp8;
- (id)midLabel;
- (void)setUpperLabel:(id)fp8;
- (id)upperLabel;
- (void)setLowerMidLabel:(id)fp8;
- (id)lowerMidLabel;
- (void)setUpperMidLabel:(id)fp8;
- (id)upperMidLabel;
- (void)setRefreshHeaderHeight:(float)fp8;
- (float)refreshHeaderHeight;
- (void)viewDidUnload;
- (void)startLoading;
- (void)stopLoading;
- (void)refreshHeaderWasHidden;
- (void)hidePullToRefreshHeader;
- (void)showPullToRefreshHeader;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)releaseActionNotTriggered;
- (void)releaseActionTriggered;
- (void)scrollViewDidScroll:(id)fp8;
- (void)updatePullText;
- (void)updateReleaseText;
- (BOOL)canUpdateArrow;
- (BOOL)canUpdateContent;
- (void)prepareHeaderForEditingMode:(BOOL)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)isEntireRefreshHeaderCurrentlyShownToUser;
- (BOOL)isPullToRefreshHeaderActive;
- (void)addPullToRefreshHeaderToCurrentTableView;
- (void)setupStrings;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidLoad;
- (void)dealloc;
- (void)initGTPullToRefreshTVC;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithStyle:(int)fp8;
- (void)logStringFromGTPullToRefresh:(id)fp8;
- (void)logAndExecuteAssertForUnexpectedValue:(id)fp8 inFunction:(id)fp12;

@end

