/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSMutableDictionary;

@interface GTRecycleItemsQueue : _ABAddressBookAddRecord
{
    NSMutableDictionary *_recycleItemsQueueDictionary;
}

- (void)setRecycleItemsQueueDictionary:(id)fp8;
- (id)recycleItemsQueueDictionary;
- (void)handleLowMemoryWarning:(id)fp8;
- (void)enqueueRecycleItem:(id)fp8 withIdentifer:(id)fp12;
- (id)dequeueRecycleItemWithIdentifier:(id)fp8;
- (id)init;
- (void)dealloc;

@end

