/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GTDayGridViewDelegate-Protocol.h"
#import "GTWeekAllDayViewDelegate-Protocol.h"

@class GTCalendarGridView, GTCalendarWeekStripView, GTWeekAllDayView, NSDate, NSMutableArray, NSOperationQueue, UIImageView, UILabel, UIScrollView, UIView;

@interface GTWeekView : _ABAddressBookAddRecord <GTDayGridViewDelegate, GTWeekAllDayViewDelegate>
{
    float _topInset;
    struct CGSize _allDayLabelSize;
    BOOL _dayIsSelected;
    NSDate *_date;
    id <GTCalendarViewDataSource> _dataSourceDelegate;
    GTCalendarWeekStripView *_weekStrip;
    UIView *_allDayContainer;
    UILabel *_allDayLabel;
    UIScrollView *_allDayScrollView;
    GTWeekAllDayView *_allDayView;
    UIScrollView *_dayScrollView;
    GTCalendarGridView *_gridView;
    NSMutableArray *_allDayLines;
    NSMutableArray *_dayLines;
    UIView *_dayContainer;
    id <GTWeekViewDelegate> _delegate;
    UILabel *_workWeekLabel;
    UIImageView *_doubleRedLinesView;
    UIImageView *_allDaySeperatorLineView;
    NSOperationQueue *_renderOperationQueue;
    UIView *_selectedDayColumnView;
    UIView *_selectedAllDayColumnView;
    UIImageView *_selectedDayShadowView;
    UIImageView *_selectedAllDayShadowView;
}

+ (void)initialize;
- (void)setDayIsSelected:(BOOL)fp8;
- (BOOL)dayIsSelected;
- (void)setSelectedAllDayShadowView:(id)fp8;
- (id)selectedAllDayShadowView;
- (void)setSelectedDayShadowView:(id)fp8;
- (id)selectedDayShadowView;
- (void)setSelectedAllDayColumnView:(id)fp8;
- (id)selectedAllDayColumnView;
- (void)setSelectedDayColumnView:(id)fp8;
- (id)selectedDayColumnView;
- (void)setRenderOperationQueue:(id)fp8;
- (id)renderOperationQueue;
- (void)setAllDaySeperatorLineView:(id)fp8;
- (id)allDaySeperatorLineView;
- (void)setDoubleRedLinesView:(id)fp8;
- (id)doubleRedLinesView;
- (void)setWorkWeekLabel:(id)fp8;
- (id)workWeekLabel;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setDayContainer:(id)fp8;
- (id)dayContainer;
- (void)setDayLines:(id)fp8;
- (id)dayLines;
- (void)setAllDayLines:(id)fp8;
- (id)allDayLines;
- (void)setGridView:(id)fp8;
- (id)gridView;
- (void)setDayScrollView:(id)fp8;
- (id)dayScrollView;
- (void)setAllDayView:(id)fp8;
- (id)allDayView;
- (void)setAllDayScrollView:(id)fp8;
- (id)allDayScrollView;
- (void)setAllDayLabel:(id)fp8;
- (id)allDayLabel;
- (void)setAllDayContainer:(id)fp8;
- (id)allDayContainer;
- (void)setWeekStrip:(id)fp8;
- (id)weekStrip;
- (void)setDataSourceDelegate:(id)fp8;
- (id)dataSourceDelegate;
- (id)date;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (int)offsetInSecondsOfGridCenter;
- (void)centerGridToOffsetInSeconds:(int)fp8;
- (void)allDayWeekView:(id)fp8 willRemoveFilteredCache:(id)fp12;
- (void)allDayWeekView:(id)fp8 addCalendarEventAt:(id)fp12 fromPoint:(struct CGPoint)fp16 inView:(id)fp24 allDay:(BOOL)fp28;
- (void)allDayWeekView:(id)fp8 didTouchBubble:(id)fp12;
- (void)allDayWeekView:(id)fp8 didChangeFrame:(struct CGRect)fp12;
- (void)dayGridView:(id)fp8 addCalendarEventAt:(id)fp12 fromPoint:(struct CGPoint)fp16 inView:(id)fp24 allDay:(BOOL)fp28;
- (void)dayGridView:(id)fp8 didTouchBubble:(id)fp12;
- (void)dayGridView:(id)fp8 touchedInRangeOfBubbles:(id)fp12;
- (void)removeOldFilteredCaches;
- (void)handleTimeUpdateNotification:(id)fp8;
- (void)setDate:(id)fp8;
- (void)deselectDate;
- (void)setSelectedDateFromDate:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)updateWeekLabel;
- (void)addDoubleRedLines;
- (float)topInset;
- (void)setTopInset:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 dataSourceDelegate:(id)fp24;
- (void)dealloc;

@end

