/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GUBarButtonItem.h"

@interface GUBarButtonItemiOS6 : GUBarButtonItem
{
}

- (void)setTag:(int)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (void)setImage:(id)fp8;
- (id)button;
- (void)setButton:(id)fp8;
- (void)setAccessibilityIdentifier:(id)fp8;
- (void)dealloc;
- (id)initWithTitle:(id)fp8 style:(int)fp12 target:(id)fp16 action:(SEL)fp20;
- (id)initWithTitle:(id)fp8 font:(id)fp12 textGutterWidth:(float)fp16 style:(int)fp20 target:(id)fp24 action:(SEL)fp28;
- (id)imageForSystemItem:(int)fp8;
- (id)initWithBarButtonSystemItem:(int)fp8 target:(id)fp12 action:(SEL)fp16;
- (id)initWithImage:(id)fp8 landscapeImagePhone:(id)fp12 style:(int)fp16 target:(id)fp20 action:(SEL)fp24;
- (id)initWithImage:(id)fp8 size:(struct CGSize)fp12 style:(int)fp20 target:(id)fp24 action:(SEL)fp28;
- (id)initWithImage:(id)fp8 style:(int)fp12 target:(id)fp16 action:(SEL)fp20;
- (id)initWithCustomView:(id)fp8;

@end

