/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GUDrawTextHelper : _ABAddressBookAddRecord
{
}

+ (struct CGSize)GUDrawShadowedText:(id)fp8 inContext:(struct CGContext *)fp12 withFont:(id)fp16 simulatedBold:(BOOL)fp20 inRect:(struct CGRect)fp24 lineBreakMode:(int)fp40 color:(id)fp44 shadowColor:(id)fp48 alignment:(int)fp52;

@end

