/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GUEmptyViewController : _ABAddressBookAddRecord
{
    id <GUEmptyViewControllerDelegate> delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;

@end

