/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GUMessageMarkingProtocol-Protocol.h"

@class NSArray, NSDictionary;

@interface GUMessageCaveat : _ABAddressBookAddRecord <GUMessageMarkingProtocol>
{
    NSDictionary *options;
    NSArray *caveatsMarkingsCache;
}

+ (id)instance;
- (void)setCaveatsMarkingsCache:(id)fp8;
- (id)caveatsMarkingsCache;
- (void)setOptions:(id)fp8;
- (id)options;
- (void)dealloc;
- (id)messageMarkingNames;
- (id)markingTitle;
- (BOOL)isEnabled;
- (int)defaultMessageMarking;
- (id)bottomBody:(int)fp8;
- (id)topBody:(int)fp8;
- (id)subject:(int)fp8;
- (id)select:(int)fp8;
- (BOOL)markingValid:(int)fp8;
- (int)numberOfMarkings;
- (int)noneMarking;
- (BOOL)isNoneMarking:(int)fp8;
- (BOOL)areMarkingsProvidedFromGMC;
- (id)allocWithZone:(struct _NSZone *)fp8;
- (id)init;
- (void)optionsUpdated:(id)fp8;
- (void)caveatsUpdated:(id)fp8;

@end

