/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GUMessageMarkingProtocol-Protocol.h"

@class NSArray, NSDictionary;

@interface GUMessageClassification : _ABAddressBookAddRecord <GUMessageMarkingProtocol>
{
    NSArray *classificationMarkingsCache;
    NSDictionary *options;
}

+ (id)instance;
- (void)setOptions:(id)fp8;
- (id)options;
- (void)setClassificationMarkingsCache:(id)fp8;
- (id)classificationMarkingsCache;
- (void)dealloc;
- (id)markingTitle;
- (id)messageMarkingNames;
- (BOOL)doesPolicyExist;
- (BOOL)isEnabled;
- (BOOL)isPreferencesMenuForClassificationsEnabled;
- (void)saveDefaultMarking:(int)fp8;
- (int)defaultMessageMarking;
- (id)oldTypeClassificationName:(int)fp8;
- (id)bottomBody:(int)fp8;
- (id)topBody:(int)fp8;
- (id)subject:(int)fp8;
- (id)select:(int)fp8;
- (BOOL)markingValid:(int)fp8;
- (int)numberOfMarkings;
- (BOOL)areMarkingsProvidedFromGMC;
- (id)allocWithZone:(struct _NSZone *)fp8;
- (id)init;
- (void)optionsUpdated:(id)fp8;
- (void)classificationsUpdated:(id)fp8;
- (int)noneMarking;
- (BOOL)isNoneMarking:(int)fp8;

@end

