/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTPopoverView.h"

@interface GUPopoverView : GTPopoverView
{
}

+ (id)showPopoverAtPoint:(struct CGPoint)fp8 inView:(id)fp16 withContentView:(id)fp20 withSelectedIndex:(int)fp24 delegate:(id)fp28;
+ (id)showPopoverAtPoint:(struct CGPoint)fp8 inView:(id)fp16 withViewArray:(id)fp20 withSelectedIndex:(int)fp24 delegate:(id)fp28;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

