/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "UIWebViewDelegate-Protocol.h"

@class NSString, UIFont, UIScrollView, UIWebView;

@interface GUSubjectView : _ABAddressBookAddRecord <UIWebViewDelegate>
{
    UIWebView *_webView;
    UIScrollView *_scrollView;
    NSString *_text;
    NSString *_when;
    NSString *_where;
    UIFont *_subjectFont;
    UIFont *_detailFont;
    BOOL _textIsRTL;
    BOOL _whereIsRTL;
    BOOL _shouldLayoutWebView;
    NSString *_formattedText;
    NSString *_formattedWhereText;
}

- (void)setFormattedWhereText:(id)fp8;
- (id)formattedWhereText;
- (void)setFormattedText:(id)fp8;
- (id)formattedText;
- (id)detailFont;
- (id)subjectFont;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)setContentInset:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)contentInset;
- (void)setWhere:(id)fp8;
- (void)setWhen:(id)fp8;
- (void)setText:(id)fp8;
- (void)setDetailFont:(id)fp8;
- (void)setSubjectFont:(id)fp8;
- (void)sizeToFit;
- (void)layoutSubviews;
- (void)setWebViewNeedsLayout;
- (void)refreshText;
- (id)where;
- (id)when;
- (id)text;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

