/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString, UILabel;

@interface GUTextField : _ABAddressBookAddRecord
{
    UILabel *_customPlaceholderLabel;
    NSString *_customPlaceholder;
}

- (void)setCustomPlaceholder:(id)fp8;
- (id)customPlaceholder;
- (void)textDidChange:(id)fp8;
- (void)setText:(id)fp8;
- (void)setPlaceholder:(id)fp8;
- (id)placeholder;
- (id)placeholderColor;
- (void)setPlaceholderColor:(id)fp8;
- (void)createPlaceholderLabel;
- (void)dealloc;

@end

