/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GUWidgetBuilder : _ABAddressBookAddRecord
{
}

+ (id)bubbleButtonWithText:(id)fp8 withArrow:(BOOL)fp12 withFont:(id)fp16 withAvailability:(int)fp20;
+ (id)bubbleButtonWithText:(id)fp8 withAvailability:(int)fp12;
+ (id)bubbleButtonWithText:(id)fp8 withArrow:(BOOL)fp12;
+ (id)bubbleButtonWithText:(id)fp8;

@end

