/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface GxOpRequestConnect : _ABAddressBookAddRecord
{
    BOOL executing;
    BOOL finished;
    BOOL waitingfordata;
}

+ (void)releaseReqConnObj;
+ (void)beginRequestConnect:(_Bool)fp8;
- (void)_handleNetworkEvent:(unsigned long)fp8 _ReadStreamRef:(struct __CFReadStream *)fp12;
- (void)reqConnThread;
- (void)reqConnThreadMain;
- (void)completeOperation;
- (void)dealloc;
- (void)start;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isConcurrent;
- (id)init;

@end

