/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class CGHTTPCallback;

@interface IdCallbackWrapper : _ABAddressBookAddRecord
{
    unsigned long tokenId;
    CGHTTPCallback *callback;
}

- (void)setCallback:(id)fp8;
- (id)callback;
- (void)setTokenId:(unsigned long)fp8;
- (unsigned long)tokenId;

@end

