/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSArray, THCalendarInfo;

@interface KLCalendarModel : _ABAddressBookAddRecord
{
    struct __CFCalendar *_cal;
    THCalendarInfo *_calendarInfo;
    BOOL considerTime;
    int hourToScroll;
    NSArray *_dayNames;
    BOOL allOccurences;
}

+ (id)model;
- (void)setAllOccurences:(BOOL)fp8;
- (BOOL)allOccurences;
- (void)setHourToScroll:(int)fp8;
- (int)hourToScroll;
- (void)setConsiderTime:(BOOL)fp8;
- (BOOL)considerTime;
- (void)set_calendarInfo:(id)fp8;
- (id)_calendarInfo;
- (void)onSystemTimeZoneDidChange;
- (BOOL)isDomino;
- (int)allDayEventEndHour;
- (int)allDayEventStartHour;
- (id)findAppointmentOfId:(unsigned long)fp8 andInstance:(long)fp12;
- (void)setListener:(id)fp8 withSelector:(SEL)fp12;
- (void)respondToMeetingRequestFromCalendar:(id)fp8 response:(int)fp12 notes:(id)fp16 sendEmail:(BOOL)fp20 forAllOccurrences:(BOOL)fp24;
- (void)deleteAppointment:(id)fp8 applyAll:(BOOL)fp12;
- (void)modifyAppointment:(id)fp8 applyAll:(BOOL)fp12;
- (void)addAppointment:(id)fp8;
- (id)findAppointmentsForPeriod:(id)fp8 numberOfDays:(int)fp12;
- (id)findAppointmentsForDay:(id)fp8;
- (void)dealloc;
- (id)daysInFirstWeekOfFollowingMonth;
- (id)daysInSelectedMonth;
- (id)daysInFinalWeekOfPreviousMonth;
- (id)dayNameAbbreviationForDayOfWeek:(unsigned int)fp8;
- (int)selectedMonthNumberOfWeeks;
- (int)selectedYear;
- (id)selectedMonthName;
- (int)selectedMonth;
- (id)selectedDayName;
- (int)selectedDay;
- (id)getDate;
- (void)setDate:(id)fp8;
- (void)incrementDay;
- (void)decrementDay;
- (void)incrementMonth;
- (void)decrementMonth;
- (id)init;

@end

