/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSDate;

@interface KLCalendarUiData : _ABAddressBookAddRecord
{
    NSDate *savedDate;
}

+ (id)instance;
- (void)setSavedDate:(id)fp8;
- (id)savedDate;
- (void)dealloc;
- (void)saveCurrentDate;

@end

