/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSArray;

@interface KLCalendarDayViewCellView : _ABAddressBookAddRecord
{
    int hour;
    BOOL isToday;
    BOOL highlighted;
    NSArray *hourStrings;
}

- (void)setHourStrings:(id)fp8;
- (id)hourStrings;
- (void)setIsToday:(BOOL)fp8;
- (BOOL)isToday;
- (void)setHour:(int)fp8;
- (int)hour;
- (BOOL)isHighlighted;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

