/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "GUSwipeTrackerDelegate-Protocol.h"

@class GUSwipeTracker, KLGenericViewController, NSDate;

@interface KLDayView : _ABAddressBookAddRecord <GUSwipeTrackerDelegate>
{
    GUSwipeTracker *swipeTracker;
    BOOL _shouldTrackSwipe;
    KLGenericViewController *controller;
    NSDate *lastTouchDateforSwipe;
}

- (void)setLastTouchDateforSwipe:(id)fp8;
- (id)lastTouchDateforSwipe;
- (void)dealloc;
- (void)wasSwipedRightInView:(id)fp8;
- (void)wasSwipedLeftInView:(id)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesBeganTimerExpired:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 controller:(id)fp24;

@end

