/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class GUCalendarDateControl, KLCalendarView, KLViewMgrBase;

@interface KLGenericViewController : _ABAddressBookAddRecord
{
    KLCalendarView *headerView;
    KLViewMgrBase *viewMgr;
    GUCalendarDateControl *_calendarDateControl;
    BOOL resetUi;
    BOOL isOnShown;
    BOOL _showCalendarDateControl;
}

- (void)setShowCalendarDateControl:(BOOL)fp8;
- (BOOL)showCalendarDateControl;
- (void)setCalendarDateControl:(id)fp8;
- (id)calendarDateControl;
- (void)setViewMgr:(id)fp8;
- (id)viewMgr;
- (void)setHeaderView:(id)fp8;
- (id)headerView;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (id)titleString;
- (BOOL)tabBarController:(id)fp8 shouldSelectViewController:(id)fp12;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)motionEnded:(int)fp8 withEvent:(id)fp12;
- (BOOL)canBecomeFirstResponder;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (id)init;

@end

