/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class AppointmentWrapperCache, CALayer, NSMutableArray, UIViewController;

@interface KLTimeFrame : _ABAddressBookAddRecord
{
    AppointmentWrapperCache *appointments;
    NSMutableArray *appointmentRects;
    CALayer *layer;
    int layerIndex;
    double duration;
    UIViewController *_controller;
    float dayViewWidth;
}

- (float)dayViewWidth;
- (void)setController:(id)fp8;
- (id)controller;
- (void)setAppointmentRects:(id)fp8;
- (id)appointmentRects;
- (void)setAppointments:(id)fp8;
- (id)appointments;
- (void)setLayerIndex:(int)fp8;
- (int)layerIndex;
- (void)setLayer:(id)fp8;
- (id)layer;
- (void)deselectAllAppointments;
- (void)highlightAppointmentRect:(id)fp8 highlight:(BOOL)fp12;
- (void)highlightAppointment:(id)fp8 highlight:(BOOL)fp12;
- (id)appointmentRectForAppointment:(id)fp8;
- (id)appointmentAtPoint:(struct CGPoint)fp8;
- (void)drawLayer:(id)fp8 inContext:(struct CGContext *)fp12;
- (void)dealloc;
- (void)setDayViewWidth:(float)fp8;
- (void)addAppointment:(id)fp8;
- (BOOL)fitsInTimeFrame:(id)fp8;
- (id)initWithDuration:(double)fp8 withController:(id)fp16;

@end

