/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "KLAppointmentAddModCell.h"

@class UILabel;

@interface KLTitleCell : KLAppointmentAddModCell
{
    UILabel *_titleLabel;
}

- (void)setupConstraints;
- (void)setupTitleLabelDefaultApperance:(id)fp8;
- (void)setupTitleLabelApperance:(id)fp8;
- (void)setTitle:(id)fp8;
- (void)dealloc;
- (void)setupView;
- (void)setupFonts;

@end

