/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "KLTitleAndValueCell.h"

@class UILabel;

@interface KLTitleAndValue2RowsCell : KLTitleAndValueCell
{
    UILabel *_titleLabel2;
    UILabel *_valueLabel2;
}

- (float)defaultBottomMargin;
- (float)defaultTopMargin;
- (void)setupConstraints;
- (void)setValue2:(id)fp8;
- (void)setTitle2:(id)fp8;
- (void)dealloc;
- (void)setupFonts;
- (void)setupView;

@end

