/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "AppointmentModificationHandler-Protocol.h"

@class DayPicker, KLCalendarModel, KLCalendarView, KLGenericViewController;

@interface KLViewMgrBase : _ABAddressBookAddRecord <AppointmentModificationHandler>
{
    KLCalendarModel *model;
    KLCalendarView *view;
    KLGenericViewController *controller;
    struct CGRect originalSuperviewFrame;
    unsigned long lastRefreshTime;
    BOOL timerCreatedToProcessRefresh;
    BOOL viewWasUnloaded;
    BOOL isMainViewMgr;
    DayPicker *_dayPicker;
}

- (void)setViewWasUnloaded:(BOOL)fp8;
- (BOOL)viewWasUnloaded;
- (void)setIsMainViewMgr:(BOOL)fp8;
- (BOOL)isMainViewMgr;
- (void)setView:(id)fp8;
- (id)view;
- (void)setDayPicker:(id)fp8;
- (id)dayPicker;
- (id).cxx_construct;
- (void)dealloc;
- (void)dateUpdatedTo:(id)fp8;
- (id)currentDate;
- (void)setCurrentDate:(id)fp8;
- (void)handleDateChange;
- (void)ensurePlusButtonPresentInNavBar;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)drawInNavView:(struct CGRect)fp8;
- (void)PickAPeriod;
- (void)showFollowingPeriod;
- (void)showPreviousPeriod;
- (void)refreshViewWithPushDirection:(id)fp8;
- (void)refreshView;
- (BOOL)isDisplayed:(id)fp8;
- (void)doNotifReceived:(id)fp8;
- (float)topPositionForModelView;
- (void)refreshUI;
- (void)timeZoneDidChange:(id)fp8;
- (void)removeUI;
- (void)addUI;
- (id)initWithModel:(id)fp8 view:(id)fp12 controller:(id)fp16;

@end

