/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "CLLocationManagerDelegate-Protocol.h"
#import "MKMapViewDelegate-Protocol.h"
#import "MKReverseGeocoderDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CLLocation, CLLocationManager, MKMapView, MKReverseGeocoder, NSString, NSTimer, UIAlertView, UITableView;

@interface MapDirectionsController : _ABAddressBookAddRecord <UITableViewDelegate, UITableViewDataSource, MKMapViewDelegate, UIActionSheetDelegate, CLLocationManagerDelegate, MKReverseGeocoderDelegate>
{
    NSString *address;
    CDAnonymousStruct2 location;
    UITableView *myTableView;
    MKMapView *myMapView;
    BOOL directionTo;
    NSTimer *currentLocationTimer;
    CLLocationManager *_locationManager;
    CLLocation *_currentLocation;
    NSTimer *currentAddressTimer;
    MKReverseGeocoder *_reverseGeocoder;
    NSString *_currentAddress;
    UIAlertView *_retrievingCurrentLocationAlert;
}

- (void)setRetrievingCurrentLocationAlert:(id)fp8;
- (id)retrievingCurrentLocationAlert;
- (void)setCurrentAddress:(id)fp8;
- (id)currentAddress;
- (void)setReverseGeocoder:(id)fp8;
- (id)reverseGeocoder;
- (void)setCurrentLocation:(id)fp8;
- (id)currentLocation;
- (void)setLocationManager:(id)fp8;
- (id)locationManager;
- (void)setDirectionTo:(BOOL)fp8;
- (BOOL)directionTo;
- (void)setMyMapView:(id)fp8;
- (id)myMapView;
- (void)setMyTableView:(id)fp8;
- (id)myTableView;
- (void)setLocation:(CDAnonymousStruct2)fp8;
- (CDAnonymousStruct2)location;
- (void)setAddress:(id)fp8;
- (id)address;
- (id).cxx_construct;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)reverseGeocoder:(id)fp8 didFindPlacemark:(id)fp12;
- (void)reverseGeocoder:(id)fp8 didFailWithError:(id)fp12;
- (void)locationManager:(id)fp8 didFailWithError:(id)fp12;
- (void)locationManager:(id)fp8 didUpdateToLocation:(id)fp12 fromLocation:(id)fp16;
- (void)prepareDirection:(id)fp8;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (BOOL)launchDirection:(id)fp8 to:(id)fp12;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)onCurrentAddressTimerElapsed:(id)fp8;
- (void)onCurrentAddressComplete;
- (void)onCurrentLocationTimerElapsed:(id)fp8;
- (void)onCurrentLocationComplete;
- (void)doConfirmLeaveApplication;
- (void)loadView;
- (void)dealloc;
- (void)stopAll;
- (void)stopReverseGeocoder;
- (void)startReverseGeocoder;
- (void)stopLocationManager;
- (void)startLocationManager;
- (id)init;

@end

