/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString;

@interface OrderedTab : _ABAddressBookAddRecord
{
    BOOL isVisible;
    NSString *tabName;
}

- (void)setIsVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (void)setTabName:(id)fp8;
- (id)tabName;
- (void)dealloc;

@end

