/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol OTAClientAuthenticatorDelegate
- (void)showDownloadIPhoneConfigUI:(id)fp8;
- (void)authenticator:(id)fp8 showOtaError:(id)fp12;
- (void)authenticator:(id)fp8 didUpdateStatus:(int)fp12 withMessage:(id)fp16 majorProgressLocation:(id)fp20 minorProgressLocation:(id)fp24;
- (void)authenticator:(id)fp8 didFailWithError:(id)fp12;
- (void)authenticator:(id)fp8 didLoadResult:(id)fp12;
@end

