/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface PeopleWrapper : _ABAddressBookAddRecord <NSCopying>
{
    NSString *displayName;
    NSString *email;
    int read;
    int myself;
    int attendence;
    int response;
    int availability;
    int goodContactId;
    BOOL isDistributionList;
}

+ (id)peopleWrapperWithEmail:(id)fp8;
- (void)setIsDistributionList:(BOOL)fp8;
- (BOOL)isDistributionList;
- (void)setGoodContactId:(int)fp8;
- (int)goodContactId;
- (void)setAvailability:(int)fp8;
- (int)availability;
- (void)setResponse:(int)fp8;
- (int)response;
- (void)setAttendence:(int)fp8;
- (int)attendence;
- (void)setMyself:(int)fp8;
- (int)myself;
- (void)setRead:(int)fp8;
- (int)read;
- (void)setEmail:(id)fp8;
- (id)email;
- (void)setDisplayName:(id)fp8;
- (id)displayName;
- (int)compareDisplayName:(id)fp8;
- (void)dump;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)init;

@end

