/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface PMHeaderInSection : _ABAddressBookAddRecord
{
}

+ (float)labelHeight:(id)fp8 font:(id)fp12 andWidth:(float)fp16;
+ (id)headerWithLabelOS7:(id)fp8 andWidth:(float)fp12;
+ (id)headerWithLabel:(id)fp8 andWidth:(float)fp12;
+ (id)defaultFont;
+ (float)lastSectionHeight;
+ (id)headerWithLabelFactory:(id)fp8 andWidth:(float)fp12;
+ (float)heightWithLabel;
+ (float)defaultHeight;

@end

