/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "SecuritySelectionListViewProtocol-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class SmimeModuleAccessor, UIPopoverController;

@interface PreferencesViewSecurityManager : _ABAddressBookAddRecord <SecuritySelectionListViewProtocol, UIPopoverControllerDelegate>
{
    SmimeModuleAccessor *smimeModuleAccessor;
    UIPopoverController *_popover;
}

- (void)setSmimeModuleAccessor:(id)fp8;
- (id)smimeModuleAccessor;
- (void)presentBAIPairingView:(id)fp8;
- (BOOL)popoverControllerShouldDismissPopover:(id)fp8;
- (unsigned int)PurgeCertificateCache:(const struct GxUTF8String *)fp8;
- (void)registerForNotifications;
- (void)showPinUIAndvalidateCACPin;
- (void)displayBAILoginScreen_bkgThread;
- (void)displayBAILoginScreen_bkgThreadMain;
- (void)showCACConnectionErrorView;
- (void)showInvalidCACPinErrorView;
- (void)showSecurityMainView:(id)fp8;
- (int)getTokenPreference;
- (void)setTokenPreference:(int)fp8;
- (int)shouldShowInstallCertificatesOption;
- (void)installCertificatesSelected:(id)fp8;
- (void)SetMessageClassificationOption:(BOOL)fp8;
- (BOOL)GetMessageClassificationOption;
- (_Bool)GetShowSecurityIconOption;
- (void)SetShowSecurityIconOption:(_Bool)fp8;
- (int)GetMessageDefaultClassification;
- (void)cancelAction;
- (void)saveAction:(int)fp8;
- (void)showDefaultSecurityPickerForParent:(id)fp8 inView:(id)fp12;
- (void)showDefaultSecurityPickerForParent:(id)fp8;
- (void)dealloc;
- (BOOL)isSMIMEEnabled;

@end

