/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class PriorityTableViewCell, UIPickerView;

@interface PriorityPickerTableViewCell : _ABAddressBookAddRecord
{
    UIPickerView *_pickerView;
    PriorityTableViewCell *_assignedPriorityCell;
}

- (void)setAssignedPriorityCell:(id)fp8;
- (id)assignedPriorityCell;
- (void)setPickerView:(id)fp8;
- (id)pickerView;
- (int)selectedRow;
- (void)selectRow:(int)fp8;
- (void)dealloc;

@end

