/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "IPResolverCallback-Protocol.h"

@interface ProxyManagerIPResolverCallbackImpl : _ABAddressBookAddRecord <IPResolverCallback>
{
    struct SBProxyManager *m_proxyMgr;
}

- (void)onIPAddressResolved:(_Bool)fp8 HostName:(id)fp12 IPAddressList:(id)fp16;
- (id)initWithProxyManager:(struct SBProxyManager *)fp8;

@end

