/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSMutableDictionary;

@interface RecipientMap : _ABAddressBookAddRecord
{
    NSMutableDictionary *_recipientDictionary;
    struct UIAListener *_emailDBListener;
    id <RecipientMapDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)demCertVerified:(id)fp8;
- (void)unregisterFromSystemNotification;
- (void)registerToSystemNotification;
- (void)removeRecipientsForGoodId:(unsigned long)fp8;
- (id)recipientsForGoodId:(unsigned long)fp8;
- (void)removeRecipientsForGoodIdImpl:(id)fp8;
- (void)addRecipients:(id)fp8 forGoodId:(id)fp12;
- (void)dealloc;
- (id)init;

@end

