/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface Reminder : _ABAddressBookAddRecord
{
    struct CDateTimeBits time;
    unsigned long goodId;
    long instance;
    BOOL fired;
}

- (void)setFired:(BOOL)fp8;
- (BOOL)fired;
- (void)setInstance:(long)fp8;
- (long)instance;
- (void)setGoodId:(unsigned long)fp8;
- (unsigned long)goodId;
- (void)setTime:(struct CDateTimeBits)fp8;
- (struct CDateTimeBits)time;
- (id).cxx_construct;
- (id)initWithStr:(id)fp8 andGoodId:(id)fp12 andInstance:(id)fp16 andFired:(id)fp20;
- (id)initWithTime:(struct CDateTimeBits)fp8 andGoodId:(unsigned long)fp12 andInstance:(long)fp16;

@end

