/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class UIColor;

@interface RoundedRect : _ABAddressBookAddRecord
{
    UIColor *_foregroundColor;
}

- (void)setForegroundColor:(id)fp8;
- (id)foregroundColor;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;

@end

