/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RowGeneralSecurityView.h"

@interface RowDominoSecurityView : RowGeneralSecurityView
{
    int _status;
}

- (void)dealloc;
- (void)showIn:(id)fp8 withStatus:(int)fp12;
- (int)status;
- (void)setStatus:(int)fp8;
- (void)setFontAndFrameToLabel;
- (void)setContentSizeCategory:(id)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGRect)singleLineFrame;
- (struct CGRect)multilineFrame;
- (float)messageLabelWidth;

@end

