/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RowView.h"

@class UIImageView, UILabel;

@interface RowGeneralSecurityView : RowView
{
    UILabel *_title;
    UIImageView *_securityIcon;
    float _verticalMargin;
    float _horizontalMargin;
}

- (void)setContentSizeCategory:(id)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8 imageName:(id)fp24;
- (void)dealloc;

@end

