/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "RowView.h"

@class GUAttachmentButton, GUSubjectView, NSString, UIButton, UIImage, UILabel, UIView;

@interface RowSubjectView : RowView
{
    GUSubjectView *_subjectTextView;
    GUAttachmentButton *_attachmentButton;
    UIButton *_showInCalendarButton;
    UIImage *_showInCalendarButtonPortraitImage;
    UIImage *_showInCalendarButtonLandscapeImage;
    UIButton *_calendarAcceptButton;
    UIButton *_calendarTentativeButton;
    UIButton *_calendarDeclineButton;
    UIView *_buttonsContainer;
    UILabel *_responseMessageTextLabel;
    UIView *_bannerForDelegate;
    UILabel *_LabelForDelegageBanner;
    BOOL _isCalendarEmail;
    BOOL _isDelegatedCalendarEmail;
    struct CGSize _layoutedSize;
    float _verticalMargin;
    float _horizontalMargin;
    int _interfaceOrientation;
    int _conflicts;
    BOOL _isShowInCalendarButtonVisible;
    BOOL _areResponseButtonsVisible;
    BOOL _isResponseMessageVisible;
    NSString *_responseMessageText;
    NSString *_subject;
    unsigned int _attachmentsCount;
    NSString *_receivedDate;
    NSString *textInLabelForDelegageBanner;
}

- (int)interfaceOrientation;
- (void)setReceivedDate:(id)fp8;
- (id)receivedDate;
- (void)setAttachmentsCount:(unsigned int)fp8;
- (unsigned int)attachmentsCount;
- (void)setSubject:(id)fp8;
- (id)subject;
- (void)setTextInLabelForDelegageBanner:(id)fp8;
- (id)textInLabelForDelegageBanner;
- (void)setResponseMessageText:(id)fp8;
- (id)responseMessageText;
- (void)setIsResponseMessageVisible:(BOOL)fp8;
- (BOOL)isResponseMessageVisible;
- (void)setAreResponseButtonsVisible:(BOOL)fp8;
- (BOOL)areResponseButtonsVisible;
- (void)setIsShowInCalendarButtonVisible:(BOOL)fp8;
- (BOOL)isShowInCalendarButtonVisible;
- (void)setConflicts:(int)fp8;
- (int)conflicts;
- (id)calendarDeclineButton;
- (id)calendarTentativeButton;
- (id)calendarAcceptButton;
- (id)LabelForDelegageBanner;
- (id)bannerForDelegate;
- (id)showInCalendarButton;
- (id)attachmentButton;
- (id).cxx_construct;
- (void)layoutSubviews_old;
- (void)setEmail_old:(id)fp8;
- (void)createCalendarResponseButtons;
- (void)createShowInCalendarButton:(int)fp8;
- (void)createCalendarButtonsContainer:(int)fp8;
- (void)setFrameForBanner;
- (float)setUpAttachmentView;
- (id)newResponseMessageTextLabelForText:(id)fp8;
- (id)newBannerForDelegateWith:(struct CGRect)fp8;
- (id)newCalendarButton;
- (void)updateAttachmentView;
- (void)updateSubjectTextView;
- (void)layoutSubviews;
- (void)setEmail:(id)fp8;
- (void)setInterfaceOrientation:(int)fp8;
- (void)recalculateInsets;
- (void)setContentSizeCategory:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

