/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSDictionary, NSURL;

@interface SBActionSheet : _ABAddressBookAddRecord
{
    NSURL *url;
    NSDictionary *params;
}

- (void)setParams:(id)fp8;
- (id)params;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;
- (void)addApplicationsButtonsForServiceWithName:(id)fp8;
- (void)dealloc;

@end

