/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBBookmarkBaseVC.h"

@class UIBarButtonItem;

@interface SBBookmarkVC_iPhone : SBBookmarkBaseVC
{
    UIBarButtonItem *addBookmarkButtionItem;
}

- (void)setAddBookmarkButtionItem:(id)fp8;
- (id)addBookmarkButtionItem;
- (void)dealloc;
- (void)goToFolderForBookmark:(id)fp8;
- (void)showEditVCForBookmark:(id)fp8 atIndex:(unsigned int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)init;
- (void)onEdit:(id)fp8;
- (void)setupToolbarAndButtonsVisibleState;
- (void)onAddBookmark;

@end

