/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSMutableArray;

@interface SBBrowserSectionManager : _ABAddressBookAddRecord
{
    NSMutableArray *_rowItems;
}

- (void)set_rowItems:(id)fp8;
- (id)_rowItems;
- (void)updateRowItems;
- (void)initRowItems;
- (id)rowItemAtIndex:(unsigned int)fp8;
- (id)rowItems;
- (unsigned int)numberOfRows;
- (void)dealloc;
- (id)init;

@end

