/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface SBCertificateHelper : _ABAddressBookAddRecord
{
}

+ (id)gxTimeToNsDate:(struct GxTime *)fp8;
+ (id)certificateInfoWithCertificateData:(const char *)fp8 len:(int)fp12 detailed:(BOOL)fp16;
+ (id)certFieldValueWithCertData:(const char *)fp8 len:(int)fp12 oid:(const char *)fp16;
+ (id)certDateWithCertData:(const char *)fp8 len:(int)fp12 start:(BOOL)fp16;

@end

