/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString;

@interface SBCommandAction : _ABAddressBookAddRecord
{
    NSString *_name;
    id _target;
    SEL _action;
}

+ (id)comandWithName:(id)fp8 forTarget:(id)fp12 withAction:(SEL)fp16;
- (SEL)action;
- (id)target;
- (id)name;
- (BOOL)execute:(id)fp8 completion:(id)fp(null);
- (void)dealloc;
- (id)initWithName:(id)fp8 forTarget:(id)fp12 withAction:(SEL)fp16;

@end

