/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface SBJavascriptContainer : _ABAddressBookAddRecord
{
}

+ (id)getEscapedSettingsForDynamicGlobalVariablesInScript;
+ (id)getEscapedJSOpenerOverrideScript;
+ (id)getEscapedOverrideAnchorTagScript;
+ (id)getEscapediFrameSwitchScript;
+ (id)getEscapedJSObjCBridgeScript;
+ (id)getEscapedModalDialogStyleCSS;
+ (id)getEscapediFramePopupOverrideScript;
+ (id)getEscapedModalDialogiFrameScript;
+ (id)getEscapedJSInjectScript;
+ (id)getUserAgentScript;
+ (id)getJSToolsScript;
+ (id)getJSIsDefaultContextOSMenuDisabledScript;
+ (id)getJSOpenerOverrideScript;
+ (id)getJSOnClickOverrideScript;
+ (id)getJSDefaultOpenURLScript;
+ (id)getJSInjectDefaultScript;
+ (id)getJSInjectPopupScript:(BOOL)fp8;
+ (id)getOverrideAnchorTagScript;
+ (id)getiFrameSwitchScript;
+ (id)getJSObjCBridgeScript;
+ (id)getBaseJSInjectScript;
+ (id)getModalDialogStyleCSS;
+ (id)getiFramePopupOverrideScript;
+ (id)getModalDialogiFrameScript;
+ (id)getSettingsForDynamicGlobalVariablesInScript;

@end

