/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class NSString, NSURL;

@interface SBParentPageState : _ABAddressBookAddRecord
{
    NSURL *_pageURL;
    NSString *_pageTitle;
}

- (void)setPageTitle:(id)fp8;
- (id)pageTitle;
- (void)setPageURL:(id)fp8;
- (id)pageURL;
- (void)dealloc;

@end

