/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBResourceDataHandler.h"

@interface SBSaveAsResourceDataHandler : SBResourceDataHandler
{
    BOOL _sendOnDataCompleteNotification;
}

+ (BOOL)canHandleUrlStr:(id)fp8 mimeType:(id)fp12;
- (void)receivedResourceLastPartForUrl:(id)fp8 resDesc:(struct SBResourceDesc *)fp12 token:(struct SBResourceRequesterToken *)fp16;
- (id)initWithContext:(id)fp8 onDataCompleteNotification:(BOOL)fp12;

@end

