/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class Delegate, SmimeAlertView, SmimeAlertViewsFactory, SmimeModuleAccessor;

@interface SecurityInfoViewer : _ABAddressBookAddRecord
{
    SmimeAlertViewsFactory *alertViewsFactory;
    SmimeAlertView *smimeAlertView;
    Delegate *securityHandlerCallback;
    SmimeModuleAccessor *smimeModuleAccessor;
}

- (void)setSmimeModuleAccessor:(id)fp8;
- (id)smimeModuleAccessor;
- (void)setSecurityHandlerCallback:(id)fp8;
- (id)securityHandlerCallback;
- (void)setAlertViewsFactory:(id)fp8;
- (id)alertViewsFactory;
- (BOOL)WeHaveAllAttachmentsInCache:(struct AnEmail *)fp8;
- (id)getCertificateErrStringForCertStatus:(int)fp8 forName:(id)fp12;
- (id)prepareCertificateDetails:(struct AnEmail *)fp8 format:(id)fp12;
- (id)prepareEncryptInformation:(struct ASMIMERecord *)fp8 format:(id)fp12;
- (id)prepareSignInformation:(struct ASMIMERecord *)fp8 format:(id)fp12;
- (id)getMsgWithoutInformation;
- (void)getMessageForStatusNotVerified:(int)fp8;
- (void)getMessageForCertificateFailure:(int)fp8;
- (struct ASMIMEDatabase *)getSmimeDatabase;
- (void)showSenderCertificateMissingAlertWithCallBack:(id)fp8;
- (void)showInfoAboutFailure:(struct AnEmail *)fp8;
- (void)showInfoAboutProgress:(struct AnEmail *)fp8;
- (void)showInfoAboutSuccess:(struct AnEmail *)fp8;
- (void)dealloc;
- (void)showSmimeEncodingAlertView:(int)fp8;
- (void)showCertificateLookupFailerAlertView:(int)fp8 forEmailAddress:(id)fp12;
- (void)showCACConnectingInformativeAlertView;
- (void)showCertificateLookupAlertView;
- (void)dismissCurrentSmimeAlertView;
- (void)showCertificateDetails:(struct AnEmail *)fp8;
- (void)showInfo:(struct AnEmail *)fp8;
- (BOOL)updateMsgForSmimeSecStatus:(struct AnEmail *)fp8 securityCell:(id)fp12;
- (id)init;

@end

