/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SmimeSecStateHandler.h"

@interface SmimeSecStateOutBoxMailHandler : SmimeSecStateHandler
{
}

- (void)updateInfoForDisabledSmime;
- (void)setUpForEmail:(struct AnEmail *)fp8 hasValidPassword:(_Bool)fp12;

@end

