/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@class RowSMIMESecurityView, SecurityInfoViewer, SmimeAlertViewsFactory, SmimeModuleAccessor;

@interface SmimeSecStateHandler : _ABAddressBookAddRecord
{
    RowSMIMESecurityView *securityCell;
    SmimeAlertViewsFactory *alertViewsFactory;
    struct AnEmail *emailRecord;
    SecurityInfoViewer *infoViewer;
    SmimeModuleAccessor *smimeModuleAccessor;
    id <SmimeEmailDisplayProtocol> emailViewHandle;
    BOOL _decryptButtonClicked;
    unsigned short _currentMsgId;
    int _currentTokenType;
    int _replyForwardEmailOption;
    int _previousSecStatus;
}

- (void)setEmailViewHandle:(id)fp8;
- (id)emailViewHandle;
- (void)setSmimeModuleAccessor:(id)fp8;
- (id)smimeModuleAccessor;
- (void)setInfoViewer:(id)fp8;
- (id)infoViewer;
- (void)setEmailRecord:(struct AnEmail *)fp8;
- (struct AnEmail *)emailRecord;
- (void)setAlertViewsFactory:(id)fp8;
- (id)alertViewsFactory;
- (void)setSecurityCell:(id)fp8;
- (id)securityCell;
- (void)removeEmailRecipientsPriorDownloadingEntireMessage;
- (void)decodeEntireMessage;
- (void)downloadEntireMsgAndComposeEmail:(int)fp8;
- (void)decryptButtonClicked:(BOOL)fp8;
- (BOOL)updateSecStatusInEmailRecord:(int)fp8;
- (void)updateEmailView:(id)fp8;
- (void)updateStatusForSmimeActionResult:(id)fp8;
- (void)updateProgressBar:(id)fp8;
- (void)stopProgressView;
- (void)startProgressView;
- (void)securityInfoButtonClicked:(id)fp8;
- (void)decodeMessage:(struct AnEmail *)fp8;
- (void)updateInfoForDisabledSmime;
- (void)showSecurityInfoForEmail:(struct AnEmail *)fp8;
- (void)updateForEmail:(struct AnEmail *)fp8 hasValidPassword:(_Bool)fp12;
- (void)setUpForEmail:(struct AnEmail *)fp8 hasValidPassword:(_Bool)fp12;
- (void)dealloc;

@end

