/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SmimeAlertView.h"

@interface SmimeSoftTokenImportHowToAlertView : SmimeAlertView
{
    BOOL multipleSoftTokensDownloaded;
    BOOL exportSoftTokenPolicyEnabled;
}

- (void)setExportSoftTokenPolicyEnabled:(BOOL)fp8;
- (BOOL)exportSoftTokenPolicyEnabled;
- (void)setMultipleSoftTokensDownloaded:(BOOL)fp8;
- (BOOL)multipleSoftTokensDownloaded;
- (void)show;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)refreshViewText;
- (id)init;

@end

