/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "UIAlertViewDelegate-Protocol.h"

@class Delegate;

@interface SmimeAlertView : _ABAddressBookAddRecord <UIAlertViewDelegate>
{
    Delegate *callback;
    int tokenUsage;
    BOOL alertViewPresented;
}

- (void)setAlertViewPresented:(BOOL)fp8;
- (BOOL)alertViewPresented;
- (void)setTokenUsage:(int)fp8;
- (int)tokenUsage;
- (void)setCallback:(id)fp8;
- (id)callback;
- (void)dismissAlertNow;
- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;
- (void)didPresentAlertView:(id)fp8;
- (void)willPresentAlertView:(id)fp8;
- (void)setTextAlignment:(int)fp8;
- (void)dealloc;

@end

