/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class GMMTask, GUCheckbox, GUTextField, GUTextView, NSDate, UIActionSheet, UIButton, UILabel, UIView;

@interface TaskView : _ABAddressBookAddRecord <UITextViewDelegate, UIActionSheetDelegate, UITextFieldDelegate>
{
    BOOL _isDetailedView;
    int _priority;
    int _priorityUnchanged;
    NSDate *_dueDate;
    NSDate *_reminderDate;
    NSDate *_startDate;
    GMMTask *_task;
    UIActionSheet *_actionSheet;
    id <TaskViewDelegate> delegate;
    UILabel *priorityLabel;
    UILabel *dueDateLabel;
    UILabel *reminderLabel;
    UILabel *startLabel;
    UILabel *noteLabel;
    GUTextField *titleTextView;
    GUTextView *notesTextView;
    UIButton *deleteButton;
    UILabel *dateDueDateLabel;
    UILabel *dateReminderDateLabel;
    UILabel *dateStartDateLabel;
    UIView *dueDateView;
    UIView *reminderView;
    UIView *startDateView;
    UIView *exchangePriorityView;
    UIView *dominoPriorityView;
    UILabel *highPriorityLabel;
    UILabel *lowPriorityLabel;
    UILabel *highLabel;
    UILabel *medLabel;
    UILabel *lowLabel;
    UILabel *noneLabel;
    UIView *editView;
    UIView *backgroundView;
    GUCheckbox *taskCompleteCheckbox;
}

+ (id)taskViewWithNibForiPad;
+ (id)taskViewWithNib;
+ (void)initCommonPropertiesForTaskView:(id)fp8;
- (void)setTaskCompleteCheckbox:(id)fp8;
- (id)taskCompleteCheckbox;
- (void)setActionSheet:(id)fp8;
- (id)actionSheet;
- (void)setBackgroundView:(id)fp8;
- (id)backgroundView;
- (void)setEditView:(id)fp8;
- (id)editView;
- (void)setNoneLabel:(id)fp8;
- (id)noneLabel;
- (void)setLowLabel:(id)fp8;
- (id)lowLabel;
- (void)setMedLabel:(id)fp8;
- (id)medLabel;
- (void)setHighLabel:(id)fp8;
- (id)highLabel;
- (void)setLowPriorityLabel:(id)fp8;
- (id)lowPriorityLabel;
- (void)setHighPriorityLabel:(id)fp8;
- (id)highPriorityLabel;
- (void)setDominoPriorityView:(id)fp8;
- (id)dominoPriorityView;
- (void)setExchangePriorityView:(id)fp8;
- (id)exchangePriorityView;
- (void)setStartDateView:(id)fp8;
- (id)startDateView;
- (void)setReminderView:(id)fp8;
- (id)reminderView;
- (void)setDueDateView:(id)fp8;
- (id)dueDateView;
- (void)setDateStartDateLabel:(id)fp8;
- (id)dateStartDateLabel;
- (void)setDateReminderDateLabel:(id)fp8;
- (id)dateReminderDateLabel;
- (void)setDateDueDateLabel:(id)fp8;
- (id)dateDueDateLabel;
- (void)setDeleteButton:(id)fp8;
- (id)deleteButton;
- (void)setNotesTextView:(id)fp8;
- (id)notesTextView;
- (void)setTitleTextView:(id)fp8;
- (id)titleTextView;
- (void)setNoteLabel:(id)fp8;
- (id)noteLabel;
- (void)setStartLabel:(id)fp8;
- (id)startLabel;
- (void)setReminderLabel:(id)fp8;
- (id)reminderLabel;
- (void)setDueDateLabel:(id)fp8;
- (id)dueDateLabel;
- (void)setPriorityLabel:(id)fp8;
- (id)priorityLabel;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)task;
- (void)dismissActionSheet;
- (void)dealloc;
- (void)handleEditAttempWithTarget:(id)fp8 action:(SEL)fp12;
- (id)tapHandlerWithTarget:(id)fp8 action:(SEL)fp12;
- (void)setNotes:(id)fp8;
- (id)notes;
- (void)refreshStartDateText:(id)fp8;
- (void)setStartDate:(id)fp8;
- (id)startDate;
- (void)refreshReminderDateText:(id)fp8;
- (void)setReminderDate:(id)fp8;
- (id)reminderDate;
- (void)refreshDueDateText:(id)fp8;
- (void)setDueDate:(id)fp8;
- (id)dueDate;
- (void)setPriority:(int)fp8;
- (int)priority;
- (void)setTaskTitle:(id)fp8;
- (id)taskTitle;
- (void)setTask:(id)fp8;
- (void)actionCancel;
- (void)actionDone;
- (void)saveTask;
- (id)createNewDateToNoon:(id)fp8;
- (void)actionDelete;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)actionChangePriority:(id)fp8;
- (void)checkBoxTapped:(id)fp8;
- (void)redrawPriorityMarkers;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (void)textViewDidEndEditing:(id)fp8;
- (BOOL)textViewShouldEndEditing:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)textFieldDidEndEditing:(id)fp8;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (id)initWithTask:(id)fp8;

@end

