/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TaskView.h"

@class NSDate, UIDatePicker, UIScrollView, UIToolbar, UIView;

@interface TaskViewiPhone : TaskView
{
    UIScrollView *_scrollView;
    UIView *_dockView;
    BOOL _keyboardShowing;
    BOOL _datePickerShowing;
    UIDatePicker *_datePicker;
    UIView *_focusedDateField;
    UIView *_datePickerWithBar;
    id _oldValue;
    NSDate *_replacedOldDate;
    float _savedNotesViewHeight;
    UIToolbar *_keyboardBar;
    id <TaskViewDelegate> delegate;
    id <TaskEditDelegate> editDelegate;
}

+ (id)taskViewWithNib;
- (void)setOldValue:(id)fp8;
- (id)oldValue;
- (void)setDatePickerWithBar:(id)fp8;
- (id)datePickerWithBar;
- (void)setDatePicker:(id)fp8;
- (id)datePicker;
- (id)dockView;
- (id)scrollView;
- (void)setEditDelegate:(id)fp8;
- (id)editDelegate;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setKeyboardBar:(id)fp8;
- (id)keyboardBar;
- (void)textFieldDidEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (void)textViewDidEndEditing:(id)fp8;
- (void)textViewDidBeginEditing:(id)fp8;
- (void)setEditing:(BOOL)fp8;
- (BOOL)editing;
- (void)valueChanged:(id)fp8;
- (void)cancelButtonPushed:(id)fp8;
- (void)clearButtonPushed:(id)fp8;
- (void)okButtonPushed:(id)fp8;
- (void)updateKeyboardBar;
- (void)updateDatePicker;
- (float)datePickerHeight;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (float)keyboardHeightFromBounds:(struct CGRect)fp8;
- (BOOL)viewTapped:(id)fp8;
- (BOOL)dateViewTapped:(id)fp8;
- (void)retireKeyboard;
- (void)changePickerDisplay:(int)fp8;
- (void)setDateFieldFromDatePicker:(BOOL)fp8 withColor:(id)fp12;
- (void)preparePicker;
- (void)scrollIntoView;
- (void)scrollIntoView:(id)fp8;
- (void)setupGestureRecognizers;
- (void)dealloc;
- (void)setScrollView:(id)fp8;
- (void)setDockView:(id)fp8;
- (id)getDatePickerWithBar;
- (id)getToolbar;

@end

