/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookAddRecord.h"

@interface UrlInterceptionMgr : _ABAddressBookAddRecord
{
    id <UrlInterceptor> currentInterceptor;
}

- (void)setCurrentInterceptor:(id)fp8;
- (id)currentInterceptor;
- (void)dealloc;
- (void)releaseAnyUrlInterception;
- (void)acquireUrlInterceptionWithInterceptor:(id)fp8;
- (BOOL)isUrlInterceptionInUse;

@end

