/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (GDFWProxy)
+ (void)replaceNSFileWrapper;
- (BOOL)replacementWriteToURL:(id)fp8 options:(unsigned int)fp12 originalContentsURL:(id)fp16 error:(id *)fp20;
- (BOOL)originalWriteToURL:(id)fp8 options:(unsigned int)fp12 originalContentsURL:(id)fp16 error:(id *)fp20;
- (void)removeFileWrappers:(id)fp8;
- (BOOL)replacementReadFromURL:(id)fp8 options:(unsigned int)fp12 error:(id *)fp16;
- (BOOL)originalReadFromURL:(id)fp8 options:(unsigned int)fp12 error:(id *)fp16;
- (BOOL)replacementMatchesContentsOfURL:(id)fp8;
- (BOOL)originalMatchesContentsOfURL:(id)fp8;
- (id)replacementInitWithURL:(id)fp8 options:(unsigned int)fp12 error:(id *)fp16;
- (id)originalInitWithURL:(id)fp8 options:(unsigned int)fp12 error:(id *)fp16;
@end

