/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (GDISProxy)
+ (void)replaceNSInputStream:(Class)fp8;
+ (id)replacementInputStreamWithURL:(id)fp8;
+ (id)originalInputStreamWithURL:(id)fp8;
+ (id)replacementInputStreamWithFileAtPath:(id)fp8;
+ (id)originalInputStreamWithFileAtPath:(id)fp8;
- (id)initWithURLReplacement:(id)fp8;
- (id)initWithURLOriginal:(id)fp8;
- (id)initWithFileAtPathReplacement:(id)fp8;
- (id)initWithFileAtPathOriginal:(id)fp8;
@end

