/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (GDARProxy)
+ (id)replacementClassPathsForResourcesOfType:(id)fp8 inDirectory:(id)fp12;
+ (id)originalClassPathsForResourcesOfType:(id)fp8 inDirectory:(id)fp12;
+ (id)replacementClassPathForResource:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16;
+ (id)originalClassPathForResource:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16;
+ (id)replacementURLsForResourcesWithExtension:(id)fp8 subdirectory:(id)fp12 inBundleWithURL:(id)fp16;
+ (id)originalURLsForResourcesWithExtension:(id)fp8 subdirectory:(id)fp12 inBundleWithURL:(id)fp16;
+ (id)replacementURLForResource:(id)fp8 withExtension:(id)fp12 subdirectory:(id)fp16 inBundleWithURL:(id)fp20;
+ (id)originalURLForResource:(id)fp8 withExtension:(id)fp12 subdirectory:(id)fp16 inBundleWithURL:(id)fp20;
+ (id)replacementBundleWithURL:(id)fp8;
+ (id)originalBundleWithURL:(id)fp8;
+ (id)replacementBundleWithPath:(id)fp8;
+ (id)originalBundleWithPath:(id)fp8;
+ (void)replaceNSBundle;
- (id)replacementPathsForResourcesOfType:(id)fp8 inDirectory:(id)fp12 forLocalization:(id)fp16;
- (id)originalPathsForResourcesOfType:(id)fp8 inDirectory:(id)fp12 forLocalization:(id)fp16;
- (id)replacementPathsForResourcesOfType:(id)fp8 inDirectory:(id)fp12;
- (id)originalPathsForResourcesOfType:(id)fp8 inDirectory:(id)fp12;
- (id)replacementPathForResource:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16 forLocalization:(id)fp20;
- (id)originalPathForResource:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16 forLocalization:(id)fp20;
- (id)replacementPathForResource:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16;
- (id)originalPathForResource:(id)fp8 ofType:(id)fp12 inDirectory:(id)fp16;
- (id)replacementPathForResource:(id)fp8 ofType:(id)fp12;
- (id)originalPathForResource:(id)fp8 ofType:(id)fp12;
- (id)replacementURLsForResourcesWithExtension:(id)fp8 subdirectory:(id)fp12 localization:(id)fp16;
- (id)originalURLsForResourcesWithExtension:(id)fp8 subdirectory:(id)fp12 localization:(id)fp16;
- (id)replacementURLsForResourcesWithExtension:(id)fp8 subdirectory:(id)fp12;
- (id)originalURLsForResourcesWithExtension:(id)fp8 subdirectory:(id)fp12;
- (id)replacementURLForResource:(id)fp8 withExtension:(id)fp12 subdirectory:(id)fp16 localization:(id)fp20;
- (id)originalURLForResource:(id)fp8 withExtension:(id)fp12 subdirectory:(id)fp16 localization:(id)fp20;
- (id)replacementURLForResource:(id)fp8 withExtension:(id)fp12 subdirectory:(id)fp16;
- (id)originalURLForResource:(id)fp8 withExtension:(id)fp12 subdirectory:(id)fp16;
- (id)replacementURLForResource:(id)fp8 withExtension:(id)fp12;
- (id)originalURLForResource:(id)fp8 withExtension:(id)fp12;
- (id)replacementBundleIdentifier;
- (id)originalBundleIdentifier;
- (id)replacementInfoDictionary;
- (id)originalInfoDictionary;
- (id)replacementBuiltInPlugInsPath;
- (id)originalBuiltInPlugInsPath;
- (id)replacementSharedSupportPath;
- (id)originalSharedSupportPath;
- (id)replacementSharedFrameworksPath;
- (id)originalSharedFrameworksPath;
- (id)replacementPrivateFrameworksPath;
- (id)originalPrivateFrameworksPath;
- (id)replacementPathForAuxiliaryExecutable:(id)fp8;
- (id)originalPathForAuxiliaryExecutable:(id)fp8;
- (id)replacementExecutablePath;
- (id)originalExecutablePath;
- (id)replacementResourcePath;
- (id)originalResourcePath;
- (id)replacementBundlePath;
- (id)originalBundlePath;
- (id)replacementBuiltInPlugInsURL;
- (id)originalBuiltInPlugInsURL;
- (id)replacementSharedSupportURL;
- (id)originalSharedSupportURL;
- (id)replacementSharedFrameworksURL;
- (id)originalSharedFrameworksURL;
- (id)replacementPrivateFrameworksURL;
- (id)originalPrivateFrameworksURL;
- (id)replacementURLForAuxiliaryExecutable:(id)fp8;
- (id)originalURLForAuxiliaryExecutable:(id)fp8;
- (id)replacementExecutableURL;
- (id)originalExecutableURL;
- (id)replacementResourceURL;
- (id)originalResourceURL;
- (id)replacementBundleURL;
- (id)originalBundleURL;
- (id)replacementInitWithURL:(id)fp8;
- (id)originalInitWithURL:(id)fp8;
- (id)replacementInitWithPath:(id)fp8;
- (id)originalInitWithPath:(id)fp8;
- (id)getHandleObj;
- (void)setHandleObj:(id)fp8;
@end

