/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (GDNSURLCacheProxy)
+ (id)replacementSharedURLCache;
+ (id)originalSharedURLCache;
+ (void)replacementSetSharedURLCache:(id)fp8;
+ (void)originalSetSharedURLCache:(id)fp8;
- (unsigned int)replacementCurrentDiskUsage;
- (unsigned int)originalCurrentDiskUsage;
- (unsigned int)replacementCurrentMemoryUsage;
- (unsigned int)originalCurrentMemoryUsage;
- (void)replacementSetDiskCapacity:(unsigned int)fp8;
- (void)originalSetDiskCapacity:(unsigned int)fp8;
- (void)replacementSetMemoryCapacity:(unsigned int)fp8;
- (void)originalSetMemoryCapacity:(unsigned int)fp8;
- (unsigned int)replacementDiskCapacity;
- (unsigned int)originalDiskCapacity;
- (unsigned int)replacementMemoryCapacity;
- (unsigned int)originalMemoryCapacity;
- (void)replacementRemoveAllCachedResponses;
- (void)originalRemoveAllCachedResponses;
- (void)replacementRemoveCachedResponseForRequest:(id)fp8;
- (void)originalRemoveCachedResponseForRequest:(id)fp8;
- (void)replacementStoreCachedResponse:(id)fp8 forRequest:(id)fp12;
- (void)originalStoreCachedResponse:(id)fp8 forRequest:(id)fp12;
- (id)replacementCachedResponseForRequest:(id)fp8;
- (id)originalCachedResponseForRequest:(id)fp8;
- (id)initWithMemoryCapacityReplacement:(unsigned int)fp8 diskCapacity:(unsigned int)fp12 diskPath:(id)fp16;
- (id)initWithMemoryCapacityOriginal:(unsigned int)fp8 diskCapacity:(unsigned int)fp12 diskPath:(id)fp16;
- (id)initReplacement;
- (id)initOriginal;
@end

