/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (UIApplicationDelegate)
- (id)gdWindow;
- (BOOL)gdApplication:(id)fp8 handleOpenURL:(id)fp12;
- (void)gdApplicationDidFinishLaunching:(id)fp8;
- (void)gdApplicationProtectedDataWillBecomeUnavailable:(id)fp8;
- (void)gdApplicationProtectedDataDidBecomeAvailable:(id)fp8;
- (void)gdApplication:(id)fp8 didChangeStatusBarFrame:(struct CGRect)fp12;
- (void)gdApplication:(id)fp8 willChangeStatusBarFrame:(struct CGRect)fp12;
- (void)gdApplication:(id)fp8 didChangeStatusBarOrientation:(int)fp12;
- (void)gdApplication:(id)fp8 willChangeStatusBarOrientation:(int)fp12 duration:(double)fp16;
- (BOOL)gdApplication:(id)fp8 shouldAllowExtensionPointIdentifier:(id)fp12;
- (void)gdApplication:(id)fp8 handleEventsForBackgroundURLSession:(id)fp12 completionHandler:(id)fp(null);
- (void)gdApplication:(id)fp8 performFetchWithCompletionHandler:(id)fp(null);
- (void)gdApplicationSignificantTimeChange:(id)fp8;
- (void)gdApplicationDidReceiveMemoryWarning:(id)fp8;
- (BOOL)gdApplication:(id)fp8 openURL:(id)fp12 sourceApplication:(id)fp16 annotation:(id)fp20;
- (void)gdApplication:(id)fp8 didReceiveLocalNotification:(id)fp12;
- (void)gdApplication:(id)fp8 didReceiveRemoteNotification:(id)fp12;
- (void)gdApplication:(id)fp8 didReceiveRemoteNotification:(id)fp12 fetchCompletionHandler:(id)fp(null);
- (void)gdApplication:(id)fp8 didFailToRegisterForRemoteNotificationsWithError:(id)fp12;
- (void)gdApplication:(id)fp8 didRegisterForRemoteNotificationsWithDeviceToken:(id)fp12;
- (void)gdApplicationWillTerminate:(id)fp8;
- (void)gdApplicationWillEnterForeground:(id)fp8;
- (void)gdApplicationDidEnterBackground:(id)fp8;
- (void)gdApplicationWillResignActive:(id)fp8;
- (void)gdApplicationDidBecomeActive:(id)fp8;
- (BOOL)gdApplication:(id)fp8 didFinishLaunchingWithOptions:(id)fp12;
- (BOOL)gdApplication:(id)fp8 willFinishLaunchingWithOptions:(id)fp12;
@end

