/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (GDLabelSizingCategory)
+ (struct CGSize)sizeForText:(id)fp8 withFont:(id)fp12 limitedByWidth:(float)fp16;
@end

