/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface _CATransform3DMakeScale (GDCWriteStreamProxy)
+ (void)replaceNSOutputStream:(Class)fp8;
+ (id)replacementOutputStreamToFileAtPath:(id)fp8 append:(BOOL)fp12;
+ (id)originalOutputStreamToFileAtPath:(id)fp8 append:(BOOL)fp12;
+ (id)replacementOutputStreamWithURL:(id)fp8 append:(BOOL)fp12;
+ (id)originalOutputStreamWithURL:(id)fp8 append:(BOOL)fp12;
- (id)initWithURLReplacement:(id)fp8 append:(BOOL)fp12;
- (id)initWithURLOriginal:(id)fp8 append:(BOOL)fp12;
- (id)initToFileAtPathReplacement:(id)fp8 append:(BOOL)fp12;
- (id)initToFileAtPathOriginal:(id)fp8 append:(BOOL)fp12;
@end

