/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSMutableArray;

@interface GDAppDelegateProxyLayer : _CATransform3DMakeScale
{
    id <UIApplicationDelegate> appDelegate;
    NSMutableArray *appDelegateMethods;
    BOOL passToHandleURL;
}

+ (id)sharedInstance;
+ (void)initializeGDAppDelegateProxyLayerWithAppDelegate:(id)fp8;
- (void)setPassToHandleURL:(BOOL)fp8;
- (BOOL)passToHandleURL;
- (void)setAppDelegateMethods:(id)fp8;
- (id)appDelegateMethods;
- (void)setAppDelegate:(id)fp8;
- (id)appDelegate;
- (BOOL)isURLSchemeBlocked:(id)fp8;
- (id)findAppDelegateMethodWithSel:(SEL)fp8;
- (void)determineEntryAcceptability;
- (void)initializeProxy;

@end

