/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSDictionary, NSString;

@interface GDBundle : _CATransform3DMakeScale
{
    NSString *m_bundlePath;
    NSString *m_executablePath;
    NSString *m_bundleIdentifier;
    NSDictionary *m_infoDic;
}

- (void)setM_infoDic:(id)fp8;
- (id)m_infoDic;
- (void)setM_bundleIdentifier:(id)fp8;
- (id)m_bundleIdentifier;
- (void)setM_executablePath:(id)fp8;
- (id)m_executablePath;
- (void)setM_bundlePath:(id)fp8;
- (id)m_bundlePath;
- (id)getFullPathWithName:(id)fp8 ofType:(id)fp12 subpath:(id)fp16 localization:(id)fp20;
- (id)getFullPathWithKey:(id)fp8;
- (id)getAllFileStringsWithSubPath:(id)fp8;
- (id)getAllDirStringsWithSubPath:(id)fp8;
- (id)converToURLArray:(id)fp8;
- (id)getStringArrayForResourceWithExtension:(id)fp8 subdirectory:(id)fp12 localization:(id)fp16 inBundleWithPath:(id)fp20;
- (id)getURLArrayForResourceWithExtension:(id)fp8 subdirectory:(id)fp12 localization:(id)fp16 inBundleWithPath:(id)fp20;
- (id)getNameForResource:(id)fp8 ofType:(id)fp12 subpath:(id)fp16 localization:(id)fp20 inBundleWithPath:(id)fp24;
- (id)bundleWithURL:(id)fp8;
- (id)bundleWithPath:(id)fp8;

@end

