/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface GDDirectByteBuffer : _CATransform3DMakeScale
{
    void *m_dbbInternal;
}

- (id)unreadData;
- (id)unreadDataAsString;
- (void)dealloc;
- (int)bytesUnread;
- (int)read:(char *)fp8 toMaxLength:(int)fp12;
- (void)writeData:(id)fp8;
- (void)write:(const char *)fp8 withLength:(int)fp12;
- (void)write:(const char *)fp8;
- (id)initWithDbb:(struct Dbb *)fp8;
- (id)init;

@end

