/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSDictionary, NSEntityDescription;

@interface GDEncryptedBinaryStoreCacheNode : _CATransform3DMakeScale
{
    NSEntityDescription *entityDescription;
    NSDictionary *propertyDataCache;
}

- (BOOL)resolvePropertyValues:(id *)fp8;
- (void)setPropertyCacheData:(id)fp8;
- (id)description;
- (id)valueForKey:(id)fp8;
- (id)entity;
- (id)initWithObjectID:(id)fp8;

@end

