/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

#import "GDFetchSQLDescriptor-Protocol.h"

@class GDSQLEntity, NSEntityDescription, NSManagedObjectContext, NSMutableArray, NSRelationshipDescription, NSString;

@interface GDFetchSQL : _CATransform3DMakeScale <GDFetchSQLDescriptor>
{
    id <GDStoreSQLDescriptor> _storeDescriptor;
    NSEntityDescription *_entity;
    GDSQLEntity *_mappedEntity;
    NSManagedObjectContext *_managedObjectContext;
    NSString *_variable;
    NSRelationshipDescription *_baseRelationsdhip;
    unsigned int _seed;
    unsigned int _maxSeed;
    GDFetchSQL *_context;
    unsigned int _structure;
    NSMutableArray *_whereParameters;
    NSMutableArray *_havingParameters;
    NSMutableArray *_blocks;
    NSMutableArray *_joins;
    BOOL _groupedByItself;
    NSString *_sql;
}

+ (id)scopedSqlForContext:(id)fp8 variable:(id)fp12 function:(id)fp16 entity:(id)fp20 properties:(id)fp24 toManyRelationship:(id)fp28 storeDescriptor:(id)fp32;
+ (id)scopedSqlForContext:(id)fp8 storeDescriptor:(id)fp12 entity:(id)fp16 variable:(id)fp20 collectionVariable:(id)fp24 properties:(id)fp28 predicate:(id)fp32 baseRelationship:(id)fp36;
+ (id)sqlForFetchRequest:(id)fp8 managedObjectContext:(id)fp12 storeDescriptor:(id)fp16;
- (unsigned int)maxSeed;
- (void)updateMaxSeed:(unsigned int)fp8;
- (unsigned int)seed;
- (unsigned int)nextSeed;
- (id)encapsulate:(id)fp8 withVariable:(id)fp12;
- (id)encapsulate:(id)fp8 direct:(BOOL)fp12;
- (BOOL)respondsToGroup:(int)fp8;
- (BOOL)isGroupedByItself;
- (void)setGroupedByItself:(BOOL)fp8;
- (void)addJoins:(id)fp8;
- (void)addParameters:(id)fp8 belongingGroup:(int)fp12;
- (void)appendSql:(id)fp8 toGroup:(int)fp12;
- (void)assignSql:(id)fp8 toGroup:(int)fp12;
- (int)indexForGroup:(int)fp8;
- (id)getParentSelection:(id)fp8;
- (void)getChildrenOfEntity:(id)fp8 andFill:(id)fp12;
- (id)sql;
- (BOOL)build:(id *)fp8;
- (id)parameters;
- (void)dealloc;
- (id)storeDescriptor;
- (id)context;
- (id)managedObjectContext;
- (id)entityForDescription:(id)fp8;
- (id)resolveEntityForVariable:(id)fp8;
- (id)coreEntity;
- (id)entity;
- (id)initWithStoreDescriptor:(id)fp8 context:(id)fp12 managedObjectContext:(id)fp16 entity:(id)fp20 baseRelationship:(id)fp24 variable:(id)fp28 seed:(unsigned int)fp32;
- (id)initWithStoreDescriptor:(id)fp8 managedObjectContext:(id)fp12 entity:(id)fp16;

@end

