/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GDFetchSQLDescriptor <NSObject>
- (unsigned int)maxSeed;
- (void)updateMaxSeed:(unsigned int)fp8;
- (unsigned int)seed;
- (unsigned int)nextSeed;
- (id)context;
- (id)managedObjectContext;
- (id)coreEntity;
- (id)entity;
- (id)resolveEntityForVariable:(id)fp8;
- (id)storeDescriptor;
- (id)encapsulate:(id)fp8 withVariable:(id)fp12;
- (id)encapsulate:(id)fp8 direct:(BOOL)fp12;
- (BOOL)isGroupedByItself;
- (void)setGroupedByItself:(BOOL)fp8;
- (void)addJoins:(id)fp8;
- (void)addParameters:(id)fp8 belongingGroup:(int)fp12;
- (BOOL)respondsToGroup:(int)fp8;
- (void)appendSql:(id)fp8 toGroup:(int)fp12;
- (void)assignSql:(id)fp8 toGroup:(int)fp12;
- (id)parameters;
- (id)sql;
- (BOOL)build:(id *)fp8;
@end

