/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GDFetchSQLDescriptor.h"

@class NSArray;

@interface GDFetchGroupByDescriptor : GDFetchSQLDescriptor
{
    NSArray *_properties;
}

+ (id)descriptorWithSqlDescriptor:(id)fp8 properties:(id)fp12;
- (BOOL)build:(id *)fp8;
- (void)dealloc;
- (id)initWithSqlDescriptor:(id)fp8 properties:(id)fp12;

@end

