/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class GDFetchSQL, NSFetchRequest, NSManagedObjectContext;

@interface GDFetchSQLGenerator : _CATransform3DMakeScale
{
    NSManagedObjectContext *_managedObjectContext;
    GDFetchSQL *_fetchSQL;
    NSFetchRequest *_fetchRequest;
    id <GDStoreSQLDescriptor> _storeDescriptor;
}

+ (id)sqlForFetchRequest:(id)fp8 managedObjectContext:(id)fp12 storeDescriptor:(id)fp16;
- (id)storeDescriptor;
- (id)fetchRequest;
- (id)sql;
- (void)build:(id *)fp8;
- (id)parameters;
- (void)dealloc;
- (id)initWithFetchRequest:(id)fp8 managedObjectContext:(id)fp12 storeDescriptor:(id)fp16;

@end

