/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSHTTPURLResponse, NSString;

@interface GDHTTPCacheEntry : _CATransform3DMakeScale
{
    BOOL m_bCacheNeeded;
    int m_statusCode;
    _Bool m_bErrored;
    BOOL m_bValidationNeeded;
    int m_contentLength;
    double m_expiresTime;
    BOOL m_validationValue;
    double m_correctedInitialAge;
    NSString *m_url;
    double m_maxAge;
    NSString *m_ifModifiedSinceStr;
    double m_ifModifiedSince;
    NSString *m_eTag;
    NSString *m_contentEncoding;
    NSString *m_dateString;
    double m_dateValue;
    double m_lastVisitedTime;
    NSString *m_fileName;
    NSHTTPURLResponse *m_response;
    NSString *m_contentType;
    double _responseTime;
}

+ (id)entryWithRequest:(id)fp8 response:(id)fp12;
- (void)setResponseTime:(double)fp8;
- (double)responseTime;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setFileName:(id)fp8;
- (id)fileName;
- (void)setLastVisitedTime:(double)fp8;
- (double)lastVisitedTime;
- (void)setExpiresTime:(double)fp8;
- (double)expiresTime;
- (void)setDateValue:(double)fp8;
- (double)dateValue;
- (void)setDateString:(id)fp8;
- (id)dateString;
- (void)setContentType:(id)fp8;
- (id)contentType;
- (void)setContentEncoding:(id)fp8;
- (id)contentEncoding;
- (void)setETag:(id)fp8;
- (id)eTag;
- (void)setIfModifiedSince:(double)fp8;
- (double)ifModifiedSince;
- (void)setIfModifiedSinceStr:(id)fp8;
- (id)ifModifiedSinceStr;
- (void)setMaxAge:(double)fp8;
- (double)maxAge;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)setCorrectedInitialAge:(double)fp8;
- (double)correctedInitialAge;
- (void)setValidationNeeded:(BOOL)fp8;
- (BOOL)validationNeeded;
- (BOOL)checkAndDeleteFromStore;
- (id)mimeType;
- (BOOL)isCacheNeeded;
- (BOOL)isServerValidationNeeded;
- (double)getCurrentAge:(double)fp8;
- (BOOL)updateHTTPRequest:(id)fp8;
- (void)computeCorrectedInitialAgeWithDate:(double)fp8 age:(id)fp16 requestTime:(double)fp20 responseTime:(double)fp28 now:(double)fp36;
- (id)processMultiValueField:(id)fp8;
- (void)parseAndLoadDirectives:(id)fp8 response:(id)fp12 requestTime:(double)fp16;
- (BOOL)handle304Status;
- (void)dealloc;
- (id)initWithRequest:(id)fp8 response:(id)fp12;
- (id)init;

@end

