/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface GDInterAppManager : _CATransform3DMakeScale
{
}

+ (BOOL)processStreamPushNow:(id)fp8 sourceApplication:(id)fp12 annotation:(id)fp16;
+ (void)triggerNotification:(id)fp8 sourceApplication:(id)fp12;
+ (BOOL)isSourceApplicationAllowed:(id)fp8;
+ (BOOL)sendFile:(id)fp8 toApplication:(id)fp12 withSuccessBlock:(id)fp(null);
+ (BOOL)sendFileToGood:(id)fp8 withSuccessBlock:(id)fp(null);
+ (BOOL)canSendFileToGood;
+ (BOOL)canSendFileToApplication:(id)fp8;
+ (BOOL)didReceiveStreamPushRequest:(id)fp8 sourceApplication:(id)fp12;
+ (BOOL)didReceiveUpdateRequest:(id)fp8;
+ (BOOL)didReceiveUnblockRequest:(id)fp8;
+ (BOOL)didReceiveBlockRequest:(id)fp8;
+ (BOOL)didReceiveLockRequest:(id)fp8;
+ (BOOL)didReceiveWipeRequest:(id)fp8;
+ (BOOL)didReceiveAuthorizeRequest:(id)fp8;
+ (BOOL)didReceiveURL:(id)fp8 sourceApplication:(id)fp12 annotation:(id)fp16;
+ (BOOL)isIccLocked;
- (void)dealloc;
- (id)init;

@end

