/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GDViewController.h"

#import "GDActivityIndicatorViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class GDActivationInfo, GDActivityIndicatorView, GDAlertView, GDEasyActivationTableView, GDEasyActivationTableViewCell, NSDictionary, NSString, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface GDLoginViewController : GDViewController <GDActivityIndicatorViewDelegate, UITextFieldDelegate, UIAlertViewDelegate, UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate>
{
    BOOL isForTimeout;
    BOOL isTouchIdStarted;
    struct GSSecureManagerUnlockCallback *callback;
    BOOL isKeyBoardDisp;
    BOOL _isActivationPasswordScreen;
    UITextField *passwordField;
    GDAlertView *gdAlertView;
    GDEasyActivationTableViewCell *passwordFieldCell;
    GDEasyActivationTableView *tableViewEA;
    NSString *_appId;
    NSString *_appName;
    NSString *_appVersion;
    GDActivityIndicatorView *_activityIndicator;
    UIImageView *_activationDelegateApplicationIcon;
    UILabel *_upperTextLabel;
    UILabel *_lowerTextLabel;
    UIView *_activateAppView;
    UILabel *_usePasswordToActivateLabel;
    NSDictionary *_dictionaryOfSelectedApp;
    GDActivationInfo *_activationInfo;
    id _activationCallback;
    int _orientation;
    UIButton *_backButton;
    UIButton *_okButton;
}

+ (BOOL)isShowingTouchId;
+ (BOOL)wasTouchIdCanceled;
- (void)setOkButton:(id)fp8;
- (id)okButton;
- (void)setBackButton:(id)fp8;
- (id)backButton;
- (void)setOrientation:(int)fp8;
- (int)orientation;
- (void)setActivationCallback:(id)fp(null);
- (id)activationCallback;
- (void)setActivationInfo:(id)fp8;
- (id)activationInfo;
- (void)setDictionaryOfSelectedApp:(id)fp8;
- (id)dictionaryOfSelectedApp;
- (void)setUsePasswordToActivateLabel:(id)fp8;
- (id)usePasswordToActivateLabel;
- (void)setActivateAppView:(id)fp8;
- (id)activateAppView;
- (void)setLowerTextLabel:(id)fp8;
- (id)lowerTextLabel;
- (void)setUpperTextLabel:(id)fp8;
- (id)upperTextLabel;
- (void)setActivationDelegateApplicationIcon:(id)fp8;
- (id)activationDelegateApplicationIcon;
- (void)setActivityIndicator:(id)fp8;
- (id)activityIndicator;
- (void)setIsActivationPasswordScreen:(BOOL)fp8;
- (BOOL)isActivationPasswordScreen;
- (void)setAppVersion:(id)fp8;
- (id)appVersion;
- (void)setAppName:(id)fp8;
- (id)appName;
- (void)setAppId:(id)fp8;
- (id)appId;
- (void)setCallback:(struct GSSecureManagerUnlockCallback *)fp8;
- (struct GSSecureManagerUnlockCallback *)callback;
- (void)setIsKeyBoardDisp:(BOOL)fp8;
- (BOOL)isKeyBoardDisp;
- (void)setTableViewEA:(id)fp8;
- (id)tableViewEA;
- (void)setPasswordFieldCell:(id)fp8;
- (id)passwordFieldCell;
- (void)setGdAlertView:(id)fp8;
- (id)gdAlertView;
- (void)setIsTouchIdStarted:(BOOL)fp8;
- (BOOL)isTouchIdStarted;
- (void)setIsForTimeout:(BOOL)fp8;
- (BOOL)isForTimeout;
- (void)setPasswordField:(id)fp8;
- (id)passwordField;
- (void)clearSensitiveData;
- (BOOL)shouldClearSensitiveData;
- (void)adjustButtonsUnderFrame:(struct CGRect)fp8;
- (void)adjustRequestingAppDataToOrientation:(int)fp8;
- (float)heightForRequestingAppData;
- (void)adjustUsePasswordLabelSizeToOrientation:(int)fp8;
- (float)heightForUsePasswordLabel;
- (void)adjustActivateAppViewToOrientation:(int)fp8;
- (float)heightForActivateAppView;
- (float)heightOffsetForTableView:(BOOL)fp8;
- (float)heightOffsetForRequestingAppData;
- (float)horizontalScreenContentMargin;
- (void)keyboardDidShow:(id)fp8;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (double)keyboardAnimationDurationForNotification:(id)fp8;
- (void)startAnimation:(double)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)updateOKButtonState;
- (void)loadViewForiPhone;
- (void)loadViewForiPad;
- (void)loadViewForAll;
- (void)setTablePosition;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)willResetPassword;
- (void)forgotPasswordClicked;
- (id)getAppIconFromPasteboard;
- (void)setAppFromDictionary;
- (void)clearLoginViewControllerReference;
- (void)backPressed;
- (void)okPressed;
- (void)bottomInfoButtonAction;
- (void)updateActivationLockUI:(BOOL)fp8;
- (void)showAllUnlockViews;
- (void)hideAllUnlockViews;
- (void)hideAllActivationSubviews;
- (void)setScreenForActivationPassword;
- (void)hideSpinnerAndHideDimmingWindow:(BOOL)fp8;
- (void)hideSpinner;
- (void)didStopAnimationOfActivityIndicator:(id)fp8;
- (void)willStartAnimationOfActivityIndicator:(id)fp8;
- (void)showSpinner;
- (void)passwordDidValidate;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)checkPassword;
- (void)passwordWillValidate;
- (void)initInputUIData;
- (void)textFieldDidEndEditing:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)updateTitleForBottomButton;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (BOOL)showFinger;
- (void)showKeyboardAfterDelay;
- (void)setPasswordOrPinDisplay;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

