/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSArray, NSString;

@interface GDMail : _CATransform3DMakeScale
{
    BOOL _isHTML;
    NSString *_body;
    NSString *_subject;
    NSArray *_to;
    NSArray *_cc;
    NSArray *_bcc;
}

- (void)setIsHTML:(BOOL)fp8;
- (BOOL)isHTML;
- (void)setBcc:(id)fp8;
- (id)bcc;
- (void)setCc:(id)fp8;
- (id)cc;
- (void)setTo:(id)fp8;
- (id)to;
- (void)setSubject:(id)fp8;
- (id)subject;
- (void)setBody:(id)fp8;
- (id)body;
- (id)mailAsParamsDictionaryForGFEMailService;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (oneway void)dealloc;
- (id)initWithBody:(id)fp8 subject:(id)fp12 to:(id)fp16 cc:(id)fp20 bcc:(id)fp24;

@end

