/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

#import "NSStreamDelegate-Protocol.h"

@class GDCWriteStream;

@interface GDNSOutputStream : _CATransform3DMakeScale <NSStreamDelegate>
{
    GDCWriteStream *_writeStream;
}

+ (id)outputStreamWithFileAtPath:(id)fp8 append:(BOOL)fp12;
- (void)setWriteStream:(id)fp8;
- (id)writeStream;
- (void)stream:(id)fp8 handleEvent:(unsigned int)fp12;
- (void)removeFromRunLoop:(id)fp8 forMode:(id)fp12;
- (void)scheduleInRunLoop:(id)fp8 forMode:(id)fp12;
- (id)streamError;
- (unsigned int)streamStatus;
- (BOOL)setProperty:(id)fp8 forKey:(id)fp12;
- (id)propertyForKey:(id)fp8;
- (void)open;
- (void)close;
- (BOOL)hasSpaceAvailable;
- (int)write:(const char *)fp8 maxLength:(unsigned int)fp12;
- (id)init;

@end

