/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSMutableArray;

@interface GDProxyController : _CATransform3DMakeScale
{
    NSMutableArray *replaceObjectsQ;
}

+ (id)sharedInstance;
- (void)proxyMethodWithProxy:(id)fp8 withOptions:(id)fp12;
- (void)proxyMethodWithProxy:(id)fp8;
- (void)proxyMethod:(SEL)fp8 WithSel:(SEL)fp12 AndStashingIn:(SEL)fp16 ForClass:(Class)fp20 WithOptions:(id)fp24;
- (void)proxyMethod:(SEL)fp8 WithSel:(SEL)fp12 AndStashingIn:(SEL)fp16 ForClass:(Class)fp20;
- (struct objc_method *)getMethodFrom:(Class)fp8 AndSelector:(SEL)fp12 WithOptions:(id)fp16;
- (id)getReplaceQ;
- (void)dealloc;

@end

