/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface GDReconnector : _CATransform3DMakeScale
{
    BOOL weAreConnecting;
}

+ (id)getSharedInstance;
- (void)setWeAreConnecting:(BOOL)fp8;
- (BOOL)weAreConnecting;
- (void)connectorMethod:(id)fp8;
- (BOOL)isConnecting;
- (void)clearConnecting;
- (void)setConnecting;
- (void)dealloc;
- (void)reconnectWhenAvailable;
- (id)init;

@end

