/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GDViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class GDAlertView, GDEasyActivationTableView, GDEasyActivationTableViewCell, NSMutableArray, NSString, UIButton, UILabel, UISwitch, UITextField, UIView;

@interface GDSetPasswordViewController : GDViewController <UIGestureRecognizerDelegate, UITextFieldDelegate, UITableViewDataSource, UIScrollViewDelegate>
{
    BOOL isChangePassword;
    BOOL isLaunchedByApp;
    struct GSSecureManagerSetPasswordCallback *passwordCallback;
    struct GSSecureManagerUnlockCallback *unlockCallback;
    BOOL isKeyBoardDisp;
    BOOL _areConfirmButtonsHidden;
    UITextField *passwordField;
    UITextField *validateField;
    UITextField *oldPasswordField;
    GDEasyActivationTableViewCell *passwordFieldCell;
    GDEasyActivationTableViewCell *validateFieldCell;
    GDEasyActivationTableViewCell *oldPasswordFieldCell;
    GDEasyActivationTableView *tableViewEA;
    NSMutableArray *cellArr;
    struct GSSecureManagerTouchIdCallback *_touchIdCallback;
    UIView *_switchContainer;
    UISwitch *_switchView;
    UILabel *_switchLabel;
    NSString *_passwordRequirements;
    UIButton *_backButton;
    UIButton *_okButton;
    GDAlertView *_settingsChangeAlert;
}

- (void)setSettingsChangeAlert:(id)fp8;
- (id)settingsChangeAlert;
- (void)setAreConfirmButtonsHidden:(BOOL)fp8;
- (BOOL)areConfirmButtonsHidden;
- (void)setOkButton:(id)fp8;
- (id)okButton;
- (void)setBackButton:(id)fp8;
- (id)backButton;
- (void)setPasswordRequirements:(id)fp8;
- (id)passwordRequirements;
- (void)setSwitchLabel:(id)fp8;
- (id)switchLabel;
- (void)setSwitchView:(id)fp8;
- (id)switchView;
- (void)setSwitchContainer:(id)fp8;
- (id)switchContainer;
- (void)setTouchIdCallback:(struct GSSecureManagerTouchIdCallback *)fp8;
- (struct GSSecureManagerTouchIdCallback *)touchIdCallback;
- (void)setUnlockCallback:(struct GSSecureManagerUnlockCallback *)fp8;
- (struct GSSecureManagerUnlockCallback *)unlockCallback;
- (void)setPasswordCallback:(struct GSSecureManagerSetPasswordCallback *)fp8;
- (struct GSSecureManagerSetPasswordCallback *)passwordCallback;
- (void)setCellArr:(id)fp8;
- (id)cellArr;
- (void)setIsKeyBoardDisp:(BOOL)fp8;
- (BOOL)isKeyBoardDisp;
- (void)setTableViewEA:(id)fp8;
- (id)tableViewEA;
- (void)setOldPasswordFieldCell:(id)fp8;
- (id)oldPasswordFieldCell;
- (void)setValidateFieldCell:(id)fp8;
- (id)validateFieldCell;
- (void)setPasswordFieldCell:(id)fp8;
- (id)passwordFieldCell;
- (void)setIsLaunchedByApp:(BOOL)fp8;
- (BOOL)isLaunchedByApp;
- (void)setIsChangePassword:(BOOL)fp8;
- (BOOL)isChangePassword;
- (void)setOldPasswordField:(id)fp8;
- (id)oldPasswordField;
- (void)setValidateField:(id)fp8;
- (id)validateField;
- (void)setPasswordField:(id)fp8;
- (id)passwordField;
- (void)dismissUI:(id)fp(null);
- (void)displayChangeDialog;
- (void)updateFirstResponder:(id)fp8;
- (void)clearSensitiveData;
- (BOOL)shouldClearSensitiveData;
- (void)showPasswordRequirements;
- (void)bottomInfoButtonAction;
- (void)dismissKeyboard;
- (void)updateInfoButtonActions;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)keyboardDidShow:(id)fp8;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (double)keyboardAnimationDurationForNotification:(id)fp8;
- (void)adjustTouchIDSectionUnderFrame:(struct CGRect)fp8;
- (void)adjustButtonsUnderFrame:(struct CGRect)fp8;
- (BOOL)shouldShowTouchIDView;
- (void)startAnimation:(double)fp8;
- (void)setSwitchContainerFrame:(struct CGRect)fp8;
- (void)setTablePosition;
- (void)backPressed;
- (void)okPressed;
- (void)loadViewForAll;
- (void)loadViewForiPhone;
- (void)loadViewForiPad;
- (void)changeSwitch:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)passwordDidSet;
- (BOOL)passwordWillSet;
- (BOOL)checkPasswordStrength:(id)fp8;
- (BOOL)isPasswordContainingPrivateInfo:(id)fp8;
- (void)initInputUIData;
- (void)setPasswordGuideWithPolicyInformation;
- (void)cancelButtonClicked;
- (void)clearFieldsForSecurity;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)dealloc;
- (void)handleInteractivePopGesture:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

