/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface GDService : _CATransform3DMakeScale
{
    id <GDServiceDelegate> delegate;
}

+ (BOOL)bringToFront:(id)fp8 error:(id *)fp12;
+ (BOOL)replyTo:(id)fp8 withParams:(id)fp12 bringClientToFront:(int)fp16 withAttachments:(id)fp20 requestID:(id)fp24 error:(id *)fp28;
- (id)getDelegate;
- (void)setDelegate:(id)fp8;

@end

