/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSMutableSet, NSString, UIPasteboard;

@interface GDServiceDiscovery : _CATransform3DMakeScale
{
    NSMutableSet *services;
    NSString *_appName;
    UIPasteboard *__pasteboard;
    id <GDServiceDiscoveryDelegate> _delegate;
}

+ (void)setOwnName:(id)fp8;
+ (void)setServiceDelegate:(id)fp8;
+ (void)registeredGFEApplication:(id *)fp8 andVersion:(id *)fp12;
+ (id)applicationsProvidingService:(id)fp8 minimumVersion:(id)fp12;
+ (id)registeredApplications;
+ (void)unregisterService:(id)fp8 version:(id)fp12;
+ (void)registerService:(id)fp8 version:(id)fp12;
+ (void)updateServiceDirectory;
+ (void)enteringForeground;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)instance;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)set_pasteboard:(id)fp8;
- (id)_pasteboard;
- (void)setAppName:(id)fp8;
- (id)appName;
- (void)setServices:(id)fp8;
- (id)services;
- (id)getPasteboard;
- (void)dealloc;
- (id)init;
- (void)handlePasteBoardRemoved;
- (void)handlePasteBoardChange;

@end

