/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface GDSecureStoragePwdMgr : _CATransform3DMakeScale
{
}

+ (int)checkPasswordStrength:(id)fp8;
+ (BOOL)changePassword:(id)fp8 to:(id)fp12;
+ (BOOL)validatePassword:(id)fp8;
+ (BOOL)clearInMemoryPassword;
+ (BOOL)isPwdSet;
+ (BOOL)clearPassword:(id)fp8;
+ (BOOL)setPassword:(id)fp8;

@end

