/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@interface GDSplashViewController : _CATransform3DMakeScale
{
}

- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)didReceiveMemoryWarning;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

