/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class NSMutableArray, NSRecursiveLock, UIWindow;

@interface GDUIWindowProxyLayer : _CATransform3DMakeScale
{
    BOOL _isControllingWindows;
    UIWindow *_currentKeyWindow;
    NSMutableArray *_heldWindows;
    NSRecursiveLock *_windowLock;
}

+ (void)setupProxy;
+ (id)sharedInstance;
- (void)setWindowLock:(id)fp8;
- (id)windowLock;
- (void)setHeldWindows:(id)fp8;
- (id)heldWindows;
- (void)setCurrentKeyWindow:(id)fp8;
- (id)currentKeyWindow;
- (void)setIsControllingWindows:(BOOL)fp8;
- (BOOL)isControllingWindows;
- (void)revealWindows;
- (void)hideWindows;
- (void)cleanOutStash;
- (BOOL)isWindowInStash:(id)fp8;
- (void)makeWindowKey:(id)fp8;
- (void)removeWindowFromStash:(id)fp8;
- (void)addWindowToStash:(id)fp8;
- (void)addNewKeyWindow:(id)fp8;
- (void)dealloc;
- (id)init;

@end

