/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GDURLProtocolHttpAdapterDelegate <NSObject>
- (void)didFinishViaRoute:(id)fp8;
- (void)didLoadDataViaRoute:(id)fp8;
- (void)didHeadersReceivedViaRoute:(id)fp8;
- (void)requireClientAuthentication;
- (void)requireCertificateVerification;
- (void)willSendVia:(id)fp8;
@end

