/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class GTContainerDH, NSData, NSMutableArray, NSString;

@interface GTICCConnectionBridge : _CATransform3DMakeScale
{
    NSMutableArray *_queue;
    NSString *_application;
    BOOL _isClient;
    NSMutableArray *_attachments;
    int _requestId;
    unsigned int _state;
    BOOL _isEnterpriseMatch;
    int _version;
    id _params;
    BOOL _initiating;
    BOOL _socketIntendsToconnect;
    BOOL _authorize;
    int _enterpriseId;
    NSData *_ourCertificate;
    NSData *_theirCertificate;
    GTContainerDH *_dhContainer;
    int _streamPushPort;
    long long _lastPairTime;
}

+ (int)nextRequestId;
+ (id)createConnectionWithVersion:(int)fp8 application:(id)fp12 isClient:(BOOL)fp16;
- (void)setStreamPushPort:(int)fp8;
- (int)streamPushPort;
- (void)setDhContainer:(id)fp8;
- (id)dhContainer;
- (void)setTheirCertificate:(id)fp8;
- (id)theirCertificate;
- (void)setOurCertificate:(id)fp8;
- (id)ourCertificate;
- (void)setLastPairTime:(long long)fp8;
- (long long)lastPairTime;
- (void)setEnterpriseId:(int)fp8;
- (int)enterpriseId;
- (void)setAuthorize:(BOOL)fp8;
- (BOOL)authorize;
- (void)setSocketIntendsToconnect:(BOOL)fp8;
- (BOOL)socketIntendsToconnect;
- (void)setInitiating:(BOOL)fp8;
- (BOOL)initiating;
- (int)version;
- (int)send:(id)fp8 attachments:(id)fp12;
- (_Bool)createClientOnPort:(int)fp8 readBufferSize:(int)fp12 writeBufferSize:(int)fp16;
- (_Bool)createClientOnPort:(int)fp8;
- (_Bool)createServerWithReadBufferSize:(int)fp8 writeBufferSize:(int)fp12;
- (_Bool)createServer;
- (void)close;
- (int)port;
- (id)initForApplication:(id)fp8 isClient:(BOOL)fp12;
- (BOOL)checkAndSetConnectionStamp;
- (void)copyStateFromConnection:(id)fp8;
- (BOOL)isEnterpriseMatch;
- (void)setEnterpriseMatch:(BOOL)fp8;
- (void)setParams:(id)fp8;
- (id)attachments;
- (void)setState:(unsigned int)fp8;
- (void)removeStateFlag:(unsigned int)fp8;
- (BOOL)isClosing;
- (BOOL)isClosed;
- (BOOL)isReceiving;
- (BOOL)isSending;
- (BOOL)isConnected;
- (id)applicationId;
- (void)setRequestId:(int)fp8;
- (int)requestId;
- (int)type;
- (void)setClientState:(BOOL)fp8;
- (BOOL)isClient;
- (void)resetDHContainer;
- (void)dealloc;

@end

