/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

#import "GTSocketCommunicationDelegate-Protocol.h"
#import "NSStreamDelegate-Protocol.h"

@class GCDAsyncSocket, NSError, NSInputStream, NSOutputStream;

@interface GTSocketCommunication : _CATransform3DMakeScale <NSStreamDelegate, GTSocketCommunicationDelegate>
{
    GCDAsyncSocket *_socket;
    int _packetTag;
    id <GTSocketCommunicationDelegate> _socketCommunicationDelegate;
    unsigned int _backgroundTaskID;
    NSOutputStream *_writeToFileOut;
    NSInputStream *_readFromFileIn;
    id _successBlock;
    id _clientConnectedBlock;
    BOOL _isServer;
    BOOL _isFileWriter;
    BOOL _isFileReader;
    BOOL _isClient;
    BOOL _wantsMore;
    NSError *_pendingError;
}

+ (id)delegateWithSuccessBlock:(id)fp(null);
+ (id)fileReaderFromStream:(id)fp8 delegate:(id)fp12;
+ (id)fileReaderFrom:(id)fp8 delegate:(id)fp12;
+ (id)fileWriterDelegateToStream:(id)fp8 delegate:(id)fp12;
+ (id)fileWriterDelegateTo:(id)fp8 delegate:(id)fp12;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setSocket:(id)fp8;
- (id)socket;
- (void)successBlock:(id)fp8;
- (id)initWithSuccessBlock:(id)fp(null);
- (void)readFile;
- (id)initWithInputStream:(id)fp8 delegate:(id)fp12;
- (id)initWithFileSource:(id)fp8 delegate:(id)fp12;
- (void)fileWriterReceivedData:(id)fp8;
- (void)handleWriteToEvent:(unsigned int)fp8;
- (id)initWithOutputStream:(id)fp8 delegate:(id)fp12;
- (id)initWithFileDestination:(id)fp8 delegate:(id)fp12;
- (void)socket:(id)fp8 didReadData:(id)fp12 withTag:(long)fp16;
- (void)serverConnected;
- (id)initWithDelegate:(id)fp8;
- (BOOL)streamWantsMore;
- (void)clientConnected;
- (void)socket:(id)fp8 didWriteDataWithTag:(long)fp12;
- (void)socket:(id)fp8 didAcceptNewSocket:(id)fp12;
- (void)serverReceivedData:(id)fp8;
- (id)initSenderWithDelegate:(id)fp8 clientConnectedBlock:(id)fp(null);
- (void)dealloc;
- (void)stream:(id)fp8 handleEvent:(unsigned int)fp12;
- (void)invalidate;
- (void)socketDidDisconnect:(id)fp8 withError:(id)fp12;
- (void)socket:(id)fp8 didConnectToHost:(id)fp12 port:(unsigned short)fp16;
- (void)streamEndedWithError:(id)fp8;
- (void)streamDidReceiveData:(id)fp8;
- (void)encounteredError:(id)fp8;
- (void)stop;

@end

