/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CATransform3DMakeScale.h"

@class LMAlertView;

@interface LMEmbeddedViewController : _CATransform3DMakeScale
{
    LMAlertView *_alertView;
}

- (void)setAlertView:(id)fp8;
- (id)alertView;
- (BOOL)shouldAutorotate;
- (void)dismissViewControllerAnimated:(BOOL)fp8 completion:(id)fp(null);

@end

