//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class ABExcludes;

@interface ABAndGoodDbSyncProcessor : NSObject
{
    struct auto_ptr<GoodDbSyncSource> m_goodDbSyncSourceRef;
    struct auto_ptr<GoodDbToABSyncItemFieldKeyMapper> m_goodDbToAbKeyMapperRef;
    struct auto_ptr<ABToGoodDbSyncItemFieldKeyMapper> m_abToGoodDbKeyMapperRef;
    struct auto_ptr<LSMappingTable<unsigned short, int>> m_mappingTableRef;
    struct auto_ptr<LSSyncer<unsigned short, AKnownAddressField, int, ABPropertyKey>> m_syncerRef;
    struct auto_ptr<ABSyncSource> m_abSyncSourceRef;
    struct auto_ptr<ILSChecksumCalculator> m_checksumCalculatorRef;
    ABExcludes *abExcludes;
    BOOL hasCheckedForFirstSync;
}

+ (BOOL)isContactReMappingDone;
+ (void)setContactReMappingDone;
+ (BOOL)doesSyncLockFileExist;
+ (BOOL)deleteSyncLockFile;
+ (BOOL)createSyncLockFile;
+ (int)knownAddressFieldFromcontactFieldSyncId:(int)arg1;
+ (int)contactFieldSyncIdFromKnownAddressField:(int)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (BOOL)hasContactsInNativeDb;
- (BOOL)clearExcludes;
- (void)clearMappingTable;
- (void)clearAddressBookAllContacts;
- (void)resetAddressBookAndSync;
- (void)runNativeDBIntegrityCheck;
- (void)clearAddressBook;
- (void)simulatePushSyncModifyGoodDb:(int)arg1;
- (void)simulatePushSyncDelGoodDb:(int)arg1;
- (void)simulatePushSyncAddGoodDb:(int)arg1;
- (void)clearGoodDb;
- (void)modifyContactsInNativeDb:(int)arg1;
- (void)modifyContactsInGoodDb:(int)arg1;
- (void)deleteContactsInNativeDb:(int)arg1;
- (void)deleteContactsInGoodDb:(int)arg1;
- (void)addRandomItemsToSimulGoodDb:(int)arg1;
- (void)addXmlContactsToGoodDb;
- (void)addRandomItemsToAddressBook:(int)arg1;
- (void)addXmlContactsToNativeDb;
- (void)dumpExcludes;
- (void)dumpMappingTable;
- (void)dumpAddressBook;
- (int)dumpAddressBookStats;
- (int)dumpGoodDbStats;
- (void)dumpGoodDb;
- (BOOL)hasExcludes;
- (BOOL)isMappingTableEmpty;
- (BOOL)excludeCurrentABContactsFromSync;
- (int)pushDeleteFromGoodDb:(unsigned short)arg1;
- (int)pushModifyFromGoodDb:(unsigned short)arg1;
- (int)pushAddFromGoodDb:(unsigned short)arg1;
- (void)resetStopFlag;
- (BOOL)hasBeenStopped;
- (void)stopSync;
- (int)sync:(BOOL)arg1 deletionCallback:(CDUnknownFunctionPointerType)arg2;
- (BOOL)isAddressBookAccessDisallowed;
- (BOOL)setUpAbSyncSourceAbSource;
- (void)checkForFirstSync;
- (BOOL)ensureDbsPresence;
- (id)getSyncFields;
- (void)setSyncFields:(id)arg1;
- (int)getMappingTableVersion;
- (void)setUpSyncer;
- (void)setUpGoodSyncSource;
- (void)setUpAbSyncSource;
- (id)init;

@end

