//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

#import "SendLogCommandDelegate.h"

@class SendLogCommand, UIActivityIndicatorView, UIButton, UIScrollView, UITextView;

@interface AboutScreenVCiOS6 : UIViewController <SendLogCommandDelegate>
{
    UITextView *textView;
    UIScrollView *_scrollView;
    UIButton *_button;
    SendLogCommand *ftp;
    UIActivityIndicatorView *ftpIndicator;
}

@property(retain, nonatomic) UIActivityIndicatorView *ftpIndicator; // @synthesize ftpIndicator;
- (void)handleSendLogBackgroundComplete;
- (void)handleSendLogCommandOkCancel;
- (void)handleSendLogCommandBackground;
- (void)handleSendLogCommandResume;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)sendLogs:(id)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)getDefaultAutomationScreenName;

@end

