//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSMutableArray;

@interface AppointmentWrapperCache : NSObject
{
    NSMutableArray *appointmentCache;
}

- (void)dealloc;
- (void)log;
- (id)laterAppointment;
- (id)earliestAppointment;
- (id)edgeAppointmentWithDirection:(int)arg1;
- (id)findDisplayDate:(id)arg1 dayDate:(id)arg2 isStart:(BOOL)arg3;
- (id)findAllDayEvents:(id)arg1;
- (id)findAppointmentsForDay:(id)arg1;
- (id)findAppointmentsFrom:(id)arg1 To:(id)arg2;
- (id)content;
- (int)count;
- (void)deleteAppointment:(id)arg1;
- (void)addAppointment:(id)arg1;
- (id)initWithAppointments:(id)arg1;
- (id)init;

@end

