//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSArray, NSLock, NSMutableDictionary, NSMutableSet, NSString, NSThread, NSTimer;

@interface AppStorePolicyManager : NSObject
{
    struct UIAListener *m_listener;
    struct UIAListener *m_webOptionListener;
    id <AppStorePolicyManagerDelegate> delegate;
    BOOL enabled;
    BOOL webEnabled;
    NSString *webTokenUrl;
    NSMutableDictionary *applications;
    NSArray *applicationIndexes;
    NSMutableDictionary *pendingApplications;
    NSMutableSet *errorApplications;
    double retryInterval;
    NSTimer *retryTimer;
    NSThread *metaThread;
    NSLock *threadLock;
}

+ (id)extractValueFromScript:(const char *)arg1 withName:(const char *)arg2;
+ (id)extractTokenFromResponse:(id)arg1 status:(id *)arg2;
@property(retain, nonatomic) NSThread *metaThread; // @synthesize metaThread;
@property(retain, nonatomic) NSTimer *retryTimer; // @synthesize retryTimer;
@property(retain, nonatomic) NSMutableSet *errorApplications; // @synthesize errorApplications;
@property(retain, nonatomic) NSMutableDictionary *pendingApplications; // @synthesize pendingApplications;
@property(retain, nonatomic) NSArray *applicationIndexes; // @synthesize applicationIndexes;
@property(retain, nonatomic) NSMutableDictionary *applications; // @synthesize applications;
@property(retain, nonatomic) NSString *webTokenUrl; // @synthesize webTokenUrl;
@property(readonly, nonatomic) BOOL webEnabled; // @synthesize webEnabled;
@property(readonly, nonatomic) BOOL enabled; // @synthesize enabled;
@property(nonatomic) id <AppStorePolicyManagerDelegate> delegate; // @synthesize delegate;
- (void)enableWeb;
- (void)updateWebTokenUrl;
- (void)onOptionDatabaseNotify:(id)arg1;
- (void)notifyUpdate:(id)arg1;
- (void)notifyRemove:(id)arg1;
- (void)notifyAdd:(id)arg1;
- (void)notifyEnable;
- (void)onAppPolicyDatabaseNotify:(id)arg1;
- (void)removePolicyListener;
- (void)removeOptionsListener;
- (void)removeListeners;
- (void)addPolicyListener;
- (void)addOptionsListener;
- (void)addListeners;
- (void)updateIndexes;
- (void)moveCompletePolicy:(id)arg1;
- (void)updatePendingPolicy:(id)arg1;
- (void)metaThread:(id)arg1;
- (void)setRetryTimer;
- (void)metaThreadMain;
- (void)startMetaThread:(id)arg1;
- (void)removeApplicationPolicy:(unsigned short)arg1;
- (void)addApplicationPolicy:(unsigned short)arg1;
- (void)initApplicationPolicy;
- (BOOL)hasApplication:(id)arg1;
- (id)applicationAtIndex:(unsigned int)arg1;
- (unsigned int)applicationCount;
- (void)dealloc;
- (id)init;

@end

