//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSData, NSString;

@interface BAIBluetoothDevice : NSObject
{
    NSData *address;
    NSString *friendlyName;
}

+ (id)deviceWithAddress:(char *)arg1 length:(unsigned char)arg2;
@property(copy, nonatomic) NSData *address; // @synthesize address;
@property(copy, nonatomic) NSString *friendlyName; // @synthesize friendlyName;
- (void)dealloc;
- (id)displayString;
- (id)addressString;
- (BOOL)isNULLReader;
- (id)init;

@end

