//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

#import "UIUnlockSliderDelegate.h"

@class NSBundle, NSConditionLock, NSMutableData, NSTimer, UIActivityIndicatorView, UIButton, UILabel, UINavigationController, UITextView, UIUnlockSlider, UIView;

@interface BAILoginViewController : UIViewController <UIUnlockSliderDelegate>
{
    UIView *pinBlockedView;
    UIView *pinEntryView;
    UIView *pinFieldView;
    UILabel *pinFieldSubtitleLabel;
    UILabel *pinFieldTitleLabel;
    UIButton *pinFieldClearPinButton;
    UIView *pinFieldViewContainer;
    UIView *numericButtonsPortraitView;
    UIView *numericButtonsLandscapeView;
    UIView *numericButtonsContainerView;
    UITextView *userInstructionsTextView;
    UILabel *connectionMessageLabel;
    UIActivityIndicatorView *connectionActivityIndicator;
    UINavigationController *navController;
    BOOL wasDisplayedModally;
    BOOL viewCanBeDismissed;
    BOOL viewHasBeenDismissed;
    NSTimer *retryDismissTimer;
    BOOL pinIsNeeded;
    BOOL attemptHasFailed;
    NSBundle *bundle;
    BOOL cancelActions;
    struct _opaque_pthread_mutex_t mutex_action_required;
    struct _opaque_pthread_cond_t cond_action_required;
    unsigned char action_required;
    NSMutableData *pinData;
    unsigned char pinLength;
    BOOL pinIsLocked;
    unsigned char pinBuffer[9];
    BOOL isConnecting;
    unsigned char connectOptions;
    unsigned char cardState;
    NSTimer *pinFieldTimer;
    UIUnlockSlider *unlockSlider;
    NSConditionLock *navControllerCondLock;
    CDStruct_c5043657 *baicontext;
}

@property(readonly) NSConditionLock *navControllerCondLock; // @synthesize navControllerCondLock;
@property unsigned char connectOptions; // @synthesize connectOptions;
- (void)UIUnlockSliderValueDidChange:(id)arg1;
- (void)UISliderDidChangeState:(BOOL)arg1;
- (void)connectButtonWasPressed:(id)arg1;
- (void)infoButtonWasPressed:(id)arg1;
- (void)clearPinButtonWasPressed:(id)arg1;
- (void)hidePin;
- (void)numericButtonWasPressed:(id)arg1;
- (void)setKeypadForOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)BAIAccessoryDidDetach;
- (void)BAIAccessoryDidAttach;
- (void)requestNavController;
- (void)BAIConnectionStateChangeNotificationWasObserved:(id)arg1;
- (void)BAIConnectionAttemptStatusChangeNotificationWasObserved:(id)arg1;
- (void)connectionAttemptSucceeded;
- (void)connectionAttemptStarted;
- (void)connectionAttemptFailed;
- (void)dismissWithoutPopping;
- (void)dismiss;
- (void)dismissButtonWasPressed:(id)arg1;
- (void)updateUI;
- (void)pushViewControllerFromMainThread;
- (unsigned char)showPinBlockedDialog;
- (unsigned char)showDialogGetPINAndConnect:(CDStruct_c5043657 *)arg1;
- (unsigned char)showDialogConnectOnly:(CDStruct_c5043657 *)arg1;
- (unsigned char)doSomething:(CDStruct_c5043657 *)arg1;
- (void)setNavigationController:(id)arg1;
- (void)setPinData:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)setConnectionIcon:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

