//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "CalendarEvent.h"

@class CalendarAttendee, NSArray, NSString;

@interface CalendarEventDetail : CalendarEvent
{
    CalendarAttendee *_organizer;
    NSArray *_attendees;
    NSString *_note;
}

@property(retain, nonatomic) NSString *note; // @synthesize note=_note;
@property(retain, nonatomic) NSArray *attendees; // @synthesize attendees=_attendees;
@property(retain, nonatomic) CalendarAttendee *organizer; // @synthesize organizer=_organizer;
- (void)dealloc;

@end

