//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class CalendarOccurrence, NSDate;

@interface CollapseAllDayTiler : NSObject
{
    BOOL _breakAtStart;
    BOOL _breakAtEnd;
    CalendarOccurrence *_occurrence;
    NSDate *_dayStartDate;
    double _duration;
}

@property(nonatomic) BOOL breakAtEnd; // @synthesize breakAtEnd=_breakAtEnd;
@property(nonatomic) BOOL breakAtStart; // @synthesize breakAtStart=_breakAtStart;
@property(retain, nonatomic) NSDate *dayStartDate; // @synthesize dayStartDate=_dayStartDate;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) CalendarOccurrence *occurrence; // @synthesize occurrence=_occurrence;
- (void)dealloc;

@end

