//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface ContactSection : NSObject
{
    NSMutableArray *contactList;
    NSString *sectionTitle;
}

@property(retain, nonatomic) NSString *sectionTitle; // @synthesize sectionTitle;
@property(retain, nonatomic) NSMutableArray *contactList; // @synthesize contactList;
- (void)dealloc;
- (void)dump;
- (void)addContactRecord:(id)arg1;
- (id)initWithTitle:(id)arg1;

@end

