//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray, NSString;

@interface ContactPerson : NSObject <NSCopying>
{
    BOOL isGAL;
    BOOL isNotCompleted;
    NSString *_firstName;
    NSString *_middleName;
    NSString *_lastName;
    NSString *_companyName;
    NSString *_displayName;
    NSMutableArray *_emailAddresses;
    NSString *_sectionTitle;
    int recordID;
    int index;
    BOOL isDistributionList;
    int goodContactId;
    int _folderId;
    BOOL _isContactRTL;
}

@property(nonatomic) int folderId; // @synthesize folderId=_folderId;
@property(nonatomic) int goodContactId; // @synthesize goodContactId;
@property(nonatomic) BOOL isDistributionList; // @synthesize isDistributionList;
@property(retain, nonatomic) NSString *sectionTitle; // @synthesize sectionTitle=_sectionTitle;
@property(nonatomic) int index; // @synthesize index;
@property(nonatomic) int recordID; // @synthesize recordID;
@property(retain, nonatomic) NSMutableArray *emailAddresses; // @synthesize emailAddresses=_emailAddresses;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(nonatomic) BOOL isContactRTL; // @synthesize isContactRTL=_isContactRTL;
@property(retain, nonatomic) NSString *companyName; // @synthesize companyName=_companyName;
@property(retain, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(retain, nonatomic) NSString *middleName; // @synthesize middleName=_middleName;
@property(retain, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(nonatomic) BOOL isNotCompleted; // @synthesize isNotCompleted;
@property(nonatomic) BOOL isGAL; // @synthesize isGAL;
- (void)dump;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)ensureFieldsFilled;
- (void)fillRecordFields;
- (id)initGalWithID:(int)arg1;
- (id)initWithID:(int)arg1;

@end

