//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

#import "UIActionSheetDelegate.h"

@class UISwitch;

@interface ContactsSyncHelper : NSObject <UIActionSheetDelegate>
{
    UISwitch *switchToUpdate;
}

+ (_Bool)disable;
+ (_Bool)enable;
+ (_Bool)isDisabled;
+ (_Bool)isEnabledOnServer;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)dealloc;
- (id)init;
- (void)showActionSheet:(id)arg1 inView:(id)arg2;

@end

