//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GUBubbledTextInputMgr.h"

#import "GoodContactAccessorDelegate.h"

@class ContactDetailsFactory, ContactTypeDownAddressingMatchesTableViewMgr, ContactTypeDownAddressingMgr, NSMutableArray;

@interface ContactBubbledTextInputMgr : GUBubbledTextInputMgr <GoodContactAccessorDelegate>
{
    NSMutableArray *contactDetailsArray;
    ContactDetailsFactory *contactDetailsFactory;
    ContactTypeDownAddressingMgr *typeDownAddressingMgr;
    ContactTypeDownAddressingMatchesTableViewMgr *matchesTableMgr;
    BOOL driveMatchesView;
    BOOL isGalLookupRequested;
}

+ (id)peopleWrapperFromContactDetails:(id)arg1;
+ (id)contactDetailsFromPeopleWrapper:(id)arg1;
@property(nonatomic) BOOL driveMatchesView; // @synthesize driveMatchesView;
@property(nonatomic) ContactTypeDownAddressingMatchesTableViewMgr *matchesTableMgr; // @synthesize matchesTableMgr;
@property(nonatomic) ContactTypeDownAddressingMgr *typeDownAddressingMgr; // @synthesize typeDownAddressingMgr;
@property(retain, nonatomic) ContactDetailsFactory *contactDetailsFactory; // @synthesize contactDetailsFactory;
@property(retain, nonatomic) NSMutableArray *contactDetailsArray; // @synthesize contactDetailsArray;
- (void)submitGalLookupRequest;
- (void)forceEndLookup;
- (void)dumpContactDetails;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (void)galContactsLookupEnded:(BOOL)arg1;
- (void)galContactsLookupStarted;
- (void)galContactsShouldBePublished:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)dealloc;
- (void)bubblePressed:(id)arg1;
- (void)useTypeDownAddressingUsingMgr:(id)arg1 matchesTableMgr:(id)arg2;
- (void)fillFromContactDetailsWithoutBubbles:(id)arg1;
- (void)dehighlightBubble;
- (void)removeBubble:(id)arg1;
- (void)appendContact:(id)arg1 withBubble:(BOOL)arg2;
- (void)ensureContactDetailsFactoryExists;
- (void)appendContactWithEmail:(id)arg1;
- (id)init:(BOOL)arg1;

@end

