//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "RoundedCornerTableViewController.h"

#import "GmmStatusWatcherDelegate.h"
#import "ModalViewControllerDismissDelegate.h"

@interface DetailEmailVC : RoundedCornerTableViewController <ModalViewControllerDismissDelegate, GmmStatusWatcherDelegate>
{
    BOOL m_bViewIsVisible;
}

- (int)shiftUnusedRow:(int)arg1;
- (void)onHTMLEnableChanged:(id)arg1;
- (void)toggleConversationView:(id)arg1;
- (void)onDefaultEncryptionChanged:(id)arg1;
- (void)dismissed:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)lastUpdateChanged;
- (void)needReloadView:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (id)initWithStyle:(int)arg1;
- (void)dealloc;

@end

