//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "RoundedCornerTableViewController.h"

@class CellWithSwitch, ContactsSyncHelper;

@interface DetailContactsVC : RoundedCornerTableViewController
{
    CellWithSwitch *syncWithiPad;
    ContactsSyncHelper *_contactsSyncHelper;
}

@property(retain, nonatomic) CellWithSwitch *syncWithiPad; // @synthesize syncWithiPad;
- (void)dismissSubFolderTVC:(id)arg1;
- (void)onSyncWithiPadChanged;
- (void)updateSwitch;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithStyle:(int)arg1;
- (void)dealloc;

@end

