//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface DFID : NSObject
{
}

+ (id)dfid;
+ (id)dfidRawString;
+ (id)buildRawString;
+ (id)bootTime;
+ (id)carrierInfo;
+ (id)languageList;
+ (id)hasCydia;
+ (id)canOpenApps;
+ (id)diskSpace;
+ (id)getSysInfoByName:(char *)arg1;

@end

