//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UITableViewCell.h"

@class EmailListItem, UIButton, UIImageView, UILabel, UIView;

@interface EmailListItemCell : UITableViewCell
{
    float _defaultNibPreviewLabelHeight;
    BOOL _isInConversation;
    BOOL _showDateAsTime;
    BOOL _isMultiSelectMode;
    BOOL _selectedForDelete;
    BOOL _hasProblemsSendingEmail;
    BOOL _isSmimeEmailSecurityIconEnabled;
    EmailListItem *_emailListItem;
    id <EmailListItemCellDelegate> _delegate;
    UIView *_contentBackgroundView;
    UIView *_containerView;
    UIImageView *_iconImage;
    UIImageView *_icon2;
    UILabel *_subjectLabel;
    UILabel *_nameLabel;
    UILabel *_previewTextLabel;
    UILabel *_dateLabel;
    UIButton *_multiSelectButton;
    UIButton *_deleteButton;
    UIImageView *_numberBubble;
    UIView *_deleteButtonBackView;
}

+ (float)estimatedRowHeight;
@property(nonatomic) UIView *deleteButtonBackView; // @synthesize deleteButtonBackView=_deleteButtonBackView;
@property(retain, nonatomic) UIImageView *numberBubble; // @synthesize numberBubble=_numberBubble;
@property(nonatomic) BOOL isSmimeEmailSecurityIconEnabled; // @synthesize isSmimeEmailSecurityIconEnabled=_isSmimeEmailSecurityIconEnabled;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIButton *multiSelectButton; // @synthesize multiSelectButton=_multiSelectButton;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UILabel *previewTextLabel; // @synthesize previewTextLabel=_previewTextLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *subjectLabel; // @synthesize subjectLabel=_subjectLabel;
@property(retain, nonatomic) UIImageView *icon2; // @synthesize icon2=_icon2;
@property(retain, nonatomic) UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *contentBackgroundView; // @synthesize contentBackgroundView=_contentBackgroundView;
@property(nonatomic) BOOL isInConversation; // @synthesize isInConversation=_isInConversation;
@property(nonatomic) id <EmailListItemCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL hasProblemsSendingEmail; // @synthesize hasProblemsSendingEmail=_hasProblemsSendingEmail;
@property(nonatomic) BOOL selectedForDelete; // @synthesize selectedForDelete=_selectedForDelete;
@property(nonatomic) BOOL isMultiSelectMode; // @synthesize isMultiSelectMode=_isMultiSelectMode;
@property(nonatomic) BOOL showDateAsTime; // @synthesize showDateAsTime=_showDateAsTime;
@property(retain, nonatomic) EmailListItem *emailListItem; // @synthesize emailListItem=_emailListItem;
- (void)setFonts;
- (void)setAccessibilityElements;
- (void)updateCellForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (unsigned int)numberOfItems;
- (void)setNumberOfMessages:(unsigned int)arg1;
- (void)handleEmailSecurityIconSmimePolicyChanged;
- (void)handleEmailSecurityIconUserPreferenceChanged:(id)arg1;
- (void)setMultiSelectMode:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setMultiSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)deleteAction:(id)arg1;
- (void)setSelectForDelete:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)removeAllAnimationsFromView:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)toggleDeleteButtonForRecordNumber:(id)arg1 animated:(BOOL)arg2;
- (void)userDidExposeDeleteButton:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setDefaultTextHighlightColor;
- (void)awakeFromNib;
- (void)removeKVOForEmailListItem:(id)arg1;
- (void)setupKVOForEmailListItem:(id)arg1;
- (void)updateBackgroundColor;
- (void)setupSecurityIcon;
- (void)teardownCommon;
- (void)dealloc;

@end

