//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "RoundedCornerTableViewController.h"

@class NSString, UILabel;

@interface EmailCustomSoundVC : RoundedCornerTableViewController
{
    NSString *_soundsEmailFile;
    NSString *_soundsCalendarFile;
    NSString *warningMessage;
    UILabel *footerLabel;
}

@property(retain, nonatomic) UILabel *footerLabel; // @synthesize footerLabel;
@property(retain, nonatomic) NSString *warningMessage; // @synthesize warningMessage;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)selectSoundSettingCell:(id)arg1 atRow:(int)arg2;
- (int)soundsCalendarIndex;
- (int)soundsEmailIndex;
- (void)configureSoundSettingCell:(id)arg1 forRow:(int)arg2;
- (id)cellIdentifierForRowAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)willResignActive:(id)arg1;
- (void)willDisableCustomSound:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)didReceiveMemoryWarning;
- (void)willForeground:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)updateServerSoundPrefs;
- (void)viewDidLoad;
- (id)initWithStyle:(int)arg1;
- (void)dealloc;

@end

