//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class EmailListItem, NSArray;

@protocol EmailListItemDAOInterface <NSObject>

@optional
- (void)flagEmailsWithRecordNumbers:(NSArray *)arg1 withFlag:(int)arg2;
- (void)flagEmailWithId:(int)arg1 withFlag:(int)arg2;
- (int)getTotalCountForFolderWithId:(int)arg1;
- (int)getUnreadCountForFolderWithId:(int)arg1;
- (void)updateEmailWithId:(int)arg1 withCaveat:(int)arg2;
- (void)updateEmailWithId:(int)arg1 withClassification:(int)arg2;
- (void)updateEmailsWithRecordNumbers:(NSArray *)arg1 toReadStatus:(BOOL)arg2 withFolderId:(int)arg3;
- (void)updateEmailWithId:(int)arg1 toReadStatus:(BOOL)arg2;
- (void)moveEmailsWithIds:(NSArray *)arg1 toFolderId:(int)arg2;
- (void)moveEmailWithId:(int)arg1 toFolderId:(int)arg2;
- (void)deleteAllEmailsInFolderId:(int)arg1;
- (BOOL)deleteEmailsWithIds:(NSArray *)arg1;
- (BOOL)deleteEmailWithId:(int)arg1;
- (void)batchLoadEmailListItemsWithFolderId:(int)arg1 filterSortPreset:(int)arg2 callback:(void (^)(NSArray *, int))arg3;
- (NSArray *)findEmailListItemsWithFolderId:(int)arg1;
- (EmailListItem *)findEmailListItemWithId:(int)arg1;
- (void *)getNewlyArrivedEmailInfo;
@end

