//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@class UIButton;

@interface EmailAttachmentButton : UIView
{
    UIButton *_buttonFunctionality;
    UIButton *_buttonBadge;
}

@property(retain, nonatomic) UIButton *buttonFunctionality; // @synthesize buttonFunctionality=_buttonFunctionality;
@property(retain, nonatomic) UIButton *buttonBadge; // @synthesize buttonBadge=_buttonBadge;
- (void)dealloc;

@end

