//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSArray, NSString;

@interface EMLObject : NSObject
{
    NSString *emlString;
}

+ (id)EMLObjectFromString:(id)arg1;
@property(retain, nonatomic) NSString *emlString; // @synthesize emlString;
- (void)dealloc;
@property(readonly, nonatomic) NSString *receivedDateString;
@property(readonly, nonatomic) NSString *subject;
@property(readonly, nonatomic) NSString *plainTextBody;
- (id)bodyPartsFromString:(id)arg1;
@property(readonly, nonatomic) NSArray *from;
@property(readonly, nonatomic) NSArray *bcc;
@property(readonly, nonatomic) NSArray *cc;
@property(readonly, nonatomic) NSArray *to;
- (id)getStringTillEndOfLineFromIndex:(int)arg1 usingString:(id)arg2;

@end

