//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

#import "GMMLatencyObserver.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIWebViewDelegate.h"

@class DocumentsInfoViewController, NSOperationQueue, NSString, UIActionSheet, UIView, UIWebView;

@interface FileViewer : UIViewController <UIWebViewDelegate, UIAlertViewDelegate, UIActionSheetDelegate, GMMLatencyObserver>
{
    UIWebView *_webView;
    UIView *_loadingView;
    NSOperationQueue *_latencyCheckQueue;
    double _lastMainRunLoopExecution;
    BOOL _checkingLatency;
    NSString *_URL;
    id <FileViewerDelegate> _fileViewerDelegate;
    BOOL disappearing;
    int memoryAlertCount;
    UIActionSheet *_currentActionSheet;
    BOOL _fileOpenedFromAttachmentManager;
    BOOL _onlyForAttachments;
    NSString *_nonSupportMessage;
    DocumentsInfoViewController *_nonSupportedDocument;
    BOOL _isArchiveEntry;
    id <SourceDataProtocol> source;
    int attachmentID;
}

@property(nonatomic) BOOL isArchiveEntry; // @synthesize isArchiveEntry=_isArchiveEntry;
@property(retain, nonatomic) DocumentsInfoViewController *nonSupportedDocument; // @synthesize nonSupportedDocument=_nonSupportedDocument;
@property(copy, nonatomic) NSString *nonSupportMessage; // @synthesize nonSupportMessage=_nonSupportMessage;
@property(nonatomic) BOOL fileOpenedFromAttachmentManager; // @synthesize fileOpenedFromAttachmentManager=_fileOpenedFromAttachmentManager;
@property(nonatomic) BOOL onlyForAttachments; // @synthesize onlyForAttachments=_onlyForAttachments;
@property(retain, nonatomic) UIActionSheet *currentActionSheet; // @synthesize currentActionSheet=_currentActionSheet;
@property(nonatomic) int attachmentID; // @synthesize attachmentID;
@property(retain, nonatomic) id <SourceDataProtocol> source; // @synthesize source;
@property(nonatomic) id <FileViewerDelegate> fileViewerDelegate; // @synthesize fileViewerDelegate=_fileViewerDelegate;
@property(retain, nonatomic) NSString *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)openWithAction:(id)arg1;
- (void)close;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)fixWebViewZoom:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)dealloc;
- (void)alertLowMemory;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)memoryWarningReceived:(id)arg1;
- (void)dismissSelfAnimated:(BOOL)arg1;
- (void)showAttachmentActionSheet;
- (void)setRightButtonItem;
- (void)refreshFileViewer:(id)arg1;
- (void)viewDidLoad;
- (void)didDraw;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)stopWebView;
- (void)highLatencyObserved;
- (void)stopActivityIndicator;
- (void)startActivityIndicator;
- (id)getDefaultAutomationScreenName;

@end

