//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class FilteredCache, NSArray, NSIndexSet, NSMutableArray;

@protocol FilteredCacheFilter <NSObject>
- (BOOL)insertionIndexPathOfObject:(id)arg1 indexPath:(id *)arg2 inCache:(FilteredCache *)arg3;
- (NSMutableArray *)filterCache:(NSMutableArray *)arg1;

@optional
- (BOOL)shouldReorderObjects;
- (BOOL)shouldReEvaluateObjects;
- (void)didRemoveEmptySections:(NSArray *)arg1;
- (BOOL)shouldRemoveEmptySections;
- (NSIndexSet *)insertSectionsForObjects:(NSArray *)arg1 inCache:(FilteredCache *)arg2;
@end

