//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

@class UISwitch, UITextView;

@interface FlipsideViewController : UIViewController
{
    id <FlipsideViewControllerDelegate> delegate;
    id <FlipsideViewControllerDelegate> delegate2;
    id <FlipsideViewControllerDelegate> delegate_gdp_ping;
    id <FlipsideViewControllerDelegate> delegate_remora;
    id <FlipsideViewControllerDelegate> delegate_radio_switch;
    UISwitch *radioSwitch;
    UITextView *logOutputTextView;
}

@property(retain, nonatomic) UITextView *logOutputTextView; // @synthesize logOutputTextView;
@property(nonatomic) id <FlipsideViewControllerDelegate> delegate_radio_switch; // @synthesize delegate_radio_switch;
@property(nonatomic) id <FlipsideViewControllerDelegate> delegate_remora; // @synthesize delegate_remora;
@property(nonatomic) id <FlipsideViewControllerDelegate> delegate_gdp_ping; // @synthesize delegate_gdp_ping;
@property(nonatomic) id <FlipsideViewControllerDelegate> delegate2; // @synthesize delegate2;
@property(retain, nonatomic) UISwitch *radioSwitch; // @synthesize radioSwitch;
@property(nonatomic) id <FlipsideViewControllerDelegate> delegate; // @synthesize delegate;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)done2;
- (void)run_radio_switch;
- (void)run_remora;
- (void)run_gdp_ping;
- (void)done:(id)arg1;
- (void)viewDidLoad;

@end

