//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

@class FolderViewData;

@protocol FolderViewDataDelegate
- (void)folderViewDataDidFinishSearching:(FolderViewData *)arg1;
- (void)folderViewDataDidBeginSearching:(FolderViewData *)arg1;
- (void)folderViewDataEmailReceivedInCurFolder;
- (void)folderViewData:(FolderViewData *)arg1 didUpdateManifest:(BOOL)arg2;
- (void)folderViewData:(FolderViewData *)arg1 didSetFolderType:(int)arg2;
- (void)folderViewData:(FolderViewData *)arg1 didUpdateUnreadCount:(int)arg2;
@end

