//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"

@class CellWithSlider, UILabel;

@interface FontSizeViewController : UIViewController <UITableViewDataSource>
{
    UILabel *instructionsLabel;
    UILabel *sampleTextLabel;
    CellWithSlider *cellWithSlider;
}

+ (void)load;
+ (id)defaultContentSize;
@property(retain, nonatomic) CellWithSlider *cellWithSlider; // @synthesize cellWithSlider;
@property(retain, nonatomic) UILabel *sampleTextLabel; // @synthesize sampleTextLabel;
@property(retain, nonatomic) UILabel *instructionsLabel; // @synthesize instructionsLabel;
- (void)dealloc;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)slidingEnded:(id)arg1;
- (void)onSliderAction:(id)arg1;
- (BOOL)shouldAutorotate;
- (void)viewDidLoad;
- (int)sliderValueForContentSizeCategory:(id)arg1;
- (id)contentSizeCategoryForSliderValue:(float)arg1;

@end

