//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

@class GCDAsyncSocket, NSData, NSError, NSString;

@protocol GCDAsyncSocketDelegate

@optional
- (void)socketDidSecure:(GCDAsyncSocket *)arg1;
- (void)socketDidDisconnect:(GCDAsyncSocket *)arg1 withError:(NSError *)arg2;
- (void)socketDidCloseReadStream:(GCDAsyncSocket *)arg1;
- (double)socket:(GCDAsyncSocket *)arg1 shouldTimeoutWriteWithTag:(long)arg2 elapsed:(double)arg3 bytesDone:(unsigned int)arg4;
- (double)socket:(GCDAsyncSocket *)arg1 shouldTimeoutReadWithTag:(long)arg2 elapsed:(double)arg3 bytesDone:(unsigned int)arg4;
- (void)socket:(GCDAsyncSocket *)arg1 didWritePartialDataOfLength:(unsigned int)arg2 tag:(long)arg3;
- (void)socket:(GCDAsyncSocket *)arg1 didWriteDataWithTag:(long)arg2;
- (void)socket:(GCDAsyncSocket *)arg1 didReadPartialDataOfLength:(unsigned int)arg2 tag:(long)arg3;
- (void)socket:(GCDAsyncSocket *)arg1 didReadData:(NSData *)arg2 withTag:(long)arg3;
- (void)socket:(GCDAsyncSocket *)arg1 didConnectToHost:(NSString *)arg2 port:(unsigned short)arg3;
- (void)socket:(GCDAsyncSocket *)arg1 didAcceptNewSocket:(GCDAsyncSocket *)arg2;
- (struct dispatch_queue_s *)newSocketQueueForConnectionFromAddress:(NSData *)arg1 onSocket:(GCDAsyncSocket *)arg2;
@end

