//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSThread.h"

@interface GCFHTTPTransactorThread : NSThread
{
    struct GHTTPTransactor *m_httpTransactor;
    BOOL inited;
}

@property BOOL inited; // @synthesize inited;
- (void)doResetAuthCache;
- (void)resetAuthCache;
- (void)doGracefulShutdown;
- (void)gracefulShutdown;
- (void)onAbortCurrentRequestBasedOnId:(id)arg1;
- (void)onAbortCurrentProcessingAndFlushPoolsWithParams:(id)arg1;
- (void)onSignal:(id)arg1;
- (void)signalEvent:(id)arg1 withParam:(id)arg2;
- (void)main;
- (void)mainLoop;
- (void)abortCurrentRequestBasedOnId:(unsigned long)arg1 callbackObject:(id)arg2;
- (void)abortCurrentProcessingAndFlushPoolsWithCallback:(id)arg1 disconnectConstantConnection:(BOOL)arg2 disconnectSBProxy:(BOOL)arg3 blocking:(BOOL)arg4;
- (void)abortCurrentProcessing:(id)arg1;
- (void)dealloc;
- (id)initWithHttpTransactor:(struct GHTTPTransactor *)arg1;

@end

