//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSHTTPURLResponse.h"

@class NSMutableDictionary;

@interface GCustomHttpUrlResponse : NSHTTPURLResponse
{
    NSMutableDictionary *customHeaders;
    int customStatusCode;
}

@property(retain, nonatomic) NSMutableDictionary *customHeaders; // @synthesize customHeaders;
- (int)statusCode;
- (void)setStatusCode:(int)arg1;
- (void)setHeaderField:(id)arg1 value:(id)arg2;
- (void)ensureHeadersDictExists;
- (void)setAllHeaderFields:(id)arg1;
- (id)allHeaderFields;
- (id)initWithHttpResponse:(struct GCFHTTPResponse *)arg1 resourceDesc:(const struct SBResourceDesc *)arg2 originalUrl:(id)arg3 redirectUrl:(id)arg4;
- (id)initWithURL:(id)arg1 MIMEType:(id)arg2 expectedContentLength:(int)arg3 textEncodingName:(id)arg4 statusCode:(int)arg5;
- (void)dealloc;

@end

