//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSString;

@interface GeoCoderHistory : NSObject
{
    struct sqlite3 *db;
    NSString *address;
    NSString *coordinates;
    int deletionDate;
}

+ (id)instance;
@property(nonatomic) int deletionDate; // @synthesize deletionDate;
@property(copy, nonatomic) NSString *coordinates; // @synthesize coordinates;
@property(copy, nonatomic) NSString *address; // @synthesize address;
@property(nonatomic) struct sqlite3 *db; // @synthesize db;
- (void)dealloc;
- (void)computeDeletionDate;
- (void)dumpGeoCoderHistory;
- (void)clearGeoCoderHistory;
- (BOOL)deleteGeoCoderHistory;
- (BOOL)updateGeoCoderHistory;
- (BOOL)addGeoCoderHistory;
- (BOOL)getGeoCoderHistory;
- (id)startup;
- (BOOL)createOrUpdateSchema;

@end

