//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIApplication.h"

#import "UIActionSheetDelegate.h"

@class CTTelephonyNetworkInfo, NSMutableSet, NSOperationQueue, NSString;

@interface GMMApplication : UIApplication <UIActionSheetDelegate>
{
    NSString *_callNumber;
    NSOperationQueue *_latencyCheckQueue;
    NSMutableSet *_latencyObservers;
    double _lastMainRunLoopExecution;
    BOOL _checkingLatency;
    CTTelephonyNetworkInfo *networkInfo;
}

+ (id)keychainIdentifier;
+ (id)uniqueApplicationIdentifierForDisplay;
+ (id)uniqueApplicationIdentifier;
+ (BOOL)restoreUDRFileFromKeyChain;
+ (id)getAppLongName;
+ (BOOL)didOpenGoodShareLink:(id)arg1;
+ (BOOL)goodShareLinkSupportedForURL:(id)arg1 applicationIdentifier:(id *)arg2 minimumVersion:(id *)arg3;
+ (BOOL)isSDKApp;
+ (BOOL)isRetina;
+ (id)instance;
@property(retain, nonatomic) CTTelephonyNetworkInfo *networkInfo; // @synthesize networkInfo;
@property(readonly) double mainThreadLatency;
- (void)updateMainThreadLatency;
- (void)removeLatencyObserver:(id)arg1;
- (void)checkLatency;
- (void)addLatencyObserver:(id)arg1;
- (void)dealloc;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (BOOL)openExternalURL:(id)arg1;
- (BOOL)openURL:(id)arg1;
- (void)updateCarrierInformationOnServer;
- (void)updateCarrierInformationIfNeeded;
- (void)beginCarrierDetection;

@end

