//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface GmmEmailDebugHelper : NSObject
{
}

+ (void)removeRandomEmailsFromInbox:(int)arg1 withDelay:(double)arg2;
+ (void)removeRandomEmailsFromInbox:(int)arg1;
+ (void)generateRandomEmailInEmailFolder:(int)arg1 contactArray:(id)arg2;
+ (void)generateRandomEmailsInEmailFolder:(int)arg1 count:(int)arg2 contactArray:(id)arg3 withDelay:(double)arg4;
+ (id)randomContactStringsFromContactArray:(id)arg1 count:(int)arg2;
+ (id)randomContactStringFromContactArray:(id)arg1;
+ (id)randomContactFromContactArray:(id)arg1;
+ (int)randomIntegerLessThan:(int)arg1;
+ (struct AnEmail *)keyValueStringDataToAnEmail:(id)arg1;
+ (BOOL)yesNoFromString:(id)arg1;
+ (int)msgImportanceFromString:(id)arg1;
+ (void)fillEmailRecipient:(struct AnEmailRecipient *)arg1 fromRecipientWrapper:(id)arg2;
+ (id)recipientFromString:(id)arg1;
+ (void)addXmlEmailsToDbFromFile:(id)arg1 intoEmailFolder:(int)arg2;
- (void)invokeRemoveRandomEmailFromInbox:(id)arg1;
- (void)invokeGenerateRandomEmailInEmailFolder:(id)arg1;

@end

