//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GmmService.h"

@interface GmmOpenHttpUrlService : GmmService
{
}

+ (id)instance;
+ (void)initialize;
- (void)openBrowserUsingApplication:(id)arg1;
- (void)openUrl:(id)arg1 usingApplication:(id)arg2;
- (void)openUrl:(id)arg1 usingApplicationWithName:(id)arg2;
- (id)init;

@end

