//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class UIButton, UILabel, UITextField;

@interface GMMPhoneNumberRegistrationVC : UIViewController <UITextFieldDelegate>
{
    BOOL fieldAutoChanged;
    UITextField *phoneNumberField;
    UIButton *okButton;
    UILabel *infoTitleLabel;
    UILabel *infoDetailLabel;
    UILabel *ipadInstructionLabel;
}

+ (BOOL)validatePhoneNumber:(id)arg1;
+ (id)phoneNumberFromTextField:(id)arg1;
+ (id)formattedPhoneNumber;
+ (BOOL)phoneNumberTextField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
+ (void)setPhoneNumber:(id)arg1;
+ (id)phoneNumber;
+ (void)presentRegisterVCIfRequired;
+ (id)viewController;
+ (BOOL)isCurrentPhoneNumberValid;
+ (BOOL)isPhoneNumberValid:(id)arg1;
+ (BOOL)deviceRequiresValidPhoneNumber;
+ (BOOL)deviceRequiresValidPhoneNumberWithPolicy:(id)arg1;
+ (BOOL)isPhoneNumberRegistrationRequired;
+ (void)movePolicy;
+ (void)updatePolicy;
+ (id)phoneRegistrationPolicy;
+ (void)fetchAndStorePhoneVerificationJSON;
+ (BOOL)isCellularReachable;
@property(nonatomic) BOOL fieldAutoChanged; // @synthesize fieldAutoChanged;
@property(retain, nonatomic) UILabel *ipadInstructionLabel; // @synthesize ipadInstructionLabel;
@property(retain, nonatomic) UILabel *infoDetailLabel; // @synthesize infoDetailLabel;
@property(retain, nonatomic) UILabel *infoTitleLabel; // @synthesize infoTitleLabel;
@property(retain, nonatomic) UIButton *okButton; // @synthesize okButton;
@property(retain, nonatomic) UITextField *phoneNumberField; // @synthesize phoneNumberField;
- (void)submit:(id)arg1;
- (void)setupLocalizedScreenText;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidLoad;
- (void)dealloc;
- (void)releaseIBOutlets;
- (id)init;
- (id)getDefaultAutomationScreenName;

@end

