//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GmmService.h"

@interface GmmSaveFilesService : GmmService
{
}

+ (id)instance;
+ (void)initialize;
- (id)availableApplications;
- (void)removeUnpermittedApplicationsFrom:(id)arg1;
- (void)sendSaveFilesRequestToApplicationWithId:(id)arg1 andFileNames:(id)arg2;
- (void)saveFiles:(id)arg1 toApplication:(id)arg2;
- (void)saveFiles:(id)arg1 toApplicationWithName:(id)arg2;
- (id)init;

@end

