//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface GMMTask : NSObject
{
    unsigned short _recordNumber;
    struct ATaskRecord *_taskRecord;
    BOOL _isNewTask;
}

@property(readonly, nonatomic) struct ATaskRecord *taskRecord; // @synthesize taskRecord=_taskRecord;
@property(nonatomic) unsigned short recordNumber; // @synthesize recordNumber=_recordNumber;
- (void)setTaskNotes:(id)arg1;
- (id)taskNotes;
- (void)setTaskSubject:(id)arg1;
- (id)taskSubject;
- (void)setTaskComplete:(BOOL)arg1;
- (BOOL)taskComplete;
- (void)setTaskReminderSet:(BOOL)arg1;
- (BOOL)taskReminderSet;
- (void)setTaskPercent:(int)arg1;
- (int)taskPercent;
- (void)setTaskStatus:(int)arg1;
- (int)taskStatus;
- (void)setTaskPriority:(int)arg1;
- (int)taskPriority;
- (void)setTaskVersion:(int)arg1;
- (int)taskVersion;
- (void)setTaskHostId:(int)arg1;
- (int)taskHostId;
- (void)setReminderDate:(id)arg1;
- (id)reminderDate;
- (void)setCompletedDate:(id)arg1;
- (id)completedDate;
- (void)setStartDate:(id)arg1;
- (id)startDate;
- (void)setDueDate:(id)arg1;
- (id)dueDate;
- (BOOL)recordIsDirty;
- (void)updateRecordInDB;
- (void)refreshTaskRecord;
- (void)dealloc;
- (void)save;
- (void)update;
- (id)initWithRecordNumber:(unsigned short)arg1;
- (id)init;

@end

