//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class FilteredCache, GTAllDayView, GTEventBubble;

@protocol GTAllDayViewDelegate <NSObject>

@optional
- (void)allDayView:(GTAllDayView *)arg1 willRemoveFilteredCache:(FilteredCache *)arg2;
- (void)allDayView:(GTAllDayView *)arg1 didTouchBubble:(GTEventBubble *)arg2;
- (void)allDayView:(GTAllDayView *)arg1 didChangeFrame:(struct CGRect)arg2;
@end

