//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@interface GTArrowView : UIView
{
    struct CGGradient *_arrowGradient;
}

+ (id)arrowInFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGGradient *arrowGradient; // @synthesize arrowGradient=_arrowGradient;
- (float)searchBarHeightForPullToRefresh;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawArrowInRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

