//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GTCalendarViewController.h"

@interface GTCalendarViewController_iPhone : GTCalendarViewController
{
}

- (void)addNewEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)didSelectModule:(id)arg1 atIndex:(int)arg2;
- (void)setupBarButtonItems;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

