//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UITableViewController.h"

#import "FilteredCacheDelegate.h"
#import "GTCalendarViewControllerModule.h"

@class CalendarOccurrence, FilteredCache, GTCalendarLoadingView, NSDate, NSOperationQueue;

@interface GTCalendarInfiniteListViewController : UITableViewController <FilteredCacheDelegate, GTCalendarViewControllerModule>
{
    BOOL _disableScrollHandler;
    int _loadingState;
    NSDate *_selectedDate;
    FilteredCache *_activeFilteredCache;
    id <GTCalendarViewDataSource> _viewDataSourceDelegate;
    id <GTDataLoadingProtocol> _dataLoadingDelegate;
    id <GTCalendarViewControllerDelegate> _controlDelegate;
    NSOperationQueue *_dataLoadingQueue;
    GTCalendarLoadingView *_tableHeaderLoadingView;
    GTCalendarLoadingView *_tableFooterLoadingView;
    CalendarOccurrence *_selectedCalendarOccurrence;
}

+ (void)initialize;
@property(retain, nonatomic) CalendarOccurrence *selectedCalendarOccurrence; // @synthesize selectedCalendarOccurrence=_selectedCalendarOccurrence;
@property(nonatomic) BOOL disableScrollHandler; // @synthesize disableScrollHandler=_disableScrollHandler;
@property(retain, nonatomic) GTCalendarLoadingView *tableFooterLoadingView; // @synthesize tableFooterLoadingView=_tableFooterLoadingView;
@property(retain, nonatomic) GTCalendarLoadingView *tableHeaderLoadingView; // @synthesize tableHeaderLoadingView=_tableHeaderLoadingView;
@property(retain, nonatomic) NSOperationQueue *dataLoadingQueue; // @synthesize dataLoadingQueue=_dataLoadingQueue;
@property(nonatomic) id <GTCalendarViewControllerDelegate> controlDelegate; // @synthesize controlDelegate=_controlDelegate;
@property(nonatomic) id <GTDataLoadingProtocol> dataLoadingDelegate; // @synthesize dataLoadingDelegate=_dataLoadingDelegate;
@property(nonatomic) id <GTCalendarViewDataSource> viewDataSourceDelegate; // @synthesize viewDataSourceDelegate=_viewDataSourceDelegate;
@property(retain, nonatomic) FilteredCache *activeFilteredCache; // @synthesize activeFilteredCache=_activeFilteredCache;
@property(retain, nonatomic) NSDate *selectedDate; // @synthesize selectedDate=_selectedDate;
@property(nonatomic) int loadingState; // @synthesize loadingState=_loadingState;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)willUpdateFilteredCache:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)filteredCache:(id)arg1 didUpdateRowsAtIndexPaths:(id)arg2;
- (void)filteredCache:(id)arg1 didRemoveRowsAtIndexPaths:(id)arg2;
- (void)filteredCache:(id)arg1 didAddRowsAtIndexPaths:(id)arg2;
- (void)filteredCache:(id)arg1 didRemoveSectionsAtIndexes:(id)arg2;
- (void)filteredCache:(id)arg1 didAddSectionsAtIndexes:(id)arg2;
- (void)scrollToSelectedDate;
- (void)snapToLastPositionOfOccurrence:(id)arg1 pointOffsetY:(float)arg2 allDayDate:(id)arg3;
- (id)lastAllDayDateForOccurrence:(id)arg1 loadingState:(int)arg2 cell:(id)arg3;
- (void)scrollToLastCellWithLoadingState:(int)arg1 block:(CDUnknownBlockType)arg2;
- (void)didInitiallyLoadDataForFilteredCache:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)handleOrientationChangeWithPopover:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)stopLoadingOccurrences;
- (void)loadFilteredCacheFromStartDate:(id)arg1 minResults:(int)arg2 shouldLoadBefore:(BOOL)arg3 cacheDelegate:(id)arg4;
- (void)startLoadingNextOccurrences;
- (void)startLoadingPreviousOccurrences;
- (BOOL)isLoadingState:(int)arg1;
- (void)contentSizeCategoryDidChange;
- (void)timeZoneChanged;
- (void)didReceiveMemoryWarning;
- (struct CGRect)tableHeaderFooterFrame;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)offsetToTopOfTableView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)getDefaultAutomationScreenName;
- (id)initWithViewDataSourceDelegate:(id)arg1 dataLoadingDelegate:(id)arg2 controlDelegate:(id)arg3;
- (void)dealloc;

@end

