//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@class NSDate, UIImageView;

@interface GTCalendarWeekStripDayView : UIView
{
    NSDate *_date;
    BOOL _isSelected;
    BOOL _isCurrentDay;
    int _topCapHeight;
    int _leftCapWidth;
    UIImageView *nameOfDayImageView;
    UIImageView *dayOfMonthImageView;
    UIImageView *selectedDateBackgroundView;
}

+ (id)selectedDayIconForCalendarInRect:(struct CGRect)arg1 withDay:(id)arg2 withFontSize:(float)arg3 andColor:(id)arg4;
+ (id)iconForCalendarInRect:(struct CGRect)arg1 withDay:(id)arg2 withFontSize:(float)arg3 andColor:(id)arg4;
+ (void)drawShadowedText:(id)arg1 inRect:(struct CGRect)arg2 withColor:(id)arg3 withFontSize:(float)arg4;
+ (struct CGImage *)createMaskWithSize:(struct CGSize)arg1 shape:(CDUnknownBlockType)arg2;
+ (id)blackSquareOfSize:(struct CGSize)arg1;
@property(retain, nonatomic) UIImageView *selectedDateBackgroundView; // @synthesize selectedDateBackgroundView;
@property(retain, nonatomic) UIImageView *dayOfMonthImageView; // @synthesize dayOfMonthImageView;
@property(retain, nonatomic) UIImageView *nameOfDayImageView; // @synthesize nameOfDayImageView;
- (id)weekNameAndDayOfMonthForVoiceOver;
- (void)updateAccessibilityValue;
- (void)updateAccessibilityLabel;
@property(retain, nonatomic) NSDate *date;
- (void)updateCurrentDay;
@property(nonatomic) BOOL isSelected;
@property(readonly, nonatomic) BOOL isCurrentDay;
- (void)tapped:(id)arg1;
- (void)redrawLabelImage;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

