//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "DataSourceCache.h"

@class NSDate, NSMutableArray, NSMutableDictionary, NSOperationQueue;

@interface GTCalendarDataSourceCache : DataSourceCache
{
    struct dispatch_source_s *_purgeTimer;
    BOOL _cacheTodayBuckets;
    NSMutableArray *_mainCache;
    id _caches;
    id <GTDataLoadingProtocol> _delegate;
    NSMutableDictionary *_bucketDictionary;
    NSDate *_recentFilteredCacheStartDate;
    NSDate *_recentFilteredCacheEndDate;
    NSOperationQueue *_fcRemovalOperationQueue;
}

@property(retain, nonatomic) NSOperationQueue *fcRemovalOperationQueue; // @synthesize fcRemovalOperationQueue=_fcRemovalOperationQueue;
@property(retain, nonatomic) NSDate *recentFilteredCacheEndDate; // @synthesize recentFilteredCacheEndDate=_recentFilteredCacheEndDate;
@property(retain, nonatomic) NSDate *recentFilteredCacheStartDate; // @synthesize recentFilteredCacheStartDate=_recentFilteredCacheStartDate;
@property(retain, nonatomic) NSMutableDictionary *bucketDictionary; // @synthesize bucketDictionary=_bucketDictionary;
@property(nonatomic) id <GTDataLoadingProtocol> delegate; // @synthesize delegate=_delegate;
- (id)caches;
- (id)mainCache;
@property(nonatomic) BOOL cacheTodayBuckets; // @synthesize cacheTodayBuckets=_cacheTodayBuckets;
- (void)addBuckets:(id)arg1 withOccurrences:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
- (id)loadBucketDataForStartDate:(id)arg1;
- (id)createBucketAndLoadDataForDate:(id)arg1;
- (void)markOrLoadBucketAsActiveForStartDate:(id)arg1 endDate:(id)arg2;
- (float)getPercentInactiveBuckets;
- (BOOL)hasBucketsInRangeOfCalendarOccurrence:(id)arg1;
- (void)purgeAllInactiveData;
- (void)handleLowMemoryWarning:(id)arg1;
- (void)removeInactiveBucketDataForBuckets:(id)arg1;
- (void)removeInactiveBuckets;
- (void)markRecentFilteredCacheBucketsActive;
- (void)markTodayPlusMinusOneBucketActive;
- (void)updateMainCacheBuckets;
- (void)addOrReplaceObjects:(id)arg1;
- (void)deleteAllFilteredCaches;
- (void)clearMainCache;
- (void)cancelDataLoadForInactiveBuckets;
- (void)deleteFilteredCache:(id)arg1;
- (void)deleteFilteredCacheWithKey:(id)arg1;
- (id)createCacheWithFilter:(id)arg1 delegate:(id)arg2 filteredCacheClass:(Class)arg3;
- (id)createCacheWithFilter:(id)arg1 delegate:(id)arg2;
- (id)createOrOverwriteCacheWithKey:(id)arg1 delegate:(id)arg2 filter:(id)arg3 filteredCacheClass:(Class)arg4;
- (id)createOrOverwriteCacheWithKey:(id)arg1 delegate:(id)arg2 filter:(id)arg3;
- (void)enumerateCacheDateRangeUsingBlock:(CDUnknownBlockType)arg1;
- (void)removeCalendarOccurrencesWithRecordId:(unsigned int)arg1 andNotInArray:(id)arg2 startDate:(id)arg3 endDate:(id)arg4;
- (void)removeAllCalendarOccurrencesWithRecordId:(unsigned int)arg1;
- (void)setupDataSourceCache;
- (id)initWithDataLoadingDelegate:(id)arg1;
- (void)dealloc;

@end

