//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSDate, NSOperation;

@protocol GTDataLoadingProtocol <NSObject>
- (void)loadDataForDay:(NSDate *)arg1 operation:(NSOperation *)arg2 callback:(void (^)(void))arg3;
- (void)loadDataForMonth:(NSDate *)arg1 operation:(NSOperation *)arg2 callback:(void (^)(void))arg3;
- (void)loadFilteredCacheFromStartDate:(NSDate *)arg1 minResults:(int)arg2 shouldLoadBefore:(BOOL)arg3 operation:(NSOperation *)arg4 cacheDelegate:(id <FilteredCacheDelegate>)arg5 prepareForSwapCallback:(void (^)(void))arg6;
- (void)cancelLoadingFromStartDate:(NSDate *)arg1 toEndDate:(NSDate *)arg2 sender:(id)arg3 completionBlock:(void (^)(NSDate *, NSDate *, BOOL))arg4;
- (void)startLoadingCalendarOccurrencesFromStartDate:(NSDate *)arg1 toEndDate:(NSDate *)arg2 sender:(id)arg3 completionBlock:(void (^)(NSDate *, NSDate *, NSArray *, BOOL))arg4;
@end

