//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSString;

@interface GTICCServiceRequest : NSObject
{
    NSString *reqB64Data;
    int reqType;
}

@property(nonatomic) int reqType; // @synthesize reqType;
@property(retain, nonatomic) NSString *reqB64Data; // @synthesize reqB64Data;
- (BOOL)setReqPlainData:(id)arg1;
- (id)initWithPlainData:(id)arg1 andService:(int)arg2;
- (void)dealloc;

@end

