//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GTInfiniteScrollDatePickerCell.h"

#import "GTInfiniteScrollDatePickerCellDataSource.h"

@class NSDateFormatter, NSMutableArray;

@interface GTInfiniteScrollDatePickerYearCell : GTInfiniteScrollDatePickerCell <GTInfiniteScrollDatePickerCellDataSource>
{
    NSMutableArray *_dates;
    NSMutableArray *_tiles;
    NSDateFormatter *_yearFormatter;
    NSDateFormatter *_monthFormatter;
}

@property(retain, nonatomic) NSDateFormatter *monthFormatter; // @synthesize monthFormatter=_monthFormatter;
@property(retain, nonatomic) NSDateFormatter *yearFormatter; // @synthesize yearFormatter=_yearFormatter;
@property(retain, nonatomic) NSMutableArray *tiles; // @synthesize tiles=_tiles;
@property(retain, nonatomic) NSMutableArray *dates; // @synthesize dates=_dates;
- (void)didSelectTile:(id)arg1;
- (void)selectDate:(id)arg1;
- (BOOL)datePickerSelectsOnTapAndHold:(id)arg1;
- (float)headerHeightForDatePicker:(id)arg1;
- (id)headerViewForDatePicker:(id)arg1;
- (int)numberOfRowsInDatePicker:(id)arg1;
- (int)numberOfColumnsInDatePicker:(id)arg1;
- (id)datePicker:(id)arg1 tileForItemAtIndexPath:(id)arg2;
- (void)updateModel;
- (void)setDate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

