//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIScrollView.h"

@class GTRecycleItemsQueue, NSMutableArray, UIView;

@interface GTInfiniteScrollView : UIScrollView
{
    BOOL _recentersView;
    int _style;
    NSMutableArray *_visibleViews;
    GTRecycleItemsQueue *_recycleViewsQueue;
    UIView *_scrollContainer;
    id <GTInfiniteScrollViewDataSource> _dataSource;
}

@property(nonatomic) id <GTInfiniteScrollViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) BOOL recentersView; // @synthesize recentersView=_recentersView;
@property(retain, nonatomic) UIView *scrollContainer; // @synthesize scrollContainer=_scrollContainer;
@property(retain, nonatomic) GTRecycleItemsQueue *recycleViewsQueue; // @synthesize recycleViewsQueue=_recycleViewsQueue;
@property(retain, nonatomic) NSMutableArray *visibleViews; // @synthesize visibleViews=_visibleViews;
@property(nonatomic) int style; // @synthesize style=_style;
- (id)insertViewAtIndex:(int)arg1;
- (float)maxEdgeOfFrame:(struct CGRect)arg1;
- (struct CGRect)frameWithSize:(struct CGSize)arg1 afterEdge:(float)arg2;
- (float)minEdgeOfFrame:(struct CGRect)arg1;
- (struct CGRect)frameWithSize:(struct CGSize)arg1 beforeEdge:(float)arg2;
- (void)placeNewViewWithIndex:(int)arg1 atFrame:(struct CGRect)arg2 isPrev:(BOOL)arg3;
- (void)reuseCell:(id)arg1;
- (void)tileViewsInVisibleBounds:(struct CGRect)arg1;
- (void)recenterIfNecessary;
- (BOOL)isVerticalStyle;
- (BOOL)isHorizontalStyle;
- (float)maxContentSize;
- (void)setContentSize:(struct CGSize)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)dequeueRecycleItemWithIdentifier:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2 recentersView:(BOOL)arg3;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (void)dealloc;

// Remaining properties
@property(nonatomic) id <GTInfiniteScrollViewDelegate> delegate;

@end

