//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class GTInfiniteScrollWeekCell, NSDate, NSOperationQueue;

@protocol GTInfiniteScrollWeekCellDelegate <NSObject>
- (NSOperationQueue *)filteredCacheQueue;
- (NSOperationQueue *)renderingQueue;
- (NSDate *)selectedMonthForWeekCell:(GTInfiniteScrollWeekCell *)arg1;
- (BOOL)isCurrentDate:(NSDate *)arg1;
- (void)weekCell:(GTInfiniteScrollWeekCell *)arg1 willSelectDate:(NSDate *)arg2;
@end

