//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@class NSArray;

@interface GTPopoverView : UIView
{
    struct CGRect boxFrame;
    struct CGSize contentSize;
    struct CGPoint arrowPoint;
    BOOL dismissed;
    id <GTPopoverViewDelegate> delegate;
    UIView *parentView;
    UIView *topView;
    NSArray *subviewsArray;
    UIView *contentView;
    int _selectedIndex;
}

+ (id)showPopoverAtPoint:(struct CGPoint)arg1 inView:(id)arg2 withContentView:(id)arg3 withSelectedIndex:(int)arg4 delegate:(id)arg5;
+ (id)showPopoverAtPoint:(struct CGPoint)arg1 inView:(id)arg2 withViewArray:(id)arg3 withSelectedIndex:(int)arg4 delegate:(id)arg5;
+ (void)initialize;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) id <GTPopoverViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView;
@property(retain, nonatomic) NSArray *subviewsArray; // @synthesize subviewsArray;
- (void)onAccessibilityVoiceOverStatusChanged:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dismissComplete;
- (void)dismiss:(BOOL)arg1;
- (void)dismiss;
- (void)didTapButton:(id)arg1;
- (void)selectNextButton:(id)arg1;
- (void)rotateSelection;
- (void)delayDismiss;
- (void)tapped:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setupLayout:(struct CGPoint)arg1;
- (void)showAtPoint:(struct CGPoint)arg1 inView:(id)arg2 withContentView:(id)arg3 withSelectedIndex:(int)arg4;
- (void)showAtPoint:(struct CGPoint)arg1 inView:(id)arg2 withViewArray:(id)arg3 withSelectedIndex:(int)arg4;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

