//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@class UIImage;

@interface GTTourPageControl : UIView
{
    int _currentPage;
    int _numberOfPages;
    UIImage *selectedImage;
    UIImage *unselectedImage;
    id <GTTourPageControlDelegate> delegate;
}

@property(nonatomic) int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) int numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(nonatomic) id <GTTourPageControlDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIImage *unselectedImage; // @synthesize unselectedImage;
@property(retain, nonatomic) UIImage *selectedImage; // @synthesize selectedImage;
- (void)tapped:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (float)leftMargin;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

