//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GUAlertView.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, UILabel, UITableView, UIView;

@interface GUAlertMultiItemDetail : GUAlertView <UIAlertViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UIView *_tableHolderView;
    UITableView *_tableView;
    NSDictionary *_itemDetail;
    UILabel *_msgLabel;
    int _tableYorigin;
    int _tableHeight;
}

@property(nonatomic) int tableHeight; // @synthesize tableHeight=_tableHeight;
@property(nonatomic) int tableYorigin; // @synthesize tableYorigin=_tableYorigin;
@property(retain, nonatomic) UILabel *msgLabel; // @synthesize msgLabel=_msgLabel;
@property(retain, nonatomic) UIView *tableHolderView; // @synthesize tableHolderView=_tableHolderView;
@property(retain, nonatomic) NSDictionary *itemDetail; // @synthesize itemDetail=_itemDetail;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)heightOfCellWithTitle:(id)arg1 andSubtitle:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)innerShadowImageForRect:(struct CGRect)arg1 withCornerRadius:(float)arg2;
- (id)maskImage:(id)arg1 toPath:(id)arg2;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitleArray:(id)arg5 andItemDetail:(id)arg6;

@end

