//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIControl.h"

@class UIButton;

@interface GUAttachmentButton : UIControl
{
    unsigned int _attachmentCount;
    UIButton *_attachmentBadgeButton;
}

@property(nonatomic) unsigned int attachmentCount; // @synthesize attachmentCount=_attachmentCount;
- (void)dealloc;
- (void)createSubviews;
- (id)initWithFrame:(struct CGRect)arg1 target:(id)arg2 action:(SEL)arg3 attachmentCount:(int)arg4;
- (id)initWithFrame:(struct CGRect)arg1 attachmentCount:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

