//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

@class UIActivityIndicatorView, UIImageView, UILabel, UIView;

@interface GULogoVC : UIViewController
{
    UIImageView *_backgroundImageView;
    UIActivityIndicatorView *_fadeActivityIndicatorView;
    UILabel *_fadeLabel;
    UIView *_fadeView;
}

+ (id)presetLogoViewControllerIn:(id)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)dismissFadeLoadingIndicatorAnimated:(BOOL)arg1;
- (void)presentFadeLoadingIndicatorWithLabelText:(id)arg1 animated:(BOOL)arg2;

@end

