//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UISearchBar.h"

@interface GUSearchBar : UISearchBar
{
    UISearchBar *_searchBar;
    struct CGRect _superviewBounds;
}

- (void)layoutSubviews;
- (void)setSelectedScopeButtonIndex:(int)arg1;
- (void)setScopeButtonTitles:(id)arg1;
- (int)selectedScopeButtonIndex;
- (id)scopeButtonTitles;
- (void)initScopeButtons;
- (void)setDelegate:(id)arg1;
- (void)initAdditionalSearchBar;

@end

