//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface GUSkin : NSObject
{
}

+ (id)tasksDatePlaceholderColor;
+ (id)tasksPlaceholderColor;
+ (id)tableCellDetailTextLabelColor;
+ (id)tableBackgroundColor;
+ (struct CGSize)buttonSize;
+ (id)buttonFont;
+ (id)recipientEmailFont;
+ (id)recipientEmailTextColor;
+ (id)buttonTextColor;
+ (float)buttonBorderWidth;
+ (id)buttonBorderColor;
+ (id)preferencesMenuCellFont;
+ (float)eventAttachementButtonVerticalMargin;
+ (float)eventAttachementButtonHorizontalMargin;
+ (id)attachmentSizeColor;
+ (float)folderViewTitleVerticalMargin;
+ (id)folderViewTitleFont;
+ (float)composeTextViewAutoAddedHeight;
+ (float)composeTextViewAdditionalBottomHeight;
+ (float)composeTextViewVerticalMargin;
+ (float)composeTextViewMinHeight;
+ (float)emailPickerHeight;
+ (float)emailPickerWidth;
+ (float)emailPickerLabelHeight;
+ (float)emailPickerLabelWidth;
+ (float)emailPickerToolbarHeight;
+ (id)emailRowViewEncryptionColor;
+ (id)emailRowViewSMIMETitleColor;
+ (id)emailRowViewCalendarButtonColor;
+ (id)emailRowViewSeparatorColor;
+ (id)emailRowViewDetailsButtonColor;
+ (id)goodTabBarTextColor;
+ (id)goodUIViewBackgroundColor;
+ (id)goodUIButtonBorderColor;
+ (id)goodUIButtonChevronColor;
+ (id)goodBrandingColor;
+ (id)boldFontWithSize:(float)arg1;
+ (id)standardFontWithSize:(float)arg1;
+ (id)emailPickerFont;
+ (id)emailDetailedViewTitleFont;
+ (id)emailRowViewSMIMEStopButtonFont;
+ (id)emailRowViewSMIMEMoreDetailsButtonFont;
+ (id)emailRowViewSubjectCalendarButtonFont;
+ (id)emailRowViewSubjectDateFont;
+ (id)emailRowViewSubjectFont;
+ (id)emailRowViewDetailsButtonFont;
+ (id)emailRowViewBoldBigFont;
+ (id)emailRowViewBoldFont;
+ (id)emailRowViewFont;
+ (float)emailRowViewSMIMEProgressViewHeight;
+ (float)emailRowViewSMIMEStopButtonHeight;
+ (float)emailRowViewSMIMEDecryptButtonHeight;
+ (float)emailRowViewCalendarButtonHeight;
+ (float)emailRowViewHorizontalMargin;
+ (float)emailRowViewVerticalMargin;
+ (float)emailRowViewSeparatorHeight;
+ (float)emailRowViewSMIMEHeight;
+ (float)emailRowViewHeight;
+ (id)cellLightBlueSelectionColor;
+ (id)textTertiaryColor;
+ (id)textSecondaryColor;
+ (id)textPrimaryColor;
+ (id)darkGrayFontColor;
+ (id)grayDEMBackgroundColor;
+ (id)lightGrayBackgroundColor;
+ (id)accentColor;
+ (id)barBackgroundColor;
+ (id)barButtonColor;
+ (id)barColor;
+ (id)emailFont;
+ (id)preferredAvailableLanguage;

@end

