//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

#import "UIWebViewDelegate.h"

@class NSString, UIFont, UIScrollView, UIWebView;

@interface GUSubjectView : UIView <UIWebViewDelegate>
{
    UIWebView *_webView;
    UIScrollView *_scrollView;
    NSString *_text;
    NSString *_when;
    NSString *_where;
    UIFont *_subjectFont;
    UIFont *_detailFont;
    BOOL _textIsRTL;
    BOOL _whereIsRTL;
    BOOL _shouldLayoutWebView;
    NSString *_formattedText;
    NSString *_formattedWhereText;
}

@property(copy, nonatomic) NSString *formattedWhereText; // @synthesize formattedWhereText=_formattedWhereText;
@property(copy, nonatomic) NSString *formattedText; // @synthesize formattedText=_formattedText;
@property(retain, nonatomic) UIFont *detailFont; // @synthesize detailFont=_detailFont;
@property(retain, nonatomic) UIFont *subjectFont; // @synthesize subjectFont=_subjectFont;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
@property(nonatomic) struct UIEdgeInsets contentInset;
@property(retain, nonatomic) NSString *where;
@property(retain, nonatomic) NSString *when;
@property(retain, nonatomic) NSString *text;
- (void)sizeToFit;
- (void)layoutSubviews;
- (void)setWebViewNeedsLayout;
- (void)refreshText;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

