//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSMutableArray, UIView;

@interface GUSwipeTracker : NSObject
{
    UIView *view;
    NSMutableArray *trackedTouchPoints;
    id <GUSwipeTrackerDelegate> delegate;
    int primaryAxisSensitivity;
    int secondaryAxisSensitivity;
    int trackedDirections;
}

@property(nonatomic) int trackedDirections; // @synthesize trackedDirections;
@property(nonatomic) int secondaryAxisSensitivity; // @synthesize secondaryAxisSensitivity;
@property(nonatomic) int primaryAxisSensitivity; // @synthesize primaryAxisSensitivity;
@property(nonatomic) id <GUSwipeTrackerDelegate> delegate; // @synthesize delegate;
@property(readonly, nonatomic) UIView *view; // @synthesize view;
- (void)dealloc;
- (BOOL)detectSwipeForDirection:(int)arg1 primaryAxisVal:(int)arg2 secondaryAxisVal:(int)arg3;
- (BOOL)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithView:(id)arg1 delegate:(id)arg2;

@end

