//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@class AppointmentWrapper;

@interface KLAppointmentAvailabilityCellView : UIView
{
    AppointmentWrapper *appWrapper;
    AppointmentWrapper *appWrapperTmp;
    int choice;
    int row;
    BOOL highlighted;
}

@property(nonatomic) int row; // @synthesize row;
@property(nonatomic) int choice; // @synthesize choice;
@property(nonatomic) AppointmentWrapper *appWrapperTmp; // @synthesize appWrapperTmp;
@property(nonatomic) AppointmentWrapper *appWrapper; // @synthesize appWrapper;
@property(nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted;
- (BOOL)isSelectedCell;
- (id)imageNameForRowWithNumber:(int)arg1;
- (id)textForRowWithNumber:(int)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

