//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UITableViewCell.h"

@class KLAppointmentRepeatEndCellView;

@interface KLAppointmentRepeatEndCell : UITableViewCell
{
    KLAppointmentRepeatEndCellView *appView;
}

- (void)dealloc;
- (void)setAppWrapper:(id)arg1 appWrapperTmp:(id)arg2 appWrapperTmpLoc:(id)arg3 row:(int)arg4;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

