//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@interface KLDayViewCountView : UIView
{
    int count;
}

@property(nonatomic) int count; // @synthesize count;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCount:(int)arg1;

@end

