//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "KLGenericViewController.h"

@class CalendarSplitViewController, KLMonthViewMgriPad;

@interface MasterKLMonthViewController : KLGenericViewController
{
    KLMonthViewMgriPad *monthViewMgr;
    CalendarSplitViewController *mainViewController;
}

@property(retain, nonatomic) KLMonthViewMgriPad *monthViewMgr; // @synthesize monthViewMgr;
@property(retain, nonatomic) CalendarSplitViewController *mainViewController; // @synthesize mainViewController;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)updateUIBasedOnOrientation;
- (void)viewDidUnload;
- (void)loadView;
- (id)initWithSplitViewController:(id)arg1;

@end

