//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface MeetingInvitesExtraDataTable : NSObject
{
    struct sqlite3 *db;
    int goodID;
    int mailRecNum;
    int calRecNum;
    int responded;
    int toDelete;
    int deletionDate;
}

+ (id)instance;
@property(nonatomic) int deletionDate; // @synthesize deletionDate;
@property(nonatomic) int toDelete; // @synthesize toDelete;
@property(nonatomic) int responded; // @synthesize responded;
@property(nonatomic) int calRecNum; // @synthesize calRecNum;
@property(nonatomic) int mailRecNum; // @synthesize mailRecNum;
@property(nonatomic) int goodID; // @synthesize goodID;
@property(nonatomic) struct sqlite3 *db; // @synthesize db;
- (void)dealloc;
- (void)dumpMeetingInviteExtraData;
- (void)clearMeetingInviteExtraData;
- (BOOL)getMeetingInviteExtraDataFromCalRecNum;
- (BOOL)removeMeetingInviteExtraData;
- (BOOL)modifyMeetingInviteExtraData;
- (BOOL)addMeetingInviteExtraData;
- (BOOL)getMeetingInviteExtraData;
- (BOOL)ensureDbsPresence;
- (id)startup;

@end

