//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSCalendar, NSDate, NSDateFormatter;

@interface OoODatePickerHandler : NSObject <UIPickerViewDataSource, UIPickerViewDelegate>
{
    NSDate *_startDate;
    NSDate *_date;
    NSDate *_minimumDate;
    NSDate *_today;
    NSCalendar *_currentCallendar;
    NSDateFormatter *_dateFormatter;
    id <OoODatePickerHandlerDelegate> delegate;
    NSDateFormatter *dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter;
@property(retain, nonatomic) NSCalendar *currentCallendar; // @synthesize currentCallendar=_currentCallendar;
@property(nonatomic) id <OoODatePickerHandlerDelegate> delegate; // @synthesize delegate;
- (void)pickerView:(id)arg1 didSelectRow:(int)arg2 inComponent:(int)arg3;
- (float)pickerView:(id)arg1 widthForComponent:(int)arg2;
- (id)pickerView:(id)arg1 viewForRow:(int)arg2 forComponent:(int)arg3 reusingView:(id)arg4;
- (id)getDateWithoutTime:(id)arg1;
- (int)rowNumberForDate:(id)arg1;
- (id)dateForRow:(int)arg1;
- (int)pickerView:(id)arg1 numberOfRowsInComponent:(int)arg2;
- (int)numberOfComponentsInPickerView:(id)arg1;
- (void)pickerView:(id)arg1 setMinimumDate:(id)arg2;
- (void)setMinimumDate:(id)arg1;
- (id)minimumDate;
- (id)restrictDateToPickerBounds:(id)arg1;
- (void)pickerView:(id)arg1 setDate:(id)arg2 animated:(BOOL)arg3;
- (void)setDate:(id)arg1;
- (id)date;
- (void)dealloc;
- (id)initWithDate:(id)arg1;
- (id)init;

@end

