//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface PeopleWrapper : NSObject <NSCopying>
{
    NSString *displayName;
    NSString *email;
    int read;
    int myself;
    int attendence;
    int response;
    int availability;
    int goodContactId;
    BOOL isDistributionList;
}

+ (id)peopleWrapperWithEmail:(id)arg1;
@property(nonatomic) BOOL isDistributionList; // @synthesize isDistributionList;
@property(nonatomic) int goodContactId; // @synthesize goodContactId;
@property(nonatomic) int availability; // @synthesize availability;
@property(nonatomic) int response; // @synthesize response;
@property(nonatomic) int attendence; // @synthesize attendence;
@property(nonatomic) int myself; // @synthesize myself;
@property(nonatomic) int read; // @synthesize read;
@property(retain, nonatomic) NSString *email; // @synthesize email;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName;
- (int)compareDisplayName:(id)arg1;
- (void)dump;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

