//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UITableViewCell.h"

@class NSDictionary, UILabel;

@interface PriorityTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_priorityLabel;
    NSDictionary *_priority;
}

@property(retain, nonatomic) NSDictionary *priority; // @synthesize priority=_priority;
@property(retain, nonatomic) UILabel *priorityLabel; // @synthesize priorityLabel=_priorityLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)resetPriorityWithText:(id)arg1 andColor:(id)arg2;
- (void)setPriorityWithText:(id)arg1 andColor:(id)arg2;
- (void)setTitleText:(id)arg1 andPriorityText:(id)arg2 withPriorityTextColor:(id)arg3;
- (void)dealloc;

@end

