//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "GmmStatusBar.h"

@class CALayer, UIView;

@interface Private_GmmStatusBariOS7 : GmmStatusBar
{
    CALayer *_topBorder;
    UIView *_flashingView;
}

@property(nonatomic) UIView *flashingView; // @synthesize flashingView=_flashingView;
@property(nonatomic) CALayer *topBorder; // @synthesize topBorder=_topBorder;
- (void)animationDidStart:(id)arg1;
- (void)cancelFlashAnimation;
- (void)startFlashAniamtionWithDelay:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

