//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

#import "CalendarEventViewControllerDelegate.h"
#import "UIApplicationDelegate.h"

@class NSDate, NSMutableArray, NSTimer, Reminder, UIAlertView, UIWindow;

@interface ReminderManager : NSObject <UIApplicationDelegate, CalendarEventViewControllerDelegate>
{
    NSTimer *_reminderTimer;
    struct ACalendar *calendarDb;
    NSMutableArray *remindersArray;
    BOOL firstTime;
    struct CDateTimeBits startTime;
    Reminder *_currentReminder;
    NSDate *_currentEndDate;
    UIAlertView *_reminderAlertView;
    BOOL _gracefulShutdown;
    BOOL _wasLocked;
    BOOL _allRemindersSaved;
}

@property(retain, nonatomic) NSTimer *reminderTimer; // @synthesize reminderTimer=_reminderTimer;
- (id).cxx_construct;
- (void)dismissEventViewController:(id)arg1 animated:(BOOL)arg2;
- (void)wipeData;
- (void)showReminderIfLockedPolicyChangedTo:(BOOL)arg1;
- (void)onPolicyChanged:(id)arg1;
- (void)prepareToForeground;
- (void)prepareToBackground;
- (void)dealloc;
- (void)gracefulShutdown;
- (void)dismissAnyAlert;
- (void)doLock;
- (void)doGmmIsLocked;
- (void)setFiredEventOfId:(unsigned long)arg1 andInstance:(long)arg2;
- (void)checkNextReminder:(id)arg1;
- (unsigned long)currentReminderGoodID;
- (void)openAppointmentDetails:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)didPresentAlertView:(id)arg1;
- (void)onAlertButtonShowEvent;
- (void)onAlertButtonClose;
- (void)playAudibleIndicatorIfRelevant;
- (void)showAlert:(id)arg1 forAppointment:(id)arg2;
- (void)checkReminders;
- (void)showNextReminder;
- (void)updateReminders:(id)arg1;
- (void)resumeCheckingReminders;
- (void)doComplianceCheckSucceeded;
- (void)dismissRemindersIfAnyFromMainThread;
- (void)doGmmIsNotLocked;
- (void)checkElapsedReminders;
- (void)doReminderTimerFired:(id)arg1;
- (void)doCalendarReminderDelete:(unsigned long)arg1;
- (void)doCalendarReminderUpdate:(unsigned long)arg1;
- (void)saveRemindersToFileIfInBackground;
- (void)updateReminder:(unsigned long)arg1 forTime:(struct CDateTimeBits)arg2;
- (void)removeReminder:(unsigned long)arg1;
- (void)addReminder:(struct CDateTimeBits)arg1 withGoodId:(unsigned long)arg2 andInstance:(long)arg3;
- (void)saveRemindersToFile;
- (BOOL)loadRemindersFromDb;
- (BOOL)loadRemindersFromFile;
- (BOOL)loadReminders;
@property(nonatomic, getter=areAllRemindersSaved) BOOL allRemindersSaved; // @synthesize allRemindersSaved=_allRemindersSaved;
- (id)init;

// Remaining properties
@property(retain, nonatomic) UIWindow *window;

@end

