//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "RowView.h"

@class UIImageView, UILabel, UISwitch;

@interface RowDominoSecurityComposeView : RowView
{
    UISwitch *_onOff;
    UILabel *_securityText;
    UIImageView *_securityEncryptedIcon;
    UILabel *_title;
}

@property(readonly, nonatomic) UILabel *securityText; // @synthesize securityText=_securityText;
@property(readonly, nonatomic) UISwitch *onOff; // @synthesize onOff=_onOff;
- (void)setContentSizeCategory:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

