//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@interface RowView : UIView
{
    UIView *_separatorLine;
    struct CGRect _originalFrame;
}

@property(readonly, nonatomic) struct CGRect originalFrame; // @synthesize originalFrame=_originalFrame;
@property(readonly, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
- (id).cxx_construct;
- (void)contentSizeCategoryChanged:(id)arg1;
- (void)setContentSizeCategory:(id)arg1;
- (void)setHeight:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

