//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface SBBookmarksManager : NSObject
{
    vector_bfbdcd42 _bookmarks_vector;
    unsigned short _parentId;
    NSMutableArray *_bookmarks;
    NSArray *_specialBookmarks;
}

@property(nonatomic) unsigned short parentId; // @synthesize parentId=_parentId;
@property(retain, nonatomic) NSArray *specialBookmarks; // @synthesize specialBookmarks=_specialBookmarks;
@property(retain, nonatomic) NSMutableArray *bookmarks; // @synthesize bookmarks=_bookmarks;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)deleteBookmarkAtIndex:(int)arg1;
- (void)updateBookmark:(id)arg1 name:(id)arg2 andUrl:(id)arg3;
- (void)createNewBookmarkWithName:(id)arg1 andUrl:(id)arg2;
- (void)removeDebugCommandsFromIndex:(int)arg1;
- (BOOL)removeBookmarkAtIndex:(int)arg1;
- (void)removeBookmarkFromArrayAtIndex:(int)arg1;
- (int)vectorIndexFromIndex:(int)arg1;
@property(readonly, nonatomic) BOOL areEditable;
@property(readonly, nonatomic) BOOL hasBookmarks;
@property(readonly, nonatomic) NSArray *bookmarksArray;
- (void)dealloc;
- (void)refreshBookmarks;
- (id)initWithParentId:(int)arg1;
- (id)init;
- (id)specialBookmarksArray;

@end

