//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface SBCertificateHelper : NSObject
{
}

+ (id)gxTimeToNsDate:(struct GxTime *)arg1;
+ (id)certificateInfoWithCertificateData:(const char *)arg1 len:(int)arg2 detailed:(BOOL)arg3;
+ (id)certFieldValueWithCertData:(const char *)arg1 len:(int)arg2 oid:(const char *)arg3;
+ (id)certDateWithCertData:(const char *)arg1 len:(int)arg2 start:(BOOL)arg3;

@end

