//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface SBCommandConsole : NSObject
{
    id <SBCommandConsoleDelegate> delegate;
    NSMutableArray *_commands;
    NSMutableDictionary *_commandActions;
    NSArray *commandsHistory;
}

@property(retain, nonatomic) NSMutableDictionary *commandActions; // @synthesize commandActions=_commandActions;
@property(retain, nonatomic) NSMutableArray *commands; // @synthesize commands=_commands;
@property(nonatomic) id <SBCommandConsoleDelegate> delegate; // @synthesize delegate;
- (id)evaluateString:(id)arg1;
@property(readonly, nonatomic) NSArray *commandsHistory; // @synthesize commandsHistory;
- (void)addNewCommandAction:(id)arg1;
- (void)addNewCommandString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

