//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class GUBarButtonItem, NSDictionary, SBOpenInController, SBViewController, UIImageView, UIToolbar;

@interface SBDocWebViewBarMgr : NSObject
{
    SBViewController *_sbViewController;
    UIToolbar *_docBarView;
    UIImageView *_background;
    GUBarButtonItem *_optionsButton;
    GUBarButtonItem *_backButton;
    GUBarButtonItem *_labelButton;
    GUBarButtonItem *_tabCounterButton;
    NSDictionary *_event;
    BOOL _docBarEnabled;
    SBOpenInController *_openInController;
}

@property(readonly, nonatomic) UIToolbar *docBarView; // @synthesize docBarView=_docBarView;
@property(readonly, nonatomic) GUBarButtonItem *optionsButton; // @synthesize optionsButton=_optionsButton;
@property(retain, nonatomic) SBOpenInController *openInController; // @synthesize openInController=_openInController;
- (void)sbOpenInControllerDidDismissed:(id)arg1;
- (void)onOptions:(id)arg1;
- (void)onBack:(id)arg1;
- (void)setEvent:(id)arg1;
- (BOOL)isDocBarEnabled;
- (void)updateDocBar;
- (void)showDocBar:(BOOL)arg1;
- (void)setTabCounterValue:(int)arg1;
- (void)positionAndSizeItems;
- (void)onTabCounterTouched:(id)arg1;
- (void)createDocBar;
- (void)dealloc;
- (id)initWithSbViewController:(id)arg1;

@end

