//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSMutableArray;

@interface SBHintViewNotificationQueue : NSObject
{
    BOOL isNotEmpty;
    NSMutableArray *_queue;
}

@property(retain, nonatomic) NSMutableArray *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) BOOL isNotEmpty; // @synthesize isNotEmpty;
- (id)first;
- (void)pop;
- (void)push:(id)arg1;
- (void)dealloc;
- (id)init;

@end

