//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface SBRDHandlerFileNameUtils : NSObject
{
}

+ (id)filePathWithObfuscatedFileName:(id)arg1 filename:(id)arg2;
+ (id)uniqeFilePathForFileName:(id)arg1 inDir:(int)arg2;
+ (id)dirNameWithDir:(int)arg1;
+ (id)filePathWithDir:(int)arg1 andFileName:(id)arg2;
+ (id)obfuscatedFileName:(id)arg1;
+ (id)goodLinkSensitivePath;

@end

