//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface SBRDHandlerDirUtils : NSObject
{
}

+ (BOOL)ensureDir:(id)arg1 error:(id *)arg2;
+ (BOOL)deleteAllFilesInDir:(id)arg1 error:(id *)arg2;
+ (BOOL)deleteFile:(id)arg1 error:(id *)arg2;
+ (BOOL)renameFile:(id)arg1 to:(id)arg2 error:(id *)arg3;

@end

