//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSMutableArray;

@interface SBResourceLoader : NSObject
{
    struct map<SBResourceRequesterToken *, NSURL *, std::less<SBResourceRequesterToken *>, std::allocator<std::pair<SBResourceRequesterToken *const, NSURL *>>> m_asyncTokens;
    struct GxLock m_tokenLock;
    NSMutableArray *_delegates;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)unregisterDelegates;
- (void)unregisterDelegates:(id)arg1;
- (void)registerDelegates:(id)arg1;
- (void)unregisterDelegate:(id)arg1;
- (void)registerDelegate:(id)arg1;
- (void)processGMAEvent:(struct GMAEvent *)arg1 forUrl:(id)arg2 token:(struct SBResourceRequesterToken *)arg3;
- (void)processEmptyResponseForUrl:(id)arg1 withToken:(struct SBResourceRequesterToken *)arg2;
- (void)finalizeResourceLoading:(struct SBResourceDesc *)arg1 hasError:(BOOL)arg2 eor:(BOOL)arg3 startLoadingTime:(unsigned long long)arg4 isUsingCache:(_Bool)arg5;
- (void)processErrorResponseForUrl:(id)arg1 error:(id)arg2;
- (void)processFetchFromCache:(id)arg1 withToken:(struct SBResourceRequesterToken *)arg2;
- (void)processRedirectionNotification:(id)arg1 withToken:(struct SBResourceRequesterToken *)arg2;
- (void)processAuthRequestForUrl:(id)arg1 withToken:(struct SBResourceRequesterToken *)arg2;
- (void)releaseToken:(struct SBResourceRequesterToken *)arg1;
- (void)setToken:(struct SBResourceRequesterToken *)arg1 inErrorType:(id)arg2 error:(id)arg3 url:(id)arg4;
- (id)newUncompressedDataWithToken:(struct SBResourceRequesterToken *)arg1 data:(const basic_string_075b6133 *)arg2 url:(id)arg3 error:(char *)arg4;
- (void)processResourcePartForUrl:(id)arg1 withToken:(struct SBResourceRequesterToken *)arg2;
- (int)foundContentLengthInToken:(struct SBResourceRequesterToken *)arg1;
- (void)onTokenNotificationSelector:(id)arg1;
- (void)onTokenNotification:(id)arg1;
- (struct SBResourceRequesterToken *)newTokenWithCallback:(id)arg1;
- (struct SBIResourceContainerFactory *)resourceContainerFactory;
- (id)obtainThread;
- (int)obtainResourceForResourceDesc:(struct SBResourceDesc *)arg1 token:(struct SBResourceRequesterToken *)arg2;
- (void)abortLoading;
- (void)abortLoadingUrl:(id)arg1;
- (void)startLoadingSelector:(id)arg1 options:(id)arg2;
- (void)startLoading:(id)arg1 options:(id)arg2;
- (void)dealloc;
- (id)init;

@end

