//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSString;

@interface SBResourceDataHandlerFileWriter : NSObject
{
    struct GxEncryptedFile *_file;
    NSString *_filePath;
    NSString *_displayFilename;
    int _state;
}

@property(readonly, nonatomic) int state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *displayFilename; // @synthesize displayFilename=_displayFilename;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (void)reset;
- (BOOL)write:(id)arg1;
- (BOOL)cancelWrite;
- (BOOL)finishWrite;
- (BOOL)startWrite:(id)arg1;
- (void)dealloc;
- (id)init;

@end

