//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UITableViewController.h"

@class NSMutableDictionary;

@interface SBSetProxyPolicyVC : UITableViewController
{
    NSMutableDictionary *proxyData;
    int proxyType;
}

- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;
- (void)updateOptionPolicyBagWithXMLProxy:(id)arg1;
- (id)prepareXMLProxyPolicyForExcHosts:(id)arg1 http:(id)arg2 https:(id)arg3 socks:(id)arg4;
- (id)prepareXMLProxyPolicyForExcHosts:(id)arg1 pacUrl:(id)arg2;
- (BOOL)handleSelectedPAC;
- (BOOL)handleSelectedManualProxy;
- (BOOL)handleSelectedNoProxy;
- (void)onCancel;
- (void)onDone;
- (id)prepareTextField;
- (void)initPacProxy:(id)arg1;
- (void)initManualProxy:(id)arg1;
- (void)initExcHosts:(id)arg1;

@end

