//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIView.h"

@class UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface SBTabView_iPad : UIView
{
    UILabel *_labelURL;
    UIButton *_buttonClose;
    UIImageView *_favicon;
    UIView *_selectedView;
    UIImageView *_deselectedR;
    UIImageView *_deselectedL;
    UIView *_deselectedView;
    UIImageView *_alertIcon;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(retain, nonatomic) UIImageView *alertIcon; // @synthesize alertIcon=_alertIcon;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) UIView *deselectedView; // @synthesize deselectedView=_deselectedView;
@property(retain, nonatomic) UIImageView *deselectedR; // @synthesize deselectedR=_deselectedR;
@property(retain, nonatomic) UIImageView *deselectedL; // @synthesize deselectedL=_deselectedL;
@property(retain, nonatomic) UIView *selectedView; // @synthesize selectedView=_selectedView;
@property(retain, nonatomic) UIImageView *favicon; // @synthesize favicon=_favicon;
@property(retain, nonatomic) UIButton *buttonClose; // @synthesize buttonClose=_buttonClose;
@property(retain, nonatomic) UILabel *labelURL; // @synthesize labelURL=_labelURL;
- (void)dealloc;
- (void)closeButtonPressed;
- (id)initWithFrame:(struct CGRect)arg1;

@end

