//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface SBUtilsThread : NSObject
{
}

+ (void)runOnMainThread:(CDUnknownBlockType)arg1;
+ (id)enqueue:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)sleep:(float)arg1 name:(id)arg2;
+ (void)sleep:(float)arg1;
+ (CDUnknownBlockType)traceBlock:(CDUnknownBlockType)arg1 name:(id)arg2;
+ (void)runOnMainQueueWithoutDeadlocking:(CDUnknownBlockType)arg1;

@end

