//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "RoundedCornerTableViewController.h"

#import "SecuritySetupViewControllerDelegate.h"
#import "SecurityTimeVCDelegate.h"
#import "UIAlertViewDelegate.h"

@class CellWithSwitch, GmmSecureStringObjC, NSString, UITableViewCell;

@interface SecurityMainViewController : RoundedCornerTableViewController <UIAlertViewDelegate, SecuritySetupViewControllerDelegate, SecurityTimeVCDelegate>
{
    struct CSecurityManager *securityManager;
    BOOL flag;
    NSString *currentTimeString;
    CellWithSwitch *cellWithSwitch;
    UITableViewCell *cellTimeout;
    int _actionSheetId;
    BOOL _flag;
    BOOL showCancelButton;
    basic_string_075b6133 _secureStorageKey;
}

@property(nonatomic) BOOL showCancelButton; // @synthesize showCancelButton;
@property(nonatomic) int _actionSheetId; // @synthesize _actionSheetId;
@property(retain, nonatomic) UITableViewCell *cellTimeout; // @synthesize cellTimeout;
@property(retain, nonatomic) CellWithSwitch *cellWithSwitch; // @synthesize cellWithSwitch;
@property(nonatomic) NSString *currentTimeString; // @synthesize currentTimeString;
@property(nonatomic) struct CSecurityManager *securityManager; // @synthesize securityManager;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updatePassword:(id)arg1;
- (void)cancel:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)confirmPassword;
- (void)securityTimeVCDidUpdateTimeout;
- (void)setSwitchStatus;
- (void)securitySetupViewControllerDidSetupPassword;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)calculateHeightForSection0Footer;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (void)switchAction:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
@property(retain, nonatomic) GmmSecureStringObjC *pwd;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setPolicies:(id)arg1;
- (void)getCurrentTimeOut;
- (void)refreshPasswordSettingsView;
- (void)viewDidLoad;
- (id)getDefaultAutomationScreenName;

@end

