//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "SmimeAlertView.h"

@class NSTimer, UIActivityIndicatorView, UIButton;

@interface SmimeCertificateLookUpAlertView : SmimeAlertView
{
    UIActivityIndicatorView *_activityIndicator;
    NSTimer *_cancelButtonTimer;
    UIButton *_cancelUIButton;
}

- (void)dealloc;
- (void)didPresentAlertView:(id)arg1;
- (void)enableCancelButtonNow;
- (void)show;
- (id)init;

@end

