//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface SmimeAlertViewsFactory : NSObject
{
}

- (id)createSenderCertificateMissingAlertView;
- (id)createHowToImportAlertView;
- (id)createSmartCardPairingInstructionView;
- (id)createEncodingView;
- (id)createCertificateLookupView;
- (id)createMoreDetailsViewCertMismatch;
- (id)createMoreDetailsViewWithButtonWithMessage:(id)arg1;
- (id)createMoreDetailsView;
- (id)createSoftTokenImportUnknownErrView;
- (id)createSoftTokenImportCertMismatchView;
- (id)createSoftTokenImportCertProcessingErrView;
- (id)createSoftTokenImportCertBeforeCurrTimeView;
- (id)createSoftTokenImportCertExpiredView;
- (id)createSoftTokenImportStrongProtectionIssueView;
- (id)createSoftTokenImportNotEnoughDiskSpaceView;
- (id)createSoftTokenImportPersistFailedView;
- (id)createSoftTokenImportIncorrectPinView;
- (id)createSoftTokenImportView;
- (id)createIncorrectPinView;
- (id)createPinView;
- (id)create:(int)arg1;

@end

