//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@class NSArray;

@interface THCalendarInfo : NSObject
{
    double _absoluteTime;
    struct __CFCalendar *_calendar;
    struct __CFTimeZone *_timeZone;
    NSArray *_dayNames;
    NSArray *_monthNames;
}

+ (id)currentMonthName;
+ (id)currentDayName;
+ (int)daysInCurrentMonth;
+ (int)currentSecond;
+ (int)currentMinute;
+ (int)currentHourIn24HourFormat;
+ (int)currentHourIn12HourFormat;
+ (int)currentHour;
+ (int)currentYear;
+ (int)currentMonth;
+ (int)currentDayOfMonth;
+ (int)currentDayOfWeek;
+ (double)currentAbsoluteTime;
+ (id)currentDate;
+ (void)setDefaultHourFormat:(int)arg1;
+ (int)defaultHourFormat;
+ (void)setDefaultRoundingRule:(int)arg1;
+ (int)defaultRoundingRule;
+ (id)calendarInfo;
+ (void)initialize;
- (void)onSystemTimeZoneDidChange;
- (void)setTimeZone:(struct __CFTimeZone *)arg1;
- (struct __CFTimeZone *)timeZone;
- (void)setCalendar:(struct __CFCalendar *)arg1;
- (struct __CFCalendar *)calendar;
- (void)setupEnglishNames;
- (int)weeksInMonth;
- (int)weekOfMonth;
- (void)moveToBeginningOfDay;
- (void)moveToFirstDayOfMonth;
- (void)adjustYears:(int)arg1;
- (void)adjustMonths:(int)arg1;
- (void)adjustDays:(int)arg1;
- (void)moveToPreviousYear;
- (void)moveToPreviousMonth;
- (void)moveToPreviousDay;
- (void)moveToNextYear;
- (void)moveToNextMonth;
- (void)moveToNextDay;
- (id)monthName;
- (id)dayName;
- (int)daysInMonth;
- (int)second;
- (int)minute;
- (int)hourIn24HourFormat;
- (int)hourIn12HourFormat;
- (int)hour;
- (int)year;
- (int)month;
- (int)dayOfMonth;
- (int)dayOfWeek;
- (void)resetDateAndTimeToCurrent;
- (void)setDate:(id)arg1;
- (id)date;
- (void)setAbsoluteTime:(double)arg1;
- (double)absoluteTime;
- (void)dealloc;
- (id)init;

@end

