//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIImage.h"

@interface UIImage (GTCalendar)
+ (id)iconForCalendarInRect:(struct CGRect)arg1 withDay:(unsigned int)arg2 andColor:(BOOL)arg3;
+ (void)drawShadowedText:(id)arg1 inRect:(struct CGRect)arg2 withColor:(id)arg3;
+ (void)drawText:(id)arg1 inRect:(struct CGRect)arg2 withColor:(id)arg3;
+ (struct CGImage *)createMaskWithSize:(struct CGSize)arg1 shape:(CDUnknownBlockType)arg2;
+ (id)blackSquareOfSize:(struct CGSize)arg1;
+ (id)newCalendarImageWithDay:(unsigned int)arg1 andColor:(BOOL)arg2;
+ (id)calendarImageWithDay:(unsigned int)arg1 andColor:(BOOL)arg2;
+ (id)calendarTabImageSelectedWithDay:(unsigned int)arg1;
+ (id)calendarTabImageNormalWithDay:(unsigned int)arg1;
@end

