//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

@interface UIViewController (Automation)
- (BOOL)isAutomationScreenActive;
- (void)deactivateAutomationScreen;
- (void)activateAutomationScreen;
- (id)getTopAutomationScreenName;
- (id)getDefaultAutomationScreenName;
- (void)forceAutomationScreen;
- (void)updateAutomationScreenNameAndUpdateState:(id)arg1;
- (void)setAutomationScreen:(id)arg1;
@end

