//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "UIViewController.h"

@interface UIViewController (Swizzle)
- (void)customDidRotateFromInterfaceOrientation:(int)arg1;
- (void)customWillRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)customWillAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)fixNestedModal;
- (void)helperRotateInterface:(int)arg1 animationDuration:(double)arg2;
- (BOOL)needsNestedModalHack;
- (void)dismissModalViewControllerAnimated:(BOOL)arg1 fromSecurityLock:(BOOL)arg2;
- (void)customDismissModalViewControllerAnimated:(BOOL)arg1;
- (void)customPresentModalViewController:(id)arg1 animated:(BOOL)arg2;
- (BOOL)customPresentModalIssueCanOccur;
- (void)dismissModalAfterAnimationDelayAnimated:(id)arg1;
- (void)presentModalAfterAnimationDelayAnimated:(id)arg1;
- (void)dismissModalAfterAnimationDelay:(id)arg1;
- (void)presentModalAfterAnimationDelay:(id)arg1;
- (void)customViewDidLayoutSubviews;
- (void)customViewDidAppear:(BOOL)arg1;
- (void)customViewWillAppear:(BOOL)arg1;
- (void)iOS7BugFixForTintAdjustment;
- (BOOL)isPresentedOnCenterOfScreen;
- (void)customViewDidDisappear:(BOOL)arg1;
- (void)customViewDidLoad;
@end

