//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/
//

#import "NSObject.h"

@interface ZLib : NSObject
{
    struct z_stream_s _stream;
}

+ (id)zlib;
- (id).cxx_construct;
- (int)finishCompressionStream:(id)arg1;
- (int)compressData:(id)arg1 toData:(id)arg2;
- (int)compressedDataSize:(id)arg1;
- (int)compressedDataSizeFromFileAtPath:(id)arg1 closeStream:(BOOL)arg2;
- (void)dealloc;
- (id)init;

@end

