//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface GDActivationInfo : NSObject
{
    NSString *_appId;
    NSString *_appName;
    NSString *_appVersion;
    NSMutableArray *_appAddressArray;
    NSMutableArray *_appIconArray;
    int _appEnterpriseUserNumber;
    NSString *_appEnterpriseName;
}

@property(retain, nonatomic) NSString *appEnterpriseName; // @synthesize appEnterpriseName=_appEnterpriseName;
@property(nonatomic) int appEnterpriseUserNumber; // @synthesize appEnterpriseUserNumber=_appEnterpriseUserNumber;
@property(retain, nonatomic) NSMutableArray *appIconArray; // @synthesize appIconArray=_appIconArray;
@property(retain, nonatomic) NSMutableArray *appAddressArray; // @synthesize appAddressArray=_appAddressArray;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;

@end

