//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "GDActivationIconRetrievedProtocol.h"

@class NSString, UIImageView, UILabel, UIView;

@interface GDActivationDelegationSelectionCell : UITableViewCell <GDActivationIconRetrievedProtocol>
{
    UIImageView *_activationDelegateApplicationIcon;
    UILabel *_upperTextLabel;
    UILabel *_lowerTextLabel;
    UIView *_upperLineView;
    UIView *_lowerLineView;
    struct GDCTPCommandGetAppResource *_getAppIcon;
    struct CIconResourceCallback *_iconResourceCallback;
}

+ (float)widthForLabelWithCellWidth:(float)arg1;
+ (float)xPaddingForWidth:(float)arg1;
+ (float)lineHeight;
+ (id)upperLabelTextFont;
+ (id)lowerLabelTextFont;
+ (float)marginFromIconToLabel;
+ (float)marginBetweenLabels;
+ (float)cellVerticalEdgeMargin;
+ (struct CGSize)iconRectSize;
@property(nonatomic) struct CIconResourceCallback *iconResourceCallback; // @synthesize iconResourceCallback=_iconResourceCallback;
@property(nonatomic) struct GDCTPCommandGetAppResource *getAppIcon; // @synthesize getAppIcon=_getAppIcon;
@property(retain, nonatomic) UIView *lowerLineView; // @synthesize lowerLineView=_lowerLineView;
@property(retain, nonatomic) UIView *upperLineView; // @synthesize upperLineView=_upperLineView;
@property(retain, nonatomic) UILabel *lowerTextLabel; // @synthesize lowerTextLabel=_lowerTextLabel;
@property(retain, nonatomic) UILabel *upperTextLabel; // @synthesize upperTextLabel=_upperTextLabel;
@property(retain, nonatomic) UIImageView *activationDelegateApplicationIcon; // @synthesize activationDelegateApplicationIcon=_activationDelegateApplicationIcon;
- (void)dealloc;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)getIcon:(id)arg1;
- (void)resourceRetrieved:(int)arg1 andData:(const char *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

