//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface GDAppDelegateProxyLayer : NSObject
{
    id <UIApplicationDelegate> appDelegate;
    NSMutableArray *appDelegateMethods;
    BOOL passToHandleURL;
}

+ (id)sharedInstance;
+ (void)initializeGDAppDelegateProxyLayerWithAppDelegate:(id)arg1;
@property BOOL passToHandleURL; // @synthesize passToHandleURL;
@property(retain, nonatomic) NSMutableArray *appDelegateMethods; // @synthesize appDelegateMethods;
@property id <UIApplicationDelegate> appDelegate; // @synthesize appDelegate;
- (BOOL)isURLSchemeBlocked:(id)arg1;
- (id)findAppDelegateMethodWithSel:(SEL)arg1;
- (void)determineEntryAcceptability;
- (void)initializeProxy;

@end

