//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GDViewController, NSObject<OS_dispatch_queue>, NSString;

@interface GDAutomationData : NSObject
{
    NSString *old_password;
    NSString *anew_password;
    NSString *current_password;
    NSString *email;
    NSString *pin;
    NSString *key;
    double fillDelay;
    double executeDelay;
    CDUnknownBlockType callbackBlock;
    NSObject<OS_dispatch_queue> *ui_automation_q;
    GDViewController *gdViewController;
}

@property(nonatomic) GDViewController *gdViewController; // @synthesize gdViewController;
@property(nonatomic) NSObject<OS_dispatch_queue> *ui_automation_q; // @synthesize ui_automation_q;
@property(nonatomic) CDUnknownBlockType callbackBlock; // @synthesize callbackBlock;
@property(nonatomic) double executeDelay; // @synthesize executeDelay;
@property(nonatomic) double fillDelay; // @synthesize fillDelay;
@property(retain, nonatomic) NSString *key; // @synthesize key;
@property(retain, nonatomic) NSString *pin; // @synthesize pin;
@property(retain, nonatomic) NSString *email; // @synthesize email;
@property(retain, nonatomic) NSString *current_password; // @synthesize current_password;
@property(retain, nonatomic) NSString *anew_password; // @synthesize anew_password;
@property(retain, nonatomic) NSString *old_password; // @synthesize old_password;
- (void)dealloc;
- (BOOL)saveAppStatus;
- (BOOL)loadAppStatus;
- (id)init;

@end

