//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDCookieManager : NSObject
{
}

+ (id)sharedGDCookieManager;
+ (void)initialize;
- (void)convertAndSaveCurlCookie:(char *)arg1;
- (_Bool)migrateCurlCookies;
- (void)queueOperationWithSelector:(SEL)arg1;
- (void)loadCookiesOperation;
- (void)loadCookies;
- (void)saveCookies;
- (void)cookiesDidChange:(id)arg1;
- (id)cookiesForURL:(id)arg1;
- (id)cookies;
- (void)clearCookiesForURL:(id)arg1 sessionCookiesOnly:(BOOL)arg2;
- (id)headerStringForCookiesWithURL:(id)arg1;
- (void)_saveCookiesFromHeaderDict:(id)arg1 forBaseURL:(id)arg2;
- (void)saveCookiesFromHeaderDict:(id)arg1 forBaseURL:(id)arg2;
- (void)saveCookiesFromHeader:(id)arg1 forBaseURL:(id)arg2;
- (_Bool)attemptDisableSystemCookies;
- (void)disableSystemCookies;
- (void)dealloc;
- (id)init;

@end

