//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface GDDictionaryComplianceManager : NSObject
{
    NSMutableDictionary *_dlpDict;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *dlpDict; // @synthesize dlpDict=_dlpDict;
- (void)doSpellCorrectionWithOp:(int)arg1;
- (void)dealloc;
- (id)init;

@end

