//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDDirectByteBuffer : NSObject
{
    void *m_dbbInternal;
}

- (id)unreadData;
- (id)unreadDataAsString;
- (void)dealloc;
- (int)bytesUnread;
- (int)read:(char *)arg1 toMaxLength:(int)arg2;
- (void)writeData:(id)arg1;
- (void)write:(const char *)arg1 withLength:(int)arg2;
- (void)write:(const char *)arg1;
- (id)initWithDbb:(struct Dbb *)arg1;
- (id)init;

@end

