//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDFileHandle : NSObject
{
    struct auto_ptr<GSCFileReaderV2> m_apReader;
    struct auto_ptr<GSCFileWriterV2> m_apWriter;
    basic_string_075b6133 m_name;
    _Bool m_isFile;
    _Bool m_isOpen;
    int m_opType;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)truncateFileAtOffset:(unsigned long long)arg1;
- (void)synchronizeFile;
- (int)fileDescriptor;
- (void)closeFile;
- (void)seekToFileOffset:(unsigned long long)arg1;
- (unsigned long long)seekToEndOfFile;
- (unsigned long long)offsetInFile;
- (void)writeData:(id)arg1;
- (id)readDataOfLength:(unsigned int)arg1;
- (id)readDataToEndOfFile;
- (id)availableData;
- (id)sharedFileReader:(unsigned long)arg1;
- (BOOL)isFile;
- (BOOL)isWriting;
- (BOOL)isReading;
- (void)validate;
- (id)initWithFilePath:(id)arg1 opType:(int)arg2;
- (id)realFile:(id)arg1;

@end

