//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNotificationCenter.h"

@class NSMutableArray;

@interface GDNotificationCenter : NSNotificationCenter
{
    NSMutableArray *_arrayOfObserversAndSelectors;
    NSMutableArray *_arrayOfBlockObservers;
    NSMutableArray *_arrayOfQueuedNotifications;
}

+ (void)unlockNotifications;
+ (void)processNotification:(id)arg1;
+ (id)originalDefaultCenter;
+ (id)replacementDefaultCenter;
+ (void)setupProxy;
@property(retain) NSMutableArray *arrayOfQueuedNotifications; // @synthesize arrayOfQueuedNotifications=_arrayOfQueuedNotifications;
@property(retain) NSMutableArray *arrayOfBlockObservers; // @synthesize arrayOfBlockObservers=_arrayOfBlockObservers;
@property(retain) NSMutableArray *arrayOfObserversAndSelectors; // @synthesize arrayOfObserversAndSelectors=_arrayOfObserversAndSelectors;
- (void)refireNotification:(id)arg1 usingDictionary:(id)arg2;
- (BOOL)notification:(id)arg1 matchesDictionary:(id)arg2;
- (id)findAllNotificationDictionariesMatchingNotification:(id)arg1;
- (void)removeObserver:(id)arg1 name:(id)arg2 object:(id)arg3;
- (void)removeObserver:(id)arg1;
- (void)refireOrQueueNotification:(id)arg1 usingDictionaryWithBlock:(id)arg2;
- (void)observedMethod:(id)arg1;
- (BOOL)shouldObserveringObjectPassThrough:(id)arg1;
- (id)addObserverForName:(id)arg1 object:(id)arg2 queue:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 name:(id)arg3 object:(id)arg4;
- (void)postNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)postNotificationName:(id)arg1 object:(id)arg2;
- (id)init;

@end

