//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDViewController.h"

#import "UITextFieldDelegate.h"

@class NSArray, NSString, UITextField, UITextView, UIView, UIWebView;

@interface GDRemoteLockViewController : GDViewController <UITextFieldDelegate>
{
    UITextView *remotelockDetailView;
    UIWebView *remoteLockTicketLabel;
    UIView *keyEnterGroup;
    UITextField *pwdField1;
    UITextField *pwdField2;
    UITextField *pwdField3;
    UITextField *pwdField4;
    NSArray *pwdFields;
    NSString *remoteLockTicket;
    struct GSSecureManagerUnlockCallback *callback;
    struct GDPairingCallback *pairingCallback;
}

@property(nonatomic) struct GDPairingCallback *pairingCallback; // @synthesize pairingCallback;
@property(nonatomic) struct GSSecureManagerUnlockCallback *callback; // @synthesize callback;
@property(retain, nonatomic) NSString *remoteLockTicket; // @synthesize remoteLockTicket;
@property(retain, nonatomic) NSArray *pwdFields; // @synthesize pwdFields;
@property(retain, nonatomic) UITextField *pwdField4; // @synthesize pwdField4;
@property(retain, nonatomic) UITextField *pwdField3; // @synthesize pwdField3;
@property(retain, nonatomic) UITextField *pwdField2; // @synthesize pwdField2;
@property(retain, nonatomic) UITextField *pwdField1; // @synthesize pwdField1;
@property(retain, nonatomic) UIView *keyEnterGroup; // @synthesize keyEnterGroup;
@property(retain, nonatomic) UIWebView *remoteLockTicketLabel; // @synthesize remoteLockTicketLabel;
@property(retain, nonatomic) UITextView *remotelockDetailView; // @synthesize remotelockDetailView;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)dismissKeyboard;
- (void)updateInfoButtonActions;
- (void)updateUIToOrientation:(int)arg1;
- (void)loadViewForAll;
- (void)setupEntryField:(id)arg1;
- (void)loadViewForiPhone;
- (void)loadViewForiPad;
- (void)cancelRemoteLock;
- (void)passwordDidValidate;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)passwordWillValidate;
- (void)onUnlockKeyArrives;
- (void)initInputUIData;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)dealloc;
- (id)makeHTMLStringWithRemoteLockTicket;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

