//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSString, UIPasteboard;

@interface GDServiceDiscovery : NSObject
{
    NSMutableSet *services;
    NSString *_appName;
    UIPasteboard *__pasteboard;
    id <GDServiceDiscoveryDelegate> _delegate;
}

+ (void)setOwnName:(id)arg1;
+ (void)setServiceDelegate:(id)arg1;
+ (void)registeredGFEApplication:(id *)arg1 andVersion:(id *)arg2;
+ (id)applicationsProvidingService:(id)arg1 minimumVersion:(id)arg2;
+ (id)registeredApplications;
+ (void)unregisterService:(id)arg1 version:(id)arg2;
+ (void)registerService:(id)arg1 version:(id)arg2;
+ (void)updateServiceDirectory;
+ (void)enteringForeground;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)instance;
@property(nonatomic) id <GDServiceDiscoveryDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIPasteboard *_pasteboard; // @synthesize _pasteboard=__pasteboard;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSMutableSet *services; // @synthesize services;
- (id)getPasteboard;
- (void)dealloc;
- (id)init;
- (void)handlePasteBoardRemoved;
- (void)handlePasteBoardChange;

@end

