//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDViewController.h"

@class UIImage, UIImageView;

@interface GDStartViewController : GDViewController
{
    UIImage *_lastUsedImage;
    UIImageView *_backgroundImage;
}

@property(retain, nonatomic) UIImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIImage *lastUsedImage; // @synthesize lastUsedImage=_lastUsedImage;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (id)addBackgroundView;
- (void)updateBackgroundImage:(int)arg1;
- (void)updateUIToOrientation:(int)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)launchImage:(int)arg1;

@end

