//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GDAutomationData, GDBlockViewController, GDEProvisionProgressViewController, GDKeyCaptureViewController, GDLoginViewController, GDSetPasswordViewController, GDTouchIDViewController, GDWelcomeViewController, NSBundle, NSString, UIColor;

@interface GDUIReference : NSObject
{
    GDKeyCaptureViewController *keyCaptureViewController;
    GDAutomationData *autoData;
    NSString *email;
    NSString *pin;
    NSString *nonce;
    GDEProvisionProgressViewController *provisionProgressViewController;
    GDBlockViewController *waitViewController;
    GDBlockViewController *blockViewController;
    GDLoginViewController *loginViewController;
    NSString *libUILogoImagePath;
    NSBundle *libUIBundle;
    UIColor *libUIBackgroundColor;
    UIColor *libUIFontColor;
    BOOL m_portrait;
    BOOL m_portraitUpsideDown;
    BOOL m_landscapeRight;
    BOOL m_landscapeLeft;
    BOOL m_orientationsManuallySet;
    GDWelcomeViewController *splashViewController;
    int m_orientationsFromPlist;
    NSString *m_wipedMessage;
    NSString *m_blockedMessage;
    GDSetPasswordViewController *_changePasswordViewController;
    GDTouchIDViewController *_touchIdViewController;
}

+ (void)hideDimmingWindow;
+ (void)showDimmingWindow;
+ (int)resolution;
+ (id)spinnerImage;
+ (id)greyLogo;
+ (id)colorLogo;
+ (id)topBrandingImage;
+ (id)bottomBrandingImage;
+ (id)backgroundImage;
+ (int)iconCornerRadius;
+ (id)font16;
+ (id)font15;
+ (id)font14;
+ (id)font13;
+ (id)font12;
+ (id)font11;
+ (id)font10;
+ (id)font9;
+ (id)font8;
+ (id)font7;
+ (id)font6;
+ (id)font5;
+ (id)font4;
+ (id)font3;
+ (id)font2;
+ (id)font1;
+ (id)colorCb2;
+ (id)colorCb1;
+ (id)customerSecondaryBrandColor;
+ (id)customerPrimaryBrandColor;
+ (void)setCustomerSecondaryBrandColor:(id)arg1;
+ (void)setCustomerPrimaryBrandColor:(id)arg1;
+ (id)color20;
+ (id)color19;
+ (id)darkBlueColor;
+ (id)color18;
+ (id)darkTealColor;
+ (id)color17;
+ (id)statusUnavailableColor;
+ (id)color16;
+ (id)statusBusyColor;
+ (id)color15;
+ (id)statusAvailableColor;
+ (id)color14;
+ (id)chatBubbleBColor;
+ (id)color13;
+ (id)chatBubbleAAndSelectedMessageStateColor;
+ (id)color12;
+ (id)bodyAndListTextColor;
+ (id)color11;
+ (id)bodyTextModalsAndLoginScreensColor;
+ (id)color10;
+ (id)sectionTitleFontColor;
+ (id)color9;
+ (id)secondaryGreyColor;
+ (id)color8;
+ (id)navBarIconsAndLabelsColor;
+ (id)color7;
+ (id)searchBarLineAndNavLineColor;
+ (id)color6;
+ (id)disabledTextColor;
+ (id)color5;
+ (id)hintTextAndChevronsColor;
+ (id)color4;
+ (id)searchFieldAndListLinesColor;
+ (id)color3;
+ (id)tableBackgroundColor;
+ (id)color2;
+ (id)headerAndNavBarBackgroundColor;
+ (id)color1;
+ (id)goodBrandingColor;
+ (id)customerLogo;
+ (void)setCustomerLogo:(id)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
+ (int)getInterfaceOrientationMasksFromPlist;
+ (unsigned int)plistInterfaceOrientationMasks;
+ (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
+ (unsigned int)supportedInterfaceOrientations;
@property(retain, nonatomic) GDTouchIDViewController *touchIdViewController; // @synthesize touchIdViewController=_touchIdViewController;
@property(retain, nonatomic) GDSetPasswordViewController *changePasswordViewController; // @synthesize changePasswordViewController=_changePasswordViewController;
@property(copy, nonatomic) NSString *m_blockedMessage; // @synthesize m_blockedMessage;
@property(copy, nonatomic) NSString *m_wipedMessage; // @synthesize m_wipedMessage;
@property(nonatomic) BOOL m_orientationsManuallySet; // @synthesize m_orientationsManuallySet;
@property(nonatomic) int m_orientationsFromPlist; // @synthesize m_orientationsFromPlist;
@property(nonatomic) BOOL m_landscapeLeft; // @synthesize m_landscapeLeft;
@property(nonatomic) BOOL m_landscapeRight; // @synthesize m_landscapeRight;
@property(nonatomic) BOOL m_portraitUpsideDown; // @synthesize m_portraitUpsideDown;
@property(nonatomic) BOOL m_portrait; // @synthesize m_portrait;
@property(retain, nonatomic) UIColor *libUIFontColor; // @synthesize libUIFontColor;
@property(retain, nonatomic) UIColor *libUIBackgroundColor; // @synthesize libUIBackgroundColor;
@property(retain, nonatomic) NSBundle *libUIBundle; // @synthesize libUIBundle;
@property(retain, nonatomic) NSString *libUILogoImagePath; // @synthesize libUILogoImagePath;
@property(retain, nonatomic) GDLoginViewController *loginViewController; // @synthesize loginViewController;
@property(retain, nonatomic) GDBlockViewController *waitViewController; // @synthesize waitViewController;
@property(retain, nonatomic) GDBlockViewController *blockViewController; // @synthesize blockViewController;
@property(retain, nonatomic) GDEProvisionProgressViewController *provisionProgressViewController; // @synthesize provisionProgressViewController;
@property(retain, nonatomic) GDWelcomeViewController *splashViewController; // @synthesize splashViewController;
@property(retain, nonatomic) NSString *nonce; // @synthesize nonce;
@property(retain, nonatomic) NSString *email; // @synthesize email;
@property(retain, nonatomic) NSString *pin; // @synthesize pin;
@property(retain, nonatomic) GDAutomationData *autoData; // @synthesize autoData;
@property(retain, nonatomic) GDKeyCaptureViewController *keyCaptureViewController; // @synthesize keyCaptureViewController;
- (unsigned int)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (void)enqueueToRemoveBaseViewController:(id)arg1;
- (void)removeBaseViewController:(id)arg1;

@end

