//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSRecursiveLock, UIWindow;

@interface GDUIWindowProxyLayer : NSObject
{
    BOOL _isControllingWindows;
    UIWindow *_currentKeyWindow;
    NSMutableArray *_heldWindows;
    NSRecursiveLock *_windowLock;
}

+ (void)setupProxy;
+ (id)sharedInstance;
@property(retain, nonatomic) NSRecursiveLock *windowLock; // @synthesize windowLock=_windowLock;
@property(retain, nonatomic) NSMutableArray *heldWindows; // @synthesize heldWindows=_heldWindows;
@property(retain, nonatomic) UIWindow *currentKeyWindow; // @synthesize currentKeyWindow=_currentKeyWindow;
@property BOOL isControllingWindows; // @synthesize isControllingWindows=_isControllingWindows;
- (void)revealWindows;
- (void)hideWindows;
- (void)cleanOutStash;
- (BOOL)isWindowInStash:(id)arg1;
- (void)makeWindowKey:(id)arg1;
- (void)removeWindowFromStash:(id)arg1;
- (void)addWindowToStash:(id)arg1;
- (void)addNewKeyWindow:(id)arg1;
- (void)dealloc;
- (id)init;

@end

