//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDWebView : NSObject
{
}

+ (id)keyForUIWebView:(id)arg1;
+ (void)setDataDelegate:(id)arg1 forUIWebView:(id)arg2;
+ (void)setConnectionDelegate:(id)arg1 forUIWebView:(id)arg2;
+ (void)removeAttributesForUIWebView:(id)arg1;
+ (id)attributesForUIWebView:(id)arg1;
+ (void)setDocumentURL:(id)arg1 onUIWebView:(id)arg2;
+ (id)tagRequest:(id)arg1 forUIWebView:(id)arg2;
+ (BOOL)protocolRequest:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
+ (void)protocolRequest:(id)arg1 didConnectVia:(id)arg2;
+ (BOOL)protocolRequest:(id)arg1 willConnectVia:(id *)arg2;
+ (void)protocolDidFinishLoadingForRequest:(id)arg1;
+ (void)protocolRequest:(id)arg1 didFailWithError:(id)arg2;
+ (void)protocolRequest:(id)arg1 didReceiveData:(id)arg2;
+ (void)protocolRequest:(id)arg1 didReceiveResponse:(id)arg2;
+ (BOOL)protocolWillSendRequest:(id *)arg1;
+ (void)invoke:(id)arg1 andManageArgAt:(int)arg2;
+ (void)invoke3:(id)arg1;
+ (void)invoke2:(id)arg1;
+ (void)invoke:(id)arg1;
+ (id)safeDictionary:(id)arg1 objectForKey:(id)arg2;
+ (void)safeDictionaryRemoveAllObjects:(id)arg1;
+ (void)safeDictionaryRemoveObject:(id)arg1 forKey:(id)arg2;
+ (void)safeDictionary:(id)arg1 setObject:(id)arg2 forKey:(id)arg3;
+ (id)rootDomain:(id)arg1;
+ (id)connectionDelegateThread:(id)arg1;
+ (id)connectionDelegate:(id)arg1;
+ (id)dataDelegateThread:(id)arg1;
+ (id)dataDelegate:(id)arg1;
+ (BOOL)isMemberOfDomain:(id)arg1 domain:(id)arg2;
+ (id)attributesForRequest:(id)arg1 ensuringDefaultHasDelegateFor:(id)arg2 ensuringDefaultRespondsTo:(SEL)arg3;
+ (void)finalise;
+ (void)initialise;
+ (id)registry;

@end

