//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSString;

@protocol GTServiceClientDelegate <NSObject>
- (void)GTServiceClientGetUserDataSharingKey:(id *)arg1;
- (void)GTServiceClientGetLastActivityTime:(long long *)arg1;
- (void)GTServiceClientSetLastActivityTime:(long long)arg1;
- (void)GTServiceClientDidReceiveFrom:(NSString *)arg1 withParams:(id)arg2 withAttachments:(NSArray *)arg3 correspondingToRequestID:(NSString *)arg4;
- (BOOL)GTServiceClientDidConnectTo:(NSString *)arg1 withServerCertificate:(NSData *)arg2 withServerCertificateFromOpen:(NSData *)arg3 withEnterpriseMatch:(BOOL)arg4;
- (void)GTServiceClientWillConnectTo:(NSString *)arg1 withClientCertificate:(id *)arg2 withClientCertificatePrivateKey:(id *)arg3 withPkcs12Password:(id *)arg4 withServerCertificate:(id *)arg5 withEnterpriseUserNumber:(int *)arg6;

@optional
- (void)GTServiceClientDidFinishSendingTo:(NSString *)arg1 withAttachments:(NSArray *)arg2 withParams:(id)arg3 correspondingToRequestID:(NSString *)arg4;
- (void)GTServiceClientDidReceiveActivationResponse:(int)arg1 withProvId:(NSString *)arg2 withPin:(NSString *)arg3 fromApplication:(NSString *)arg4 wasSuccessful:(BOOL)arg5;
- (void)GTServiceClientDidReceiveAuthResponse:(NSData *)arg1 fromApplication:(NSString *)arg2 wasSuccessful:(BOOL)arg3;
- (BOOL)GTServiceClientWillSendAttachmentData:(id *)arg1 withDataBlockLength:(int)arg2 withFilename:(NSString *)arg3 withFileSize:(int *)arg4 toApplication:(NSString *)arg5 correspondingToRequestID:(NSString *)arg6;
- (void)GTServiceClientDidReceiveAttachmentData:(NSData *)arg1 withFilename:(NSString *)arg2 lastBlock:(BOOL)arg3;
- (void)GTServiceClientWillConnectTo:(NSString *)arg1 withClientCertificate:(id *)arg2 withClientCertificatePrivateKey:(id *)arg3 withPkcs8Password:(id *)arg4 withServerCertificate:(id *)arg5 withEnterpriseUserNumber:(int *)arg6;
@end

