//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (GDARProxy)
+ (id)replacementClassPathsForResourcesOfType:(id)arg1 inDirectory:(id)arg2;
+ (id)originalClassPathsForResourcesOfType:(id)arg1 inDirectory:(id)arg2;
+ (id)replacementClassPathForResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
+ (id)originalClassPathForResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
+ (id)replacementURLsForResourcesWithExtension:(id)arg1 subdirectory:(id)arg2 inBundleWithURL:(id)arg3;
+ (id)originalURLsForResourcesWithExtension:(id)arg1 subdirectory:(id)arg2 inBundleWithURL:(id)arg3;
+ (id)replacementURLForResource:(id)arg1 withExtension:(id)arg2 subdirectory:(id)arg3 inBundleWithURL:(id)arg4;
+ (id)originalURLForResource:(id)arg1 withExtension:(id)arg2 subdirectory:(id)arg3 inBundleWithURL:(id)arg4;
+ (id)replacementBundleWithURL:(id)arg1;
+ (id)originalBundleWithURL:(id)arg1;
+ (id)replacementBundleWithPath:(id)arg1;
+ (id)originalBundleWithPath:(id)arg1;
+ (void)replaceNSBundle;
- (id)replacementPathsForResourcesOfType:(id)arg1 inDirectory:(id)arg2 forLocalization:(id)arg3;
- (id)originalPathsForResourcesOfType:(id)arg1 inDirectory:(id)arg2 forLocalization:(id)arg3;
- (id)replacementPathsForResourcesOfType:(id)arg1 inDirectory:(id)arg2;
- (id)originalPathsForResourcesOfType:(id)arg1 inDirectory:(id)arg2;
- (id)replacementPathForResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3 forLocalization:(id)arg4;
- (id)originalPathForResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3 forLocalization:(id)arg4;
- (id)replacementPathForResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
- (id)originalPathForResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
- (id)replacementPathForResource:(id)arg1 ofType:(id)arg2;
- (id)originalPathForResource:(id)arg1 ofType:(id)arg2;
- (id)replacementURLsForResourcesWithExtension:(id)arg1 subdirectory:(id)arg2 localization:(id)arg3;
- (id)originalURLsForResourcesWithExtension:(id)arg1 subdirectory:(id)arg2 localization:(id)arg3;
- (id)replacementURLsForResourcesWithExtension:(id)arg1 subdirectory:(id)arg2;
- (id)originalURLsForResourcesWithExtension:(id)arg1 subdirectory:(id)arg2;
- (id)replacementURLForResource:(id)arg1 withExtension:(id)arg2 subdirectory:(id)arg3 localization:(id)arg4;
- (id)originalURLForResource:(id)arg1 withExtension:(id)arg2 subdirectory:(id)arg3 localization:(id)arg4;
- (id)replacementURLForResource:(id)arg1 withExtension:(id)arg2 subdirectory:(id)arg3;
- (id)originalURLForResource:(id)arg1 withExtension:(id)arg2 subdirectory:(id)arg3;
- (id)replacementURLForResource:(id)arg1 withExtension:(id)arg2;
- (id)originalURLForResource:(id)arg1 withExtension:(id)arg2;
- (id)replacementBundleIdentifier;
- (id)originalBundleIdentifier;
- (id)replacementInfoDictionary;
- (id)originalInfoDictionary;
- (id)replacementBuiltInPlugInsPath;
- (id)originalBuiltInPlugInsPath;
- (id)replacementSharedSupportPath;
- (id)originalSharedSupportPath;
- (id)replacementSharedFrameworksPath;
- (id)originalSharedFrameworksPath;
- (id)replacementPrivateFrameworksPath;
- (id)originalPrivateFrameworksPath;
- (id)replacementPathForAuxiliaryExecutable:(id)arg1;
- (id)originalPathForAuxiliaryExecutable:(id)arg1;
- (id)replacementExecutablePath;
- (id)originalExecutablePath;
- (id)replacementResourcePath;
- (id)originalResourcePath;
- (id)replacementBundlePath;
- (id)originalBundlePath;
- (id)replacementBuiltInPlugInsURL;
- (id)originalBuiltInPlugInsURL;
- (id)replacementSharedSupportURL;
- (id)originalSharedSupportURL;
- (id)replacementSharedFrameworksURL;
- (id)originalSharedFrameworksURL;
- (id)replacementPrivateFrameworksURL;
- (id)originalPrivateFrameworksURL;
- (id)replacementURLForAuxiliaryExecutable:(id)arg1;
- (id)originalURLForAuxiliaryExecutable:(id)arg1;
- (id)replacementExecutableURL;
- (id)originalExecutableURL;
- (id)replacementResourceURL;
- (id)originalResourceURL;
- (id)replacementBundleURL;
- (id)originalBundleURL;
- (id)replacementInitWithURL:(id)arg1;
- (id)originalInitWithURL:(id)arg1;
- (id)replacementInitWithPath:(id)arg1;
- (id)originalInitWithPath:(id)arg1;
- (id)getHandleObj;
- (void)setHandleObj:(id)arg1;
@end

