//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableURLRequest.h"

@interface NSMutableURLRequest (GDNET)
- (BOOL)disablePeerVerification;
- (BOOL)disableHostVerification;
- (BOOL)setAuthorisationCredentials:(id)arg1 withProtectionSpace:(id)arg2;
- (BOOL)setAuthorizationCredentials:(id)arg1 withProtectionSpace:(id)arg2;
- (BOOL)failOnAuthorisationChallenge;
- (BOOL)failOnAuthorizationChallenge;
@end

