//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (GDPM)
- (void)replacementDismissModalViewControllerAnimated:(BOOL)arg1;
- (void)originalDismissModalViewControllerAnimated:(BOOL)arg1;
- (void)replacementPresentModalViewController:(id)arg1 animated:(BOOL)arg2;
- (void)originalPresentModalViewController:(id)arg1 animated:(BOOL)arg2;
- (void)replacementDismissViewControllerAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)originalDismissViewControllerAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)replacementPresentViewController:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)originalPresentViewController:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)replacementAwakenFromNib;
- (void)originalAwakenFromNib;
- (id)replacementInit;
- (id)originalInit;
@end

