//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface UIWindow (ProxyLayer)
- (void)replacementAddRootViewControllerViewIfPossible;
- (void)originalAddRootViewControllerViewIfPossible;
- (void)replacementSendEvent:(id)arg1;
- (void)originalSendEvent:(id)arg1;
- (void)replacementSetHidden:(BOOL)arg1;
- (void)originalSetHidden:(BOOL)arg1;
- (void)replacementSLH:(BOOL)arg1;
- (void)originalSLH:(BOOL)arg1;
- (BOOL)isPassThroughWindow;
- (void)replacementMakeKeyWindow;
- (void)originalMakeKeyWindow;
- (void)replacementMakeKeyAndVisible;
- (void)originalMakeKeyAndVisible;
- (void)replacementResignKeyWindow;
- (void)originalResignKeyWindow;
- (void)hideWindowsMeetingCriteriaExceptWindow:(id)arg1;
@end

